### ISSUE TITLE
The empty folder doesn't show in the file share after uploading it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#1001]
**OS:** Win 10
**Build:** 20210905.1
**Regression:** Not a regression

**Repro Steps:**
1. Right click one file share --> Click "Upload Folder..." --> Select one **empty folder** to upload.
2. Check whether the empty folder shows in this file share.

**Expect:**
The empty folder shows well in this file share.

**Actual:**
The empty folder doesn't show in this file share, but the output log shows "Successfully uploaded...".
![image](https://user-images.githubusercontent.com/45614674/132291173-9915124f-0afc-4fa6-a4e4-000fdf06caee.png)

**More Info:**
1. This issue does not reproduce in Storage Explorer.
2. Upload the empty folder to this file share from Storage Explorer then refresh the file share node in VS Code, the empty folder shows well in VS Code.
3. This issue also reproduces on the previous released storage extension 0.12.1.

**Comment by v-mengwe** [comment]
Verified on the latest build 20211205.1, this issue still reproduces for now, we will continue to track this issue.
