### ISSUE TITLE
Bug: New storage resource name incorrectly reported as already existing

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurestorage#1003]
I have access to many subscriptions but only 1 is selected in the drop down list of subscriptions in VsCode. Because only 1 is selected, I thought the Azure resource extensions, such as Storage, limited the validation to that single subscription.

I tried creating a new storage resource in that 1 subscription,, and even selected the advanced path through the quickpick prompts, but I can't create the storage resource with the name selected because it already exists in a different repo. 

The image shows the error text and the storage resources in the current subscription. You can see the name isn't in the list of current storage resources.

![image](https://user-images.githubusercontent.com/41597107/135123730-44ca0a03-d479-47e5-863d-5f7f0d69d2d7.png)

**Comment by nturinski** [comment]
Hi @diberry

I believe that you're running into this issue because storage account names must be globally unique as per: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#storage-account-endpoints

> Your storage account name must be unique within Azure. No two storage accounts can have the same name.

Feel free to re-open if this doesn't resolve your issue

**Comment by diberry** [comment]
Yeah - you are correct. Sorry about that.

**Comment by nturinski** [comment]
No worries 😃 Thanks for using the extensions
