### ISSUE TITLE
Support uploading symlinked folders

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestorage#1004]
We can do this now since https://github.com/Azure/azure-storage-azcopy/issues/1174 was fixed. Here's the code in question:

https://github.com/microsoft/vscode-azurestorage/blob/0d7252fee3b4474ae9c4ed2ef15f3d1292e7aecb/src/commands/azCopy/azCopyTransfer.ts#L36-L38

**Comment by alexweininger** [comment]
This seems to be working for me. I can upload symlinked folders to a File Share from macOS. Symlinks were created using `ln`.

**Comment by nturinski** [comment]
Tried it with Windows, using `mklink /J SymLink OriginalFolder`. Seems to upload alright for me as well.

**Comment by nturinski** [comment]
Also worth mentioning, but this was also closed: https://github.com/Azure/azure-storage-azcopy/issues/1174

**Comment by alexweininger** [comment]
We should add a test case in OneNote for this
