### ISSUE TITLE
All the blobs don't display on the tree view after creating an existing blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#101]
Repro Steps:
1. Choose one blob container which contains one blob at least.
2. Create an existing blob named 'test1'.
3. Check the tree view.

Expect:
Fail to create the existing blob and all the blobs still display under the blob container.
![expect](https://user-images.githubusercontent.com/34729022/37816784-45581230-2e6c-11e8-9fd7-521a01844ef3.png)

Actual:
All the blobs don't display under the blob container.
![actual](https://user-images.githubusercontent.com/34729022/37816788-48c05676-2e6c-11e8-947a-d452dea801f4.png)

More info:
1. This issue doesn't reproduce after refreshing the blob container.
2. This issue also reprodcues on file share/queue/table.

**Comment by StephenWeatherford** [comment]
We should be warning about overwriting an existing blob.

**Comment by StephenWeatherford** [comment]
Won't be an issue after #93 is fix.ed
