### ISSUE TITLE
Pop up an error 'Failed with code "404"' after deleting a file with two levels of parent directories for an attached storage account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1012]
**OS:** Win 10
**Build:** 20220119.1
**Regression:** Not a regression

**Repro Steps:**
1. Expand an attached storage account.
2. Right click one file share -> Click "Create Directory..." -> Type name "a".
2. Right click "a" directory -> Click "Create Subdirectory..." -> Type name "b".
3. Right click "b" directory -> Click "Create Empty File..." -> Type name "test".
4. Right click "test" file -> Click "Delete...".
5. Check whether doesn't pop up an error.

**Expect:**
Don't pop up an error.

**Actual:**
Pop up an error 'Failed with code "404"'.
![image](https://user-images.githubusercontent.com/57662131/150059534-fc4a6f21-0c43-441b-8cd3-dcaff604d5fa.png)

**More Info:**
1. This issue also reproduces for blob container.
2. This issue also reproduces on local emulator.
3. This issue does not reproduce on common storage account.

**Comment by alexweininger** [comment]
@nturinski This may be fixed by https://github.com/microsoft/vscode-azurestorage/pull/1102?

**Comment by alexweininger** [comment]
I can't repro this anymore on main. But I can repro on the released extension. Seems like #1102 fixed this.
