### ISSUE TITLE
[Codespaces][Suggestion] Don't show "Open in Storage Explorer" menu item on local Codespaces

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#1023]
**Environment:** **Local Codespaces**
**Build Version:** 20220128.1
**Regression:** Not a regression

**Repro Steps:**
1. Create a new storage account.
2. Right click the storage account and check its context menu.

**Actual:**
The menu item "Open in Storage Explorer" shows in the context menu.
![image](https://user-images.githubusercontent.com/45614674/151534464-15138a01-e861-444c-a397-6ba32a8574c2.png)

**Suggestion:**
Don't show "Open in Storage Explorer" menu item on local Codespaces.

**More Info:**
There is no "Open in Storage Explorer" menu item on Linux or remote Codespaces.

**Comment by wwlorey** [comment]
This warning appears when you click "Open in Storage Explorer" in local Codespaces:

![Screen Shot 2022-02-09 at 11 54 08 AM](https://user-images.githubusercontent.com/22795803/153279650-0baddf5e-0f0a-4a55-8e91-4f9a98ecc9cc.png)

When you click "browse" it shows the file picker for files on the Codespaces VM:

![Screen Shot 2022-02-09 at 11 55 45 AM](https://user-images.githubusercontent.com/22795803/153279995-21de4728-5232-42e3-971d-9da9cc2d0d72.png)

There doesn't appear to be a way to select local files from this picker so it doesn't make sense to show "Open in Storage Explorer" in this case.
