### ISSUE TITLE
Extension won't start because of permissions issue

### ISSUE THREAD

**Issue by aloneguid** [microsoft/vscode-azurestorage#1024]
Extension won't start if one of the storage account is not accessible, in this case storage account managed by Databricks:

```The client '[REDACTED]' with object id '[REDACTED]' has permission to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' on scope '/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Storage/storageAccounts/dbstorage[REDACTED]'; however, the access is denied because of the deny assignment with name 'System deny assignment created by Azure Databricks [REDACTED]' and Id '[REDACTED]' at scope '[REDACTED].```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3155189/152318293-441e0257-53cd-458c-ad58-dc14b45f0b5f.png">

**Comment by wwlorey** [comment]
Hi @aloneguid, thanks for filing this. A few questions:

* Is this permissions problem something you can resolve in the [Azure portal](https://portal.azure.com)? 
* Are you requesting that the Azure Storage Extension provide a way to manage storage account permissions from within the extension?
