### ISSUE TITLE
VSCode Authentication error

### ISSUE THREAD

**Issue by filipembmarques** [microsoft/vscode-azurestorage#1026]
Does this occur consistently? Yes
Repro steps:

1. Sign in azure storage on vscode
2. Redirect to Microsoft page to Login
3. [No authorization error]

Action: AzureTreeDataProvider.getChildren
Error type: AuthorizationFailed
Error Message: The client '---' with object id 'redacted:id' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '{scope}' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.13.0
OS: linux
OS Release: 5.13.0-28-generic
Product: Visual Studio Code
Product Version: 1.61.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:663466
extension.bundle.js:2:652147
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by wwlorey** [comment]
Thanks for filing this, @filipembmarques. When you attempt to list your storage accounts in the [Azure Portal](https://portal.azure.com) do you get a similar error? If you aren't able to get access there it's definitely an access control problem.

Similar: https://github.com/microsoft/vscode-azurestorage/issues/684

**Comment by filipembmarques** [comment]
> Thanks for filing this, @filipembmarques. When you attempt to list your storage accounts in the [Azure Portal](https://portal.azure.com) do you get a similar error? If you aren't able to get access there it's definitely an access control problem.
> 
> Similar: #684

I can access my storage account without any problem. But all storages in vscode extension are marked as invalid, even after sing in

**Comment by wwlorey** [comment]
@filipembmarques have you been granted reader rights to these accounts? There's an open issue to support this in the extension: https://github.com/microsoft/vscode-azurestorage/issues/967
