### ISSUE TITLE
The delete process is stopped when deleting a folder again

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1029]
**OS:** Win10
**Build Version:** 20220307.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a storage account.
2. Right click the File Shares -> Create a new file share -> Upload a folder contained 100 files to it.
3. Delete the uploaded folder -> Delete the uploaded folder again during the uploaded folder is deleting.
4. Check whether the delete process is not stopped.

**Expect:**
The delete process is not stopped.

**Actual:**
The delete process is stopped.
![actual1](https://user-images.githubusercontent.com/57662131/157409350-cda838ed-c1fc-4f88-8217-9d33275e63ff.gif)

**More Info:**
This issue doesn't reproduce for the blob container.

**Comment by wwlorey** [comment]
We'll close this as wontfix since the is a pretty edge-case scenario and a reasonable error message is thrown.
