### ISSUE TITLE
An error occurs when creating a storage account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1033]
**OS:** Win10
**Build Version:** 20220324.11
**Regression:** Previous Release

**Repro Steps:**

1. F1 -> Click "Create Storage Account..." -> Enter a name.
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/160334063-f4625fd1-7b0a-417b-b004-f51a025fe5dc.png)

**More Info:**
This issue also reproduces when creating an advanced storage account.

**Comment by alexweininger** [comment]
This has been fixed.
