### ISSUE TITLE
Fail to deploy the `dist` project to the storage account with an error

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#1040]
**OS:** All
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Azure Storage Extension Build Version:** 20220505.2 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the resource groups by **Resource Type/Location/ARM Tag**.
2. Create a storage account -> Deploy the `dist` project to the storage account.
3. Check whether succeeds to deploy the `dist` project to the storage account or not.

**Expect:**
Succeed to deploy the `dist` project to the storage account.

**Actual:**
Fail to deploy the `dist` project to the storage account with an error.
<img width="450" alt="Screen Shot 2022-05-06 at 15 06 13" src="https://user-images.githubusercontent.com/62053665/167083646-e3e89908-16e9-419d-953f-2771f5e62a46.png">

**More Info:**
There is a $web blob container in the storage account.
<img width="224" alt="Screen Shot 2022-05-06 at 15 10 04" src="https://user-images.githubusercontent.com/62053665/167084849-1295481e-d66a-42d5-9164-3dfce0a622b2.png">

**More Info:**
This issue doesn't reproduce when the resource groups by Resource Group.

**Comment by v-ruizh** [comment]
This issue also reproduces on the latest main build 20220516.1, the actual behavior shows as below.

Steps:
1. Create a storage account.
2. Deploy project to the above storage account.
3. An error occurs.
![image](https://user-images.githubusercontent.com/45614674/168573581-1d049f5d-b66a-4358-b7d7-54de27c9ca10.png)
4. Deploy again, the error is the same as this issue.
![image](https://user-images.githubusercontent.com/45614674/168573754-b5bd5ded-3d82-4494-a0c6-4e1537b7c79b.png)

**Comment by v-ruizh** [comment]
Verified this issue on build 20220520.3, it does not reproduce.
