### ISSUE TITLE
Fail to detach a storage account with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1045]
**OS:** Windows / Linux
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Azure Storage Extension Build Version:** 20220505.2 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Attached a storage account -> Right click this storage account -> Click "Detach Storage Account".
2. Check whether succeeds to detach this storage account.

**Expect:**
Succeed to detach this storage account.

**Actual:**
Fail to detach this storage account with an error.
![image](https://user-images.githubusercontent.com/57662131/167241512-36f2333e-5847-4607-b2c8-736d126be3a9.png)

**More Info:**

1. There is an error under the "Attached Storage Accounts" node after refreshing the workspace view.
![image](https://user-images.githubusercontent.com/57662131/167241576-69577d78-02ac-43a5-99da-fe243d5cd59c.png)
2. This issue doesn't reproduce on Mac.

**Comment by nturinski** [comment]
This is reproducing on the release version of the extension.  Makes me think it has to do something with VS Code rather than us.  Is it possible that this also was a result of upgrading to Node 14 and we just never caught it?

**Comment by alexweininger** [comment]
> a result of upgrading to Node 14 and we just never caught it?

~Node 14~ Node 16

**Comment by nturinski** [comment]
Can confirm that this is a result of upgrading to Node 16.  Detatch and Delete Postgres Server... both work on [this version](https://code.visualstudio.com/updates/v1_64) of VS Code.

**Comment by alexweininger** [comment]
Better start reading! 😄  https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md
