### ISSUE TITLE
There is no response after clicking "Load More..." for an attached storage account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1046]
**OS:** All
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Azure Storage Extension Build Version:** 20220505.2 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Expand an attached storage account.
2. Right click the Blob Containers -> Create a new blob container -> Upload a folder contains 100 files to it.
3. Expand the folder -> Click "Load More...".
4. Check whether shows all files.

**Expect:**
Shows all files.

**Actual:**
There is no response after clicking "Load More...".

**More Info:**
 This issue doesn't reproduce for unattached storage account.

**Comment by v-xinda** [comment]
Verified on the latest main branch build 20220901.11, it still reproduces for now.

**Comment by alexweininger** [comment]
This is fixed in RGs so once we release it'll be fixed in Storage.
