### ISSUE TITLE
Add OpenInPortal

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#105]
Should this extension have OpenInPortal on storage accounts? Or are we just guiding people to storage explorer instead?

**Comment by StephenWeatherford** [comment]
@JakeRad @fiveisprime Thoughts?  Might be good to have both options.

**Comment by StephenWeatherford** [comment]
Inclined to not have both.

**Comment by StephenWeatherford** [comment]
@JakeRad Jake?

**Comment by JakeRadMSFT** [comment]
I could see both being useful.

**Comment by StephenWeatherford** [comment]
Okay, thanks, and that's what @fiveisprime thought as well.

**Comment by StephenWeatherford** [comment]
Storage Explorer only supports this for storage accounts.  Now so do we.
