### ISSUE TITLE
There is an invalid subdirectory under the parent directory for a file share

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1056]
**OS:** All
**Azure Resource Extension Build Version:** 20220516.8
**Azure Storage Extension Build Version:** 20220517.1

**Repro Steps:**
1. Expand a storage account -> Create a file share to it.
2. Right click the file share -> Click "Create Directory..." -> Enter a name "one".
3. Make sure the "one" directory is not expanded.
4. Right click the "one" directory -> Click "Create Subdirectory..." -> Enter a name "two".
5. Expand the "one" directory.
6. Check whether there is no invalid subdirectory under the "one" directory.

**Expect:**
There is no invalid subdirectory under the "one" directory.

**Actual:**
There is an invalid subdirectory under the "one" directory.
![image](https://user-images.githubusercontent.com/57662131/168791305-40cd6119-c373-4539-b821-bad903f35343.png)

**More Info:**
1. Refresh can fix this issue.
2. This issue doesn't reproduce when the "one" directory is expanded.

**Comment by alexweininger** [comment]
Is this a regression from the previous release?

**Comment by v-xinda** [comment]
@alexweininger   This issue doesn't reproduce on the previous release Azure Storage v0.13.0.

**Comment by alexweininger** [comment]
I'm unable to reproduce this using the current release, or main. @v-xinda could you verify this still reproduces? Thanks!

**Comment by v-xinda** [comment]
@alexweininger   This issue doesn't reproduce on the latest main branch build and current release version.

**Comment by alexweininger** [comment]
Great, thanks!
