### ISSUE TITLE
The created storage account is not focused after clicking "Click to view resource" in "ACTIVITY LOG" 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1062]
**OS:** Mac (M1) & Win10
**Azure Storage Build Version:** 20220522.1
**Resource Goup Build Version:** 20220522.1

**Repro Steps:**
1. Create a storage account.
2. Click "Click to view resource" in "ACTIVITY LOG".
3. Check whether the created storage account is focused.

**Expect:**
The created storage account is focused.

**Actual:**
The created storage account is not focused.

**Comment by alexweininger** [comment]
Although we're calling refresh here https://github.com/microsoft/vscode-azurestorage/blob/b1baac8305dae993b6657437bdb6eea66740a031/src/commands/createStorageAccount.ts#L74

the resources view isn't refreshed so the tree item doesn't appear after creating. Meaning it can't be revealed. This pattern works in all of the other extensions, so I'm not sure what's going on here.

**Comment by MicroFish91** [comment]
Are people still getting this bug? I'm not able to repro on Windows, it works consistently for me.  I'll try Mac shortly.

**Comment by alexweininger** [comment]
It's a race condition, so could be hard to repro. I've repro'd it a few times on macOS.

**Comment by alexweininger** [comment]
This should be fixed now, @v-xinda can you verify if this still reproduces?

**Comment by v-xinda** [comment]
@alexweininger  Verified this issue with the latest build 20230206.1, it doesn't reproduce for now.

**Comment by alexweininger** [comment]
Thank you!
