### ISSUE TITLE
Fail to open a file with an error for an attached storage account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1065]
**OS:** Win10/M1
**Azure Resource Extension Build Version:** 20220523.7
**Azure Storage Extension Build Version:** 20220523.2
**Regression:** Not a regression

**Repro Steps:**
1. Expand an attached storage account -> Create a file share -> Upload a file to it.
2. Click the file to open it. 
3. Check whether succeeds to open the file.

**Expect:**
Succeed to open the file.

**Actual:**
Fail to open the file with an error.
![image](https://user-images.githubusercontent.com/57662131/169963292-2901b492-a26c-4926-9058-f41e18ee516a.png)

**More Info:**

1. This issue doesn't reproduce for the blob container.
2. This issue doesn't reproduce for a normal storage account.

**Comment by bwateratmsft** [comment]
Seems like we can wait for after //Build for this.
