### ISSUE TITLE
An error pops up after expanding "{} ungrouped" node

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1068]
**OS:** Win10
**Azure Resource Extension Build Version:** 20220524.4
**Azure Storage Extension Build Version:** 20220524.2
**Regression:** Not a regression

**Repro Steps:**
1. Make sure the resource groups by ARM Tag.
2. Expand a storage account -> Expand a Blob Containers.
3. Right click a blob container -> Click "Open in File Explorer..." -> Click "Open in current window". 
4.  Navigate to "Resources" tree view -> Expand "{} ungrouped" node.
5. Check whether no error pops up.

**Expect:**
No error pops up.

**Actual:**
1. An error pops up.
![image](https://user-images.githubusercontent.com/57662131/170207236-94ab267c-8498-4dbe-823b-5a02fed7e72a.png)
2. Nothing shows under the "{} ungrouped" node.
![image](https://user-images.githubusercontent.com/57662131/170212922-e5481c8a-895f-4e39-845b-f4802c744909.png)

**More Info:**
This issue also reproduces for the file share.

**Comment by alexweininger** [comment]
I can't reproduce this, @v-xinda does this still reproduce?

**Comment by MicroFish91** [comment]
@motm32 and I can't seem to repro this either

**Comment by alexweininger** [comment]
I got a different (possibly unrelated error) when I followed these steps. Did you encounter any errors at all?

**Comment by MicroFish91** [comment]
I haven't encountered any trying to repro this, are you seeing anything strange?

**Comment by motm32** [comment]
I am getting an error in the output that says "Error: The specified blob does not exist.", but that doesn't seem related to this. Not getting any errors when I expand the "{} ungrouped" node.

**Comment by alexweininger** [comment]
> I am getting an error in the output that says "Error: The specified blob does not exist.", but that doesn't seem related to this. Not getting any errors when I expand the "{} ungrouped" node.

Yeah that's the one I get. We can file a new issue for that if we want

**Comment by v-xinda** [comment]
@alexweininger  Verified this issue on the latest build 20220825, it doesn't reproduce for now.
