### ISSUE TITLE
An error occurs when deleting a file for the blob container or file share

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1073]
**OS:** Win10
**Build Version:**  20220619.1
**Regression:** Previous release

**Repro Steps:**
1. Expand a storage account -> Create a blob container -> Create an empty blob.
2. Delete the above empty blob.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/174706740-e505c326-68d3-4415-9099-46f3ea823951.png)

**More Info:**
1. This issue also reproduces for the file share.
2. This issue also reproduces for the attached storage account and emulator account.

**Comment by alexweininger** [comment]
Does this issue still reproduce?

**Comment by v-xinda** [comment]
@alexweininger   Verified this issue with the latest build 20220630.3, it still reproduces now.
