### ISSUE TITLE
A warning "<workspacename> unable to resolve workspace folder" shows after opening an attached file share in the File Explorer

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1074]
**OS:** Win10
**Build Version:**  20220619.1
**Regression:** Not a regression

**Repro Steps:**

1. Attached a storage account.
2. Expand the storage account -> Expand the File Shares node -> Right click a file share -> Click "Open in File Explorer..." -> Click "Open in new window".
3. Check whether all folders and files that are under the file share show in the new opened File Explorer.

**Expect:**
All folders and files that are under the file share show in the new opened File Explorer.

**Actual:**
A warning "<workspacename> unable to resolve workspace folder" shows in the new opened File Explorer.
![image](https://user-images.githubusercontent.com/57662131/174730152-06474cd7-685c-4bee-b298-997f5a3a250c.png)

**More Info:**

1. This issue also reproduces when selecting "Open in current window" or "Add to workspace".
2. This issue doesn't reproduce for the blob container.
3. This issue doesn't reproduce for the unattached storage account.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azurestorage/pull/1107
