### ISSUE TITLE
Change the minimum VS Code version that the Azure Storage extension supports

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1075]
**OS:** Win10
**Build Version:**  20220619.1

**Repro Steps:**
1. Figure out the oldest vs code version that the extension supports, the version is 1.57.0 as below.
![image](https://user-images.githubusercontent.com/57662131/174741458-aff8635f-6c09-4469-af19-ea8549743252.png)
2. Install VS Code 1.57.1 from https://code.visualstudio.com/updates.
3. Install the Azure Storage extension from VSIX.
4. Expand the subscription node.
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/174740830-dce0a30b-5f14-4f7a-bb6c-3bde885bf273.png)

**Comment by alexweininger** [comment]
Does the error occur on version 1.57.1 only? And does it reproduce consistently?

**Comment by v-xinda** [comment]
@alexweininger   This issue still reproduces consistently on version 1.57.1.
An error as below occurs when creating a storage account on the VS Code version 1.58.2-1.62.3.
![image](https://user-images.githubusercontent.com/57662131/176812966-ae0e5e5f-d165-4d19-bb1a-4083418d6f5a.png)
An error as below occurs when creating a storage account on the VS Code version 1.63.2.
![image](https://user-images.githubusercontent.com/57662131/176832275-68e00fc3-b036-44d7-bc2a-0624fd1c6a26.png)
An error as below occurs when creating a storage account on the VS Code version 1.65.2/1.64.2.
![image](https://user-images.githubusercontent.com/57662131/176816352-426278e5-6eb5-4907-ad54-f14df79a01ff.png)
**No error** occurs when creating a storage account on the VS Code version **1.66.2** .
