### ISSUE TITLE
Cannot see attached storage accounts in plugin sidebar

### ISSUE THREAD

**Issue by Zulu-Inuoe** [microsoft/vscode-azurestorage#1077]
As per the description. In my sidebar I only see the following panels:
* RESOURCES
* WORKSPACE
* HELP AND FEEDBACK

I cannot find my attached storage account anywhere there.
I am running Azurite and can properly connect to it from my locally running function app, but I cannot view containers etc from the VSCode Excention

**Comment by alexweininger** [comment]
It should be present in the Workspace view.

![image](https://user-images.githubusercontent.com/12476526/175426814-6f1d4d87-ee78-4cb0-ae84-ba4f13edf292.png)

If for some reason it's not there, reloading VS Code could get it to show up. Could you share a screenshot of the Workspace view?

**Comment by Zulu-Inuoe** [comment]
![image](https://user-images.githubusercontent.com/1526310/175441204-f90e9ef1-be44-4a15-8dbd-c8dc8808b924.png)

The only option is for the local projects (this is in a C# functions repo).
For some reason right now this directory is empty, though earlier (before reinstalling the plugin) I saw my functions listed here.

Either way, I don't see the same thing in your screenshot. I do remember seeing it in the past. Not sure what might have changed

**Comment by alexweininger** [comment]
Thanks for the quick reply, I have a few more questions.

1. Could you please share what version of the Storage extension you have installed?
1. Could you also share a screenshot of what it looks like when the Local Project tree item is expanded?

**Comment by alexweininger** [comment]
@Zulu-Inuoe are you still experiencing this issue?

**Comment by Zulu-Inuoe** [comment]
@alexweininger Thanks for following up. I'll let you know once I am able to test on Monday.

**Comment by nturinski** [comment]
@Zulu-Inuoe Please let us know whenever you get a chance to test this. We are currently working on a release and would love to try to include a fix for this if it is still occurring.

**Comment by alexweininger** [comment]
Closing as stale, please re-open if you're still experiencing this issue.
