### ISSUE TITLE
Only one file's URL is copied if clicking "Copy to Clipboard" button after uploading two files 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1079]
**OS:** All
**Build Version:**  20220630.2
**Regression:** Not a regression

**Repro Steps:**
1. Expand a storage account -> Create a blob container -> Upload two files to it.
2. Click "Copy to Clipboard" in the notification -> Paste it.
3. Check whether the two files' URL are copied.

**Expect:**
The two files' URL are copied.

**Actual:**
Only one file's URL is copied.

**Comment by alexweininger** [comment]
This is by-design.
