### ISSUE TITLE
Cannot Manipulate or View Storage Tables

### ISSUE THREAD

**Issue by bm-nhs** [microsoft/vscode-azurestorage#1089]
Cannot manipulate or view storage tables.

**Comment by ag-nhs** [comment]
It would be sweet to update many records at once. What a concept!

**Comment by nlmitchell4** [comment]
This extension needs this enhancement ... like yesterday. PLEASE!

**Comment by alexweininger** [comment]
Unfortunately we don't support these features with tables.  As a workaround, you can use the [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/) or the portal.
