### ISSUE TITLE
Blob containers do not refresh in VS Code extension 

### ISSUE THREAD

**Issue by williamohara** [microsoft/vscode-azurestorage#1096]
Does this occur consistently? Yes
Repro steps:
1. Create Storage Account, Container, and Blob
2. log into VS Code Azure Extension
3. see the blob under "Storage Accounts->"Blob Containers"->"<Container Name>"
4. Delete the Blob in Azure UI or via command line
5. Blob Disappears from list in UI
6. Blob Still appears in the Azure extension in VS Code - even after refresh hitting the loop arrow icon at the top of the sidebar for the extension 

I would expect to see the blob disappear - this does not make me confident that i am working with the latest copy - sometimes I just need to view the contents of a file and the UI for the extension  makes it super easy to do so - but i can't trust it :( 

Version: 0.14.2
OS: linux
OS Release: 4.19.128-microsoft-standard
Product: Visual Studio Code
Product Version: 1.69.1
Language: en

**Comment by alexweininger** [comment]
Thanks for filing this bug, we understand how this is annoying.

Until this is fixed, you can use the Refresh in the right click context menu on the Blob Containers node.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/12476526/180094603-69b43738-d4cb-4a4e-889d-36ceb88161c3.png">
