### ISSUE TITLE
Link to install Storage explorer should default to my OS

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#11]
I followed the 'Download' link, but didn't even look at this dropdown:
![screen shot 2017-12-06 at 2 37 45 pm](https://user-images.githubusercontent.com/11282622/33689114-131750e2-da93-11e7-8b42-847d5e6d7f63.png)

I obviously got an error when I tried to install the windows version on a mac haha. Can we default that to the user's OS? It feels like the website should already do that anyway...

**Comment by StephenWeatherford** [comment]
Moved to Storage Explorer: https://devdiv.visualstudio.com/DevDiv/Storage%20Tools/_workitems/edit/561855
