### ISSUE TITLE
An error occurs when creating a file with name "."

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1101]
**OS:** Win 10
**Build:** 20220808.1
**Regression:** Not a Regression

**Repro Steps:**

1. Expand a storage account -> Create a file share.
2. Right click the file share -> Click "Create Directory..." -> Type name "a".
3. Right click "a" folder -> Click "Create Empty File..." -> Type name ".".
4. Check whether it can be created successfully.

**Expect:**
The file can be created successfully.

**Actual:**
An error occurs when creating a file with name ".".
![image](https://user-images.githubusercontent.com/107091828/183552179-0a7606be-1c6d-437e-bd01-30120fd893ee.png)

**More Info:**
1. This issue also reproduces on the previous released Storage extension 0.14.2.
2. The error message is clear when creating a file with invalid name, the invalid name doesn't contain ".".
![image](https://user-images.githubusercontent.com/107091828/183555728-baa2a7c1-fdaf-46c2-99c2-9bc2024e1445.png)

**Comment by alexweininger** [comment]
We could improve the error message here, but this is by design.
