### ISSUE TITLE
Unable to open the file 'This is <bold> bolded' in blob container

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#112]
Repro Steps:
1. Open one blob container and rename one blob as 'This is <bold> bolded' in Storage Explorer.
2. Open the renamed blob in VS Code.

Expect:
The blob file can be opened successfully.

Actual:
Unable to open the blob.
![open](https://user-images.githubusercontent.com/34729022/38545952-d35ac604-3c9a-11e8-9de9-432b459664ba.png)

**Comment by StephenWeatherford** [comment]
Won't fix.  Use storage explorer.
