### ISSUE TITLE
Error: Failed with code "504"

### ISSUE THREAD

**Issue by marcosdiasfte** [microsoft/vscode-azurestorage#1124]
Hi, can you help on the following issue? Thanks in advance.

When try to access Blob containers of a storage account with private endpoint enabled.
Error: This request is not authorized to perform this operation.

![image](https://user-images.githubusercontent.com/89993836/185454941-544caa38-3835-4926-a418-2cb93c31980e.png)

![image](https://user-images.githubusercontent.com/89993836/185454952-ac31cd7a-eb6e-4958-a37e-3f549b5e64ae.png)

![image](https://user-images.githubusercontent.com/89993836/185454992-eb4ef056-54be-422d-a4b6-4381ca11949e.png)

**Comment by alexweininger** [comment]
Hi, if the Storage Account is only accessible through a private endpoint, then only machines inside the VNET will be able to access the Storage Account. 

Are you running VS Code on a virtual machine inside the VNET? 

If you're running VS Code on a machine outside of the VNET, you could access the Storage Account using a VPN or ExpressRoutes.

https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints
