### ISSUE TITLE
Display an odd path after downloading a blob file

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#113]
Repro Steps:
1. Open one blob container and download one blob file.
2. Check the generated path in Output window after downloading successfully.

Expect:
It displays a clear path.

Actual:
It displays an odd path.
![path](https://user-images.githubusercontent.com/34729022/38546052-1fffbad2-3c9b-11e8-990f-f3e5ac2bfd2c.png)

**Comment by StephenWeatherford** [comment]
It looks odd but it's perfectly valid. %3A is the URI encoded version of "\".  As long as it works I think it's fine.

**Comment by StephenWeatherford** [comment]
Won't fix.
