### ISSUE TITLE
An error occurs after creating an empty blob with name "a/b/file01"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1136]
**OS:** Win10
**Build Version:** 20220828.1
**Regression:** Previous release

**Repro Steps:**
1. Create a storage account -> Create a new blob container -> Right click the blob container -> Click "Create Empty Blob..." -> Enter a name "a/b/file01".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
1. An error occurs.
![image](https://user-images.githubusercontent.com/57662131/187154242-668dff79-7331-40c8-8b27-9b0d269790cd.png)
Details in Output:
```
Error: The specified blob does not exist.
RequestId:300b5b22-e01e-001b-5b7d-bb8104000000
Time:2022-08-29T07:58:26.7113902Z
```
2. Only show the blob name "**file01**" under the blob container after creating an empty blob with name "a/b/file01". But after refreshing,  it will show the complete directory.
![image](https://user-images.githubusercontent.com/57662131/187157400-14c6ee65-a2dd-43db-885d-3acfd1aaaa73.png)

**Comment by alexweininger** [comment]
Megan and I confirmed that this only reproduces on Windows. 

Maybe caused by a difference in how Windows file paths work?
