### ISSUE TITLE
Fail to download the file share/blob container to the selected destination from VS Code

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1138]
**OS:** Win10
**Build Version:** 20220830.4
**Regression:** Not a regression

**Repro Steps:**
1. Create a storage account -> Create a new file share. 
2. Right click the file share -> Click "Download..." -> Select a destination.
3. Check whether succeeds to download the file share to the selected destination.

**Expect:**
Succeed to download the file share to the selected destination.

**Actual:**
Fail to download the file share to the selected destination.

**More Info:**
1. This issue also reproduces when downloading a blob container to the selected destination from VS Code.
2. Display "Successfully downloaded to 'c:\Users\Azuretest\Desktop'." in the Output, but the file share doesn't show in the selected destination.
![image](https://user-images.githubusercontent.com/57662131/187617711-426ed6ef-e9fa-40c6-a06a-39f7b11f31d8.png)

**Comment by alexweininger** [comment]
Does this only happen with a freshly created file share (or blob container)? Does it work as expected if the file share isn't empty?

**Comment by v-xinda** [comment]
@alexweininger 
1. This issue only happens for an empty file share or blob container, it doesn't matter if the file share or blob container is created freshly or not. 
2. This issue doesn't reproduce when the file share or blob container isn't empty.
