### ISSUE TITLE
'Upload block blob' displays in the context menu of premium blob container 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#114]
Repro Steps:
1. Expand one premium storage account.
2. Right click one blob container and check the context menu.

Expect:
It should display 'Upload page blob' in the context menu.

Actual:
It displays 'Upload block blob' in the  context menu.
![contextmenu](https://user-images.githubusercontent.com/34729022/38546354-f12d978c-3c9b-11e8-8289-b365f6c34993.png)

**Comment by StephenWeatherford** [comment]
We should probably disable the context menu in this scenario since we don't support page blobs.  I expect they'll get an Azure error here.

**Comment by StephenWeatherford** [comment]
By design for now.  If users try it anyway they should get an error message indicating that block blobs aren't supported.
