### ISSUE TITLE
File uploaded to existing directory shows up in the wrong place

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode-azurestorage#1143]
**Repro steps**
1. Have an existing directory in a blob container
2. Right click on the blob container and click upload files
3. Type in existing directory for destination directory
4. Choose a file to upload and click Upload

**Expect**
The file to appear under the existing directory 

**Actual**
File appears under the blob container
![image](https://user-images.githubusercontent.com/59709511/187988763-2391a4a5-0547-4f00-9c60-9301b7c21f44.png)

After refresh the file moves under the directory

**Comment by alexweininger** [comment]
This doesn't repro on macOS so I assume it's Windows-only.

**Comment by alexweininger** [comment]
This reproduces in the 0.14.2 (current release) as well as main.
