### ISSUE TITLE
FileShare not accessible

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode-azurestorage#115]
VS Code - 1.22.1
Extension: 0.3.0

The only known issue I can see documented is:

> Viewing the contents of tables and queues is not supported.

Is this also include FileShares?

![image](https://user-images.githubusercontent.com/11204251/38559823-a4bf897a-3c99-11e8-9f0a-ce43acb407c2.png)

If this does would there happen to be a timeline as to when they will be supported? I only ask because the Azure Account extension added support for file upload now with Azure Cloud Shell in their latest release. It would be nice to have the ability to interact with those files via this extension.

**Comment by StephenWeatherford** [comment]
@wsmelton 
You should be able to *browse* (enumerate) all of these as containers.  You should be able to browse all the blobs, files and directories as well (blobs containers and file shares).  You should be able to open/view/save blobs and files.

We just don't support displaying the contents of queues or tables.

Does this work for other storage accounts of yours?  Are you sure this isn't a blob storage account (which wouldn't support file shares/queues/tables)?  Can you view them in Storage Explorer?  (Perhaps you don't have permissions to view?)

Thanks,
Stephen

**Comment by StephenWeatherford** [comment]
@wsmelton @chrisdias Any updates here?  Thanks!

**Comment by StephenWeatherford** [comment]
Closing for now due to lack of response.  If the above solutions don't help you to see your file shares and files, please let us know.

**Comment by wsmelton** [comment]
Sorry...missing email notifications on updates to this issue.

VS Code has since updated since I submitted this issue and accessing it now seems to be working fine.

![image](https://user-images.githubusercontent.com/11204251/39558529-f2ae66de-4e54-11e8-9044-b5d5d53dc940.png)

**Comment by StephenWeatherford** [comment]
Glad to hear it, thanks for letting us know.
