### ISSUE TITLE
There is no "Load More..." button after uploading 100 files to a blob container

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#1150]
**OS:** Ubuntu 22.04
**Build Version:** 20220901.11

**Repro Steps:**
1. Expand one storage account -> Right click the Blob Containers -> Create a new blob container -> Upload 100 files to the blob container.
2. Check whether there is a "Load More..." button at the bottom of this blob container.

**Expect:**
There is a "Load More..." button.

**Actual:**
There is no "Load More..." button.

**More Info:**
1. The "Load More..." shows after refreshing the blob container.
2. This issue also reproduces for File Share (Linux OS).
3. This issue does not reproduce on Windows and Mac.

**Comment by nturinski** [comment]
When the load more button doesn't show, how many blob containers are being displayed in the tree view?

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurestorage/issues/1160

**Comment by v-ruizh** [comment]
Verified this issue on the new Storage extension build 20220915.14, it is no longer reproduce.
