### ISSUE TITLE
Suggestion: Ability to browse blob container (Copy URL)

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurestorage#116]
I've got a static site deployed to a blob storage container and i would like to be able to right click on the container and browse to it. 

Today there is no context menu to do this:

![image](https://user-images.githubusercontent.com/1487073/38595327-0474b4ec-3d00-11e8-92d3-dbaa0400b1b1.png)

**Comment by StephenWeatherford** [comment]
Are you asking for a way to copy the URI to the clipboard? Depending on settings, you may or may not be able to actually browse to it (if it's public and publicly enumerable).

**Comment by StephenWeatherford** [comment]
@chrisdias I'm assuming you meant a "Get URL" context menu item and am implementing it that way.

**Comment by chrisdias** [comment]
@StephenWeatherford yes, that would be sufficient.

**Comment by StephenWeatherford** [comment]
Fixed via #129
