### ISSUE TITLE
Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by samuel100** [microsoft/vscode-azurestorage#1178]
I am trying to upload a file to Azure Storage (something I can do using Storage explorer). However, I get the following error:

`Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

I am using WSL. 

More Info
Published
12/12/2017, 18:37:09
Last released
15/09/2022, 22:53:43
Last updated
11/10/2022, 17:06:46
Identifier
ms-azuretools.vscode-azurestorage

**Comment by alexweininger** [comment]
Is the Storage Account you're uploading to attached via SAS Url?

The error is coming from AzCopy, are there additional logs in the output channel? 

It also might be worth trying the operation outside WSL.
