### ISSUE TITLE
Pop up an error message "Error: Could not create table 'tab1'." after creating a new table immediately which name is same as the table you just deleted

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1191]
**OS:** All
**Build:** 20221228.1

**Repro Steps:**

1. Create a new storage account -> Create a new table, e.g. "tab1".
2. Delete the table "tab1".
3. Create a new table with a same name "tab1" immediately.
4. Check error message.

**Expect:**
1. Pop up an error as below.
<img width="643" alt="Screenshot 2022-12-29 at 16 31 36" src="https://user-images.githubusercontent.com/57662131/209925104-fdd09b34-4d96-4ae0-a730-ef2bf0c8b065.png">
2. Error message in Output:
<img width="530" alt="Screenshot 2022-12-29 at 16 15 17" src="https://user-images.githubusercontent.com/57662131/209923307-d84e0d95-413e-4554-adf9-3a3ba4729871.png">

**Actual:**
1. Pop up an error message "Error: Could not create table 'tab1'.", as below.
<img width="649" alt="Screenshot 2022-12-29 at 15 35 22" src="https://user-images.githubusercontent.com/57662131/209924061-0f5b7007-5d84-4351-b19d-5a8061c594b3.png">
2. Error message in Output:
<img width="754" alt="Screenshot 2022-12-29 at 16 34 30" src="https://user-images.githubusercontent.com/57662131/209925330-dab456c9-d261-4ac9-8616-e4ca4ad20440.png">

**More Info:**
This issue doesn't reproduce for Queues/ Blob Containers/ File Shares.

**Comment by nturinski** [comment]
This is a great catch, but it's very edge case and difficult for us to implement a fix. Closing as wontfix
