### ISSUE TITLE
No command works

### ISSUE THREAD

**Issue by JanDonnermayer** [microsoft/vscode-azurestorage#1199]
When using the extension, no command works. It always returns:

Internal error: Expected value to be neither null nor undefined: resourceIdMatches

![image](https://user-images.githubusercontent.com/46857032/216351801-1ea9af67-c037-4df6-b3fb-e646413c42d5.png)

**Comment by alexweininger** [comment]
Could you provide more details for us to reproduce this issue?

* VS Code version
* Azure Storage extension version
* Do you have a workspace open
* What commands did you try?
