### ISSUE TITLE
Multiple 'File not found' errors when I reopen VS Code

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#12]
Repro Steps:
1. Open several blobs from the explorer
1. Do NOT close the tabs
1. Close VS Code
1. Reopen VS Code

Expected: No errors
Actual:
![screen shot 2017-12-06 at 2 45 45 pm](https://user-images.githubusercontent.com/11282622/33689395-2979ee52-da94-11e7-908b-2f2d6c8ea389.png)

**Comment by wwlorey** [comment]
@EricJizbaMSFT I can't repro on 0.7.2, are you still able to?

**Comment by EricJizbaMSFT** [comment]
No I can't repro
