### ISSUE TITLE
When creating a Blob Container through the command palette an extra step appears 

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode-azurestorage#1205]
When using the `Azure Storage: Create Blob Container` command after choosing a Storage Account the next step should be input the name of the new Blob Container but this step appears instead:

![image](https://user-images.githubusercontent.com/59709511/217121835-2e7fae65-7b75-4a1d-af47-2c61cab80fc0.png)

Also reproduces for `Azure Storage: Create File share`, `Azure Storage: Create Table`, and `Azure Storage: Create Queue`.

Edit: Also seems to happen with the Delete command

**Comment by alexweininger** [comment]
Reopening until the fix is merged in resource groups and verified.
