### ISSUE TITLE
Files or folders uploaded to a blob container do not show in workspace view for a local emulator

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode-azurestorage#1207]
_v2 Forward compat_

When you open the blob container in the explorer the uploaded files and folders show there but not in the workspace view.

**Comment by alexweininger** [comment]
I'm having trouble reproducing this. Could you provide more details repro steps?

What I've tried and got working:
* Viewing uploaded files/folders in an Attached Storage Account
* Uploading and viewing things to emulated blob containers

Do you mean that when you upload a file/folder to a blob container, the Resources view is refreshed and shows the newly uploaded items, but the workspace view does not?

**Comment by motm32** [comment]
Repro steps in the workspace view: 
Under the Local Emulator node I right clicked on Blob Container and created a blob container. After that I right clicked and uploaded a file/folder.

I receive a message that the upload succeeded but the file does not show under the blob container in the workspace view even if I refresh the view. 

If I click open in explorer under the blob container in the workspace view the explorer shows the uploaded files/folders. This tells me it seems to have uploaded correctly but isn't being shown for some reason?

**Comment by alexweininger** [comment]
Got it. I might have accidentally been testing with #554 so that could explain why I couldn't repro.

**Comment by alexweininger** [comment]
I have verified that https://github.com/microsoft/vscode-azureresourcegroups/pull/554 fixes this.
