### ISSUE TITLE
There is no "Attached Storage Accounts" command in the "Workspaces (V2)" view

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1214]
**OS:** Win10
**Azure Resource Group Build Version:** 20230212.1
**Azure Storage Build Version:** v0.15.1
**Regression:** Previous release

**Repro Steps:**

1. Make sure install the Azure Resource extension from VSIX.
2. Check the Workspaces (V2) view.

**Expect:**
There is "Attached Storage Accounts" command in the "Workspaces (V2)" view.
![image](https://user-images.githubusercontent.com/107091828/218981478-fb748451-cf7b-427e-98db-259aea8302bc.png)

**Actual:**
There is no "Attached Storage Accounts" command in the "Workspaces (V2)" view.
![image](https://user-images.githubusercontent.com/107091828/218981519-d0a88045-049f-424d-bea0-5fe3ad1ceb35.png)

**Comment by alexweininger** [comment]
This is expected behavior. Although I could see us wanting to change it back so that we can show items here even if there isn't a workspace open.

Are users using these features without a workspace often?

**Comment by v-chenzha** [comment]
@alexweininger  We often open workspace if we want to test the deploy case or other cases (upload files or folders from "Explorer"). Otherwise, we can't open workspace.
