### ISSUE TITLE
No "No matching resources found" displays and no error pops up

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1217]
**OS:** Win10
**Azure Resource Group Build Version:** 20230215.10
**Azure Storage Build Version:** v0.15.1

**Repro Steps:**
1. Make sure no attached storage account.
2. F1 -> Azure Storage: Detach Storage Account -> Select "Attached Storage Account".
3. Check whether displays "No matching resources found" or pops up an error.

**Expect:**
Display "No matching resources found" or pop up an error.

**Actual:**
No "No matching resources found" displays and no error pops up.
![image](https://user-images.githubusercontent.com/107091828/219301723-b11885ab-54db-416d-ae0a-d7cc773115ea.png)

**More Info:**
This issue also reproduces when executing command "Azure Storage: Delete Blob Container.../Delete File Share/Delete Queue/Delete Table" from command palette.

**Comment by alexweininger** [comment]
> This issue also reproduces when executing command "Azure Storage: Delete Blob Container.../Delete File Share/Delete Queue/Delete Table" from command palette.

Just to clarify, this only happens if there are no storage accounts available, correct?

**Comment by alexweininger** [comment]
This is expected behavior.
