### ISSUE TITLE
The deleted storage account disappears after waiting about 5 seconds

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1218]
**OS:** Win10
**Azure Resource Group Build Version:** 20230215.10
**Azure Storage Build Version:** v0.15.1

**Repro Steps:**

1. Delete a storage account.
2. Check whether the deleted storage account disappears immediately after popping up "Successfully deleted storage account 'xxx'.".

**Expect:**
The storage account disappears immediately.

**Actual:**
The deleted storage account disappears after waiting about 5 seconds.
![bug](https://user-images.githubusercontent.com/107091828/219535700-d285fe9d-957c-4f69-a664-fb5146bcb1bc.gif)

**Comment by alexweininger** [comment]
Although slow, this behavior is fine.
