### ISSUE TITLE
TooManyRequests error occured

### ISSUE THREAD

**Issue by TE-KyokuYO** [microsoft/vscode-azurestorage#1222]
From 2/27/2023, When trying connect to blob container with vscode-azurestorage, the detail info is as follows:
    The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more 
    information, see - https://aka.ms/srpthrottlinglimits
We enabled Static website and use this tool to modify files in blob storage.
Also, from Activity Logs, I saw azurestorage sent quite a lot requests to the blob storage.
![image](https://user-images.githubusercontent.com/67782373/222317966-fd029bc6-d879-4e17-ae08-4d90428a8d4d.png)

**Comment by alexweininger** [comment]
This is a regression caused by the v0.6.0 release of the Azure Resources extension. Until we release a fix, a workaround for this issue, is to revert your Azure Resources extension to v0.5.6. Once installed, you may need to reopen the blob container from the Azure Resources view to get it working.

Install older version of Azure Resources
<img width="489" alt="image" src="https://user-images.githubusercontent.com/12476526/222323593-69fed3f1-76c3-470a-af1f-9167572fa981.png">

Reopen blob in VS Code
<img width="351" alt="image" src="https://user-images.githubusercontent.com/12476526/222323731-8b295ae3-6660-4117-b0f3-82480dbc7cc4.png">

**Comment by TE-KyokuYO** [comment]
> This is a regression caused by the v0.6.0 release of the Azure Resources extension. Until we release a fix, a workaround for this issue, is to revert your Azure Resources extension to v0.5.6. Once installed, you may need to reopen the blob container from the Azure Resources view to get it working.
> 
> Install older version of Azure Resources <img alt="image" width="489" src="https://user-images.githubusercontent.com/12476526/222323593-69fed3f1-76c3-470a-af1f-9167572fa981.png">
> 
> Reopen blob in VS Code <img alt="image" width="351" src="https://user-images.githubusercontent.com/12476526/222323731-8b295ae3-6660-4117-b0f3-82480dbc7cc4.png">
@alexweininger 
Thank you so much for your reply, it works for now!

**Comment by alexweininger** [comment]
@TE-KyokuYO I have a development build ready to be tested, can you try it out and report if it works for you? Make sure to reopen any blob containers using the "Open in Explorer" command. Simply opening a recent blob container from the Quick Open or Recents menus will not work.

https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=62672&view=artifacts&pathAsName=false&type=publishedArtifacts

Steps to install extension development build:
1. Download the extension VSIX from the [Azure DevOps Pipeline Artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=62672&view=artifacts&pathAsName=false&type=publishedArtifacts) <img width="702" alt="image" src="https://github.com/microsoft/vscode-azurestorage/assets/12476526/5759c9d2-5fcd-4b7b-8e15-7134eeb9775e">

1. Extract the .zip archive and find the .VSIX file.
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the extracted .VSIX file, then reload VS Code as prompted.

**Comment by TE-KyokuYO** [comment]
@alexweininger 
I tried with the new build, it works properly, thank you so much for your help!
