### ISSUE TITLE
Unable to open blob file from a specific storage account

### ISSUE THREAD

**Issue by tagoad** [microsoft/vscode-azurestorage#1224]
This was working fine until a couple weeks ago and then the main account i interact with started throwing errors saying every time i went to open a file: Unable to resolve nonexistent file 'azurestorage:/integrations-mappings/BB_Infor_Shipment_Shopify_Fulfillment.j2

Other storage accounts in my subscription work just fine, and I am really the only one who uses the trouble account so as far as i know nothing has changed with it recently. I have tried uninstalling and reinstalling the extension with no change.

**Comment by stevenjh** [comment]
I'm experiencing the same issue, some blobs/files within the container will open just fine, issues seems to relate to files loaded after clicking `Load More...` full error below. Aside from not working, saving files seems to have got excruciatingly slow!

```
cannot open azurestorage:/ABC/XYZ.json?resourceId%3D%2Fsubscriptions%2Fxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx%2FresourceGroups%2FZZZZZ%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2FXXXXX%2FBlob%20Containers%2FABC Detail: Unable to read file 'azurestorage:/ABC/XYZ.json?resourceId=/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/ZZZZZ/providers/Microsoft.Storage/storageAccounts/XXXX/Blob Containers/ABC' (Error: Unable to resolve nonexistent file 'azurestorage:/ABC/XYZ.json?resourceId=/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/ZZZZZZZZ/providers/Microsoft.Storage/storageAccounts/XXXX/Blob Containers/ABC')
```

Thanks!

**Comment by stevenjh** [comment]
Attempting to view the container in VS Code via the  `Open in Explorer...` results in a different presentation of an error.
The full container filelist is loaded, as above, recent files work, older files present the error below.
![image](https://user-images.githubusercontent.com/1258872/225170069-6e0fda4c-bc92-425e-8b91-2e16ff3399a5.png)

**Comment by alexweininger** [comment]
> Attempting to view the container in VS Code via the `Open in Explorer...` results in a different presentation of an error. The full container filelist is loaded, as above, recent files work, older files present the error below. ![image](https://user-images.githubusercontent.com/1258872/225170069-6e0fda4c-bc92-425e-8b91-2e16ff3399a5.png)

@stevenjh I think I understand the issues you mention in your first comment. However, could you provide detailed steps on how to reproduce the issue you encountered directly above?

**Comment by stevenjh** [comment]
@alexweininger sure thing!

1. Open VS Code
2. navigate to the storage container, click Open in Explorer...
3. ![image](https://user-images.githubusercontent.com/1258872/225178882-bc32753f-d8f9-402d-b30c-96aac829bc4a.png)
4. ![image](https://user-images.githubusercontent.com/1258872/225178949-93e8a4df-32da-4cfd-ae19-38c2c02a04da.png)
5. VS Code will reload with the container opened in the EXPLORER section
6. click on a 'broken file' (seems to be older files), receive the error above.

ps. just want to reiterate that it seems much slower than it used to be.

Thanks!

**Comment by alexweininger** [comment]
Thanks for the detailed steps. These issues are probably related to #1222. 

You can revert to the previous version of the Storage and Resources extensions to fix these issues. [How to do that](https://github.com/microsoft/vscode-azurestorage/issues/1222#issuecomment-1451244361)

Unfortunately our latest release caused regressions related to opening blobs/file shares in VS Code.

**Comment by stevenjh** [comment]
Thanks for monitoring the issue and steps to revert, this has things back up and running and resolves the performance issues I was referring too. Cheers!

**Comment by tagoad** [comment]
> 

So rolling the storage extension back should fix my issue for the time being as well?

**Comment by alexweininger** [comment]
Since this issue is very similar to #1222 and has the same workaround I will close as a duplicate. Please follow #1222 for updates.
