### ISSUE TITLE
Fail to open a file which is uploaded using the generated path on Windows

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#126]
Repro Steps:
1. Generate a file path and copy it to clipboard.
2. Right click one blob container and select 'Upload block blob...'.
3. Paste the generated path to the Text Box, then press Enter.
4. Check whether the uploaded file can be opened or not.

Expect:
Succeed to open the uploaded file.

Actual:
Fail to open the uploaded file with error.
![compare](https://user-images.githubusercontent.com/34729092/39239338-0c6b3998-4870-11e8-833c-5935e4d9f0fc.PNG)

**Comment by StephenWeatherford** [comment]
Repro...

**Comment by PrashanthCorp** [comment]
Closing pending customer feedback.
