### ISSUE TITLE
Fail to upload a file/folder to file share with an error

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1262]
**OS:** Win10
**Build Version**: 20230801.1
**Regression:** Previous Release

**Repro Steps:**

1. Upload a file/folder to file share.
2. Check the result.

**Expect:**
Succeed to upload a file/folder to the file share.

**Actual:**
Fail to upload a file/folder to file share.
![image](https://github.com/microsoft/vscode-azurestorage/assets/107091828/7686e402-1366-4818-af8e-83a13a758b82)

**More Info:**
1. This issue also reproduces when uploading a file/folder to blob container.
2. This issue also reproduces when executing "Download…” command for blob container and file share.
3. This issue also reproduces when executing "Download by SAS Url…” command for blob container and file share.

**Comment by v-xinda** [comment]
Verified on 0.15.4-alpha.0 version, this issue **still reproduces on Mac and Linux p**latforms. Get the error from below:
Mac:
<img width="451" alt="Screenshot 2024-06-05 at 09 51 52" src="https://github.com/microsoft/vscode-azurestorage/assets/57662131/ca5cb08e-18fb-4eb2-a37f-c93fe10d5840">
Linux:
![image](https://github.com/microsoft/vscode-azurestorage/assets/57662131/4a647a45-cc74-4ffb-9e40-7565b994ae97)

**On Windows platform,** This issue only reproduces when uploading a file to the file share.
![image](https://github.com/microsoft/vscode-azurestorage/assets/57662131/49b2731d-2b8a-4404-b7e0-bd3b156c1092)

**Comment by alexweininger** [comment]
We are still working on fixing this. The current behavior is that it fails to upload only for file shares on all platforms.
