### ISSUE TITLE
[Suggestion]Layered display of files and folders for blob containers

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#127]
Repro Steps:
1. Open a blob container which including a file and a folder at least.
2. Check the displayed mode.

Suggestion:
Layered display of files and folders.
![layer](https://user-images.githubusercontent.com/34729092/39239641-013e3cc2-4871-11e8-8250-1c6946ee6cb5.png)

**Comment by StephenWeatherford** [comment]
That's the current design.  No, it's not as nice as in the Storage Explorer.
