### ISSUE TITLE
Pop up an extra dialog after executing "Open in Storage Explorer" for a blob container

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1273]
**OS:** Win10
**Build Version:** 20230904.1
**Regression:** Not a Regression

**Repro Steps:**

1. Create a storage account -> Create a blob container.
2. Right click the blob container -> Click "Open in Storage Explorer".
3. Check whether the blob container is opened in the Storage Explorer.

**Expect:**
The blob container is opened in the Storage Explorer.

**Actual:**
Pop up an extra dialog.
![image](https://github.com/microsoft/vscode-azurestorage/assets/57662131/9b5777ab-2cdf-46e4-ab16-3b72424dc942)

**More Info**
The selected blob container can be opened in the Storage Explorer after clicking "Navigate to Container".

**Comment by nturinski** [comment]
This is actually a new feature from the storage explorer team, so I'll close this as by-designed.
