### ISSUE TITLE
Only show "AZURE" for the "AZURE: ACTIVITY LOG" window in the Visual Studio Code Insiders

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1287]
**OS:** Win10
**Build Version:** 0.15.3
**Visual Studio Code Version:** 1.84.0-insider (user setup)

**Repro Steps:**

1. Install "Azure Storage" extension from Extensions.
2. Navigate to Azure view -> Open a new Terminal -> Click "AZURE" window.
3. Check whether shows "AZURE: ACTIVITY LOG".

**Expect:**
Show "AZURE: ACTIVITY LOG".
![image](https://github.com/microsoft/vscode-azurestorage/assets/57662131/70c28e0f-eaef-4d75-baa1-03bbc6289989)

**Actual:**
Show "AZURE".
![image](https://github.com/microsoft/vscode-azurestorage/assets/57662131/ee5c9f42-9f5a-41fe-882b-5274168abde0)

**More Info:**
1. This issue doesn't reproduce for the Visual Studio Code 1.83.1 (user setup).
2. This issue is logged for the vscode https://github.com/microsoft/vscode/issues/195957

**Comment by nturinski** [comment]
This is an upstream issue, but I think it's fine for it to only display Azure as that is the name of the panel.
