### ISSUE TITLE
Extension Fails to Install (endless spinner)

### ISSUE THREAD

**Issue by RA-Davies** [microsoft/vscode-azurestorage#1296]
Hi,

This can't be installed from the Extension store for me - it just sits there spinning indefinitely, once I've restarted VS Code it treats it like it's not installed.

Tried restarting VS Code, tried rebooting, I've enough space on disk, any ideas?

Kind regards,

Roger Davies

**Comment by RA-Davies** [comment]
Sorry to double-post, in case it helps show why your exstension installation fails, below are the logs:

024-02-27 11:08:44.939 [error] EPERM: operation not permitted, rename 'c:\Users\[username]\AppData\Roaming\Code\CachedExtensionVSIXs\.3453999f-eb9b-423e-b014-a158df0ed607' -> 'c:\Users\[username]\AppData\Roaming\Code\CachedExtensionVSIXs\ms-azuretools.vscode-azurestorage-0.15.3': Download: EPERM: operation not permitted, rename 'c:\Users\[username]\AppData\Roaming\Code\CachedExtensionVSIXs\.3453999f-eb9b-423e-b014-a158df0ed607' -> 'c:\Users\[username]\AppData\Roaming\Code\CachedExtensionVSIXs\ms-azuretools.vscode-azurestorage-0.15.3'#

May be worth testing this further I think

**Comment by nturinski** [comment]
Hi @RA-Davies,

Are you able to install any other extensions? It seems like VS Code doesn't have permissions to access your app data cache. I don't think that this should be specific to our extension, but please let me know if it is.
