### ISSUE TITLE
Cancel 'Upload to Azure' on blob save shows an error

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#13]
Repro steps:
1. Open a blob
1. Edit blob
1. Save
1. Click 'close' to cancel updating this to azure

Expected: No error
Actual:
![screen shot 2017-12-06 at 2 47 09 pm](https://user-images.githubusercontent.com/11282622/33689500-8f552c1e-da94-11e7-8688-694bcfd2fd66.png)

**Comment by JakeRadMSFT** [comment]
Resolved
