### ISSUE TITLE
No azure button

### ISSUE THREAD

**Issue by ollenna** [microsoft/vscode-azurestorage#1301]
Type: <b>Bug</b>

1 install azure storage
2 no way to access it - not on the side panel not by right clicking it

Extension version: 0.15.3
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (1.54GB free)|
|Process Argv|. --crash-reporter-id 2efec6ba-c753-455f-8bd7-6c5f445abc52|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nturinski** [comment]
Could you share a screenshot of what it looks like?

Sometimes if the view gets hidden, you can try running this command:
![image](https://github.com/microsoft/vscode-azurestorage/assets/5290572/1afd052b-d0dd-4b91-8e93-1c7266221606)
