### ISSUE TITLE
Cannot Browse to Website

### ISSUE THREAD

**Issue by Tom-H2oThermo** [microsoft/vscode-azurestorage#1303]
I followed the instructions on https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage.  After deployment, in VS Code, when I click on the Browse to Website, I get this error:
![image](https://github.com/microsoft/vscode-azurestorage/assets/25697066/5df0b8e2-759f-48f9-9dcf-2b7eafcafcaa)
I copied the primary web endpoint that was provide after deployment.  When I try to open that link I get:
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:5a237046-901e-0055-802a-8d959d000000 Time:2024-04-12T22:42:47.3470869Z</Message>
</Error>

Any advice would be appreciated.

**Comment by motm32** [comment]
Thanks for filing this issue! Could you provide some more information? What exactly were you deploying? 

Here is some further documentation that could also help: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website

**Comment by Tom-H2oThermo** [comment]
Sorry, I should have closed this out.  I figured it out.  It was quite easy once I got the hang of it.  I think this can be closed out.
