### ISSUE TITLE
An error occurs when creating/deleting several storage accounts at the same time

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#1314]
**OS:** Mac/Linux
**Build Version:** v0.15.4-alpha.0

**Repro Steps:**
1. Create several storage accounts at the same time, such as create 3 storage account at the same time.
2. Check whether no error occurs when creating several storage accounts at the same time.

**Expect:**
No error occurs when creating several storage accounts at the same time.

**Actual:**
An error occurs when creating several storage accounts at the same time.
![image](https://github.com/microsoft/vscode-azurestorage/assets/45614674/8008e32c-3a9b-40a4-a94b-4652a8548f34)

**More Info:**
1. Another error occurs when deleting several storage accounts at the same time.
![image](https://github.com/microsoft/vscode-azurestorage/assets/45614674/5a2f9aac-baae-4652-8c1f-af3a47268490)
2. We are not sure if this issue related to the network speed.

**Comment by alexweininger** [comment]
Certainly caused by #1310 😢
