### ISSUE TITLE
Cannot access Azure storage account, showing "Error type: ResourceCollectionRequestsThrottled"

### ISSUE THREAD

**Issue by TimL93** [microsoft/vscode-azurestorage#1329]
Does this occur consistently? 
Repro steps:

1. We have been using Visual Studio Code to access Azure storage account for getting some database log. Since last Friday, it has not worked anymore and the icon of the storage account just shows the sign of "loading". When I accessed the same storage account via web portal on Azure, it shows that "The server rejected the request because too many requests have been received."

Action: resolveResource
Error type: ResourceCollectionRequestsThrottled
Error Message: Operation 'Microsoft.Storage/storageAccounts/read' failed as server encountered too many requests. Please try after '239' seconds. Tracking Id is 'redacted:id'.

Version: 0.16.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.92.2
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:512581
deserializeResponseBody extension.bundle.js:2:513308
```

</details>

**Comment by nturinski** [comment]
Reopening until fix is confirmed and released.

**Comment by nturinski** [comment]
If you could help us test that our fix actually worked, please follow these steps:
1. Download the zip file artifact from here: https://github.com/microsoft/vscode-azurestorage/actions/runs/10516388603/artifacts/1844647031
2. Extract the `.vsix` file from the zip file
3. In VS Code, hit F1 > `Extensions: Install from VSIX`
4. Navigate to `vscode-azurestorage.vsix`
5. Install and reload VS Code

If this resolves your issue, please let us know. It would help us greatly!

**Comment by nturinski** [comment]
We released this fix. Please let us know if you're still encountering this error.
