### ISSUE TITLE
Support 'Download' for files/directories

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#139]
Repro Steps:
1. Open one file share and create a new file.
2. Right click the file and check the context menu.

Expect:
Support to download for the file.

Actual:
No 'Download' action displays on the context menu.

**Comment by StephenWeatherford** [comment]
We currently only support downloading blobs.

**Comment by PrashanthCorp** [comment]
Closing pending further customer feedback.
