### ISSUE TITLE
[Linux]'Copy Connection String' doesn't work

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#141]
Repro Steps:
1. Right click one storage account and select 'Copy Connection String'.
2. Paste the connection string to notepad or Storage Explorer.

Expect:
The connection string of the account can pasted successfully.

Actual:
The connection string of the account isn't pasted. 

More info:
'Copy Primary Key' also doesn't work.

**Comment by PrashanthCorp** [comment]
For the repro, has xclip been installed?

**Comment by EricJizbaMSFT** [comment]
That doesn't matter. You can use clipboardy like in the [functions extension](https://github.com/Microsoft/vscode-azurefunctions/blob/34e03574739cd19ce3ade422d560b97cfd4d96bf/src/commands/copyFunctionUrl.ts#L17), which will work without xclip
