### ISSUE TITLE
'Refresh' doesn't work well in the context menu for Blob Containers.

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azurestorage#144]
Repro Steps:

1. Expand storage account. 
2. Right click Blob Containers node and select 'Refresh'.
3. Verify whether this action can work well or not.

Expect:
'Refresh' works well with refreshing icon.

Actual:
it doesn't work well.

More Info:
It also reproduces for File Shares/Queues/Tables node.

**Comment by v-haiz** [comment]
Hi, Stephen,
This is what I want to express: I test time after time, 'Refresh' is really executed successfully when right clicking the Blob Containers/File Shares/Queues/Tables, but I can't see any indication, such as refreshing icon.

Please see the difference between supplied subscription and Blob Containers node through the link below:
\\trinlab2\BAQAFiles\CloudToolsTest\v-haiz\video\compare.mp4

Thanks.

**Comment by StephenWeatherford** [comment]
Moved to https://github.com/Microsoft/vscode-azuretools/issues/181
