### ISSUE TITLE
No conflict pops up after creating an empty text file with an existing name

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#148]
Repro Steps:

1. Right click one file share node and select 'Create Empty Text File' item.
2. Repeat Step1 with the same name for the same file share.

Expect:
Pop up an error prompting that a file share with this name already exists.

Actual:
No conflict pops up.

More Info:
This issue doesn't reproduce for blob containers.

**Comment by PrashanthCorp** [comment]
We need to repro with an additional answer : does this overwrite existing data?

**Comment by PrashanthCorp** [comment]
We need to repro with an additional answer : does this overwrite existing data?
