### ISSUE TITLE
Error expanding blobs-only storage account

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurestorage#15]
Cannot match against 'undefined' or 'null'.

![image](https://user-images.githubusercontent.com/6913354/33747988-e96f6796-db7a-11e7-9515-082fe7825077.png)
![image](https://user-images.githubusercontent.com/6913354/33747980-d9cd5992-db7a-11e7-9b05-79fdce5c50a7.png)

**Comment by JakeRadMSFT** [comment]
@StephenWeatherford does this still reproduce for you?

**Comment by StephenWeatherford** [comment]
Currently get "The requested operation is not implemented on the specified resource.
RequestId:71993b56-9002-0108-7c4b-c16609000000
Time:2018-03-21T19:30:12.6701937Z"
