### ISSUE TITLE
Replace the red X icon with a warning icon in the bottom dialog when opening a page blob

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#150]
Repro Steps:
1. Expand Storage Accounts and try to open a page blob.
2. Check the cue icon in the bottom dialog.

Expect:
It displays as a warning dialog.
![expect](https://user-images.githubusercontent.com/34729022/40605973-7536634c-6253-11e8-9de6-ca74e7f33a76.png)

Actual:
It displays as a red X icon.
![icon](https://user-images.githubusercontent.com/34729022/40605985-7ac9e40a-6253-11e8-9ede-93dc88b09460.png)

**Comment by StephenWeatherford** [comment]
It is an error (not supported).
