### ISSUE TITLE
Opening a blob displays a temporary tab when the same blob has been permanently opened

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurestorage#151]
Repro Steps:
1. Expand Storage Accounts and open one blob file.
2. Right click the opened tab and select 'Keep Open'.
3. Open the same blob file again.

Expect:
It doesn't open a temporary tab.

Actual:
It opens a temporary tab.
![tab](https://user-images.githubusercontent.com/34729022/40607207-56c9268e-6257-11e8-8870-0ed56f9ae364.png)

More info:
This issue also reproduces for file share.

**Comment by v-dantch** [comment]
Verified on the latest build [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=results), it opens a **permanently** tab now when opening a blob/file.
![image](https://user-images.githubusercontent.com/34729092/74220123-b4a49f80-4ce9-11ea-9cd6-72f5aff4ef05.png)
And there won't be any extra tabs when opening the same blob/file again from Azure Storage view.

**Comment by wwlorey** [comment]
That behavior is intended, closing for now
