### ISSUE TITLE
Enable static site hosting from extension

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurestorage#153]
It seems like we'll end up shipping this in two parts, 1) supporting deployments and 2) supporting enabling and configuring storage accounts for web hosting.

As part of this first step, it would be helpful to be able to launch into the portal directly to a storage account to simplify the process for enabling web hosting.

Related to #146

**Comment by fiveisprime** [comment]
URL format seems to elude to being able to deep link.

/resource/subscriptions/:id/resourcegroups/:group/providers/Microsoft.Storage/storageAccounts/:name/staticWebsite

**Comment by StephenWeatherford** [comment]
Right now we're sending them to the portal, can allow enabling ourselves when we get SDK support.

**Comment by PrashanthCorp** [comment]
The above PR should close this issue since deployment has been implemented [here](https://github.com/Microsoft/vscode-azurestorage/commit/4e729dfd304e2485a4e0a84d6c65ee9dd1330086). @fiveisprime  let me know if there's more to the issue you'd like aside from the PR. :)

**Comment by PrashanthCorp** [comment]
Closing via PR.
