### ISSUE TITLE
'OK' button doesn't work when selecting subscriptions

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#157]
Repro Steps:
1. Launch VS Code and sign in with your account.
2. Click 'Select Subscriptions...' -> Then change the current applied subscriptions -> Click OK.

Expect:
OK button works well.

Actual:
OK button doesn't work.

More info:
This issue doesn't reproduce on Windows.

**Comment by fiveisprime** [comment]
Is this on latest VS Code (1.24.0)?

**Comment by v-xuanzh** [comment]
This issue still reprodcues on latest VS Code1.25.0
![version](https://user-images.githubusercontent.com/34729022/41215406-a9c92fe4-6d3f-11e8-8b69-57c23e423817.png)

**Comment by StephenWeatherford** [comment]
Works fine for me on Mac 1.25.0-insider.  Or is this Linux?  Can you be more specific about the exact repro steps and indicate exactly what it's doing that's wrong?  Thx.

**Comment by v-xuanzh** [comment]
Hi Stephen, it seems that this issue doesn't reproduce on Mac 1.25.0-insider and Linux. Could you help to close it and add 'Not repro' label?

**Comment by StephenWeatherford** [comment]
Done, thanks.
