### ISSUE TITLE
Does not display classic storage accounts

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurestorage#17]
Storage accounts that were created with the "Classic" option do not appear in the tree

![image](https://user-images.githubusercontent.com/6913354/33748226-2250a6aa-db7c-11e7-9f97-250b804e363c.png)

**Comment by JakeRadMSFT** [comment]
By design for now and it's in release notes/known issues.

**Comment by StephenWeatherford** [comment]
No current plans to implement.
