### ISSUE TITLE
Deploying Static Websites while logging in - Subscriptions not selected

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azurestorage#170]
![image](https://user-images.githubusercontent.com/30420973/41568583-3eaaa148-731b-11e8-868f-976a9adccf80.png)

I signed out, then signed in. Then tried to deploy a static website, and I hit the above prompt which is not very actionable.

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Most likely https://github.com/Microsoft/vscode-azuretools/issues/186, please retry with current version.
