### ISSUE TITLE
Primary endpoint not available from the extension post-deploy

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azurestorage#171]
The Primary endpoint is only available at the point of deploying a static website. It is not available outside the prompt (command palette, etc). For a first time user whose work flow is not set, this can lead to requiring a re-deploy (I cancelled the prompt and went searching around the extension for this endpoint, and resorted to re-deploying the website).

**Comment by StephenWeatherford** [comment]
You can currently get to it from "Configure Endpoint...", but when we get SDK support there will be a menu item for it.

**Comment by PrashanthCorp** [comment]
I don't see a "Configure Endpoint..." option anywhere. I can see we have code to fetch the primary endpoint:  https://github.com/Microsoft/vscode-azurestorage/blob/1df7685fa95cd0b1e3999dc326f9eb6d6ca561be/src/azureStorageExplorer/blobContainers/blobContainerNode.ts#L346

Should a fix for this just be a context menu item on `$web` that uses `getPrimaryWebEndpoint` ?

**Comment by StephenWeatherford** [comment]
azureStorage.configureStaticWebsite

Right now all it does is take you to the portal.  saw/configure changes that.

**Comment by PrashanthCorp** [comment]
I'm closing this. It looks like `Browse to Static Website` handles what I expected from this bug.
