### ISSUE TITLE
Difference between primary endpoint and URL unclear

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azurestorage#172]
There are options for two of them. Copy URL is a context menu item, always available . 

It is also not so clear what the URL does/helps. Following the link leads to a resource not found errer: 
![image](https://user-images.githubusercontent.com/30420973/41568718-27aa1798-731c-11e8-8365-091a54a2ff23.png)

**Comment by StephenWeatherford** [comment]
This will be clearer when we get SDK support.
