### ISSUE TITLE
Deploy action from sash can lead to the wrong folder being deployed

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-azurestorage#173]
My current workspace is a webapp project. I wish to deploy a specific folder (say, the out folder)
I used the deploy button from the sash. Since the default option on the prompt is my workspace. Clicking on it would deploy the whole project, rather than list sub-folders. 
![staticwebsitedeploy](https://user-images.githubusercontent.com/30420973/41568927-7c0fb27e-731d-11e8-81e8-d86647e62ca1.png)

**Comment by StephenWeatherford** [comment]
@PrashanthCorp What exactly are you suggesting?  Not sure I understand the problem.  The whole project/workspace might be what they want to deploy.

**Comment by fiveisprime** [comment]
We talked about adding `dist`, `out`, or `build` if present in the workspace. That should help here.

So if you are building to `dist`, the options in the sash will be `browse`, `${workspace}`, and `${workspace}/dist`.
