### ISSUE TITLE
Deploying to Static Website doesn't display the notification after disabling static website in portal

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#174]
Repro Steps:
1. Create one GPV2 account in portal.
2. Back to VS Code and set the "azureStorage.preview.staticWebsites" as true in User Settings.
3. Right click the created v2 account -> Select 'Deploy to Static Website...' -> Check the notification 'Website hosting is not enabled...' displays in bottom-right. -> Click 'Yes' then enable the static website in portal.
4. Deploy the account.
5. Right click the same account -> Click 'Configure Static Website' -> Disable the static website in portal.
6. Repeat Step4 and check whether the notification pops up or not.

Expect:
The notification 'Website hosting is not enabled...' displays in bottom-right.
![notification](https://user-images.githubusercontent.com/34729022/41590812-7dd067b8-73a7-11e8-8b91-26b51bc66eb1.png)

Actual:
No notification displays and it can be deployed successfully.

**Comment by StephenWeatherford** [comment]
Unfortunately we currently don't have SDK support to detect if it is actually enabled - all I can do is search for the $web container, which still exists if you disable it.  When we get the support I'll implement this properly.
