### ISSUE TITLE
Remove ellipsis from and group deployment context menu

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurestorage#181]
Drop the ellipsis to match the other extensions and group them together.

![image](https://user-images.githubusercontent.com/1186948/41880506-4278230e-7893-11e8-9923-d4d23d268db1.png)

**Comment by StephenWeatherford** [comment]
@fiveisprime @EricJizbaMSFT @nturinski I think it's the other way around.  I think the other "Deploy" menu items should have the ellipses as well.  See https://vsuiguide.azurewebsites.net/topics/14%20Evaluation%20Tools/14.01%20Craftsmanship%20checklist.html:

> Verify that buttons, commands, and command links that launch UI to capture user input, end in an ellipsis […]. Examples: 
> An [Advanced…] button on a dialog.
> The command options under the Tools menu Tools > Options should not get an ellipsis, because 
> launching the dialog itself is the intent of the command.

We require user input to determine whether to deploy to.

**Comment by fiveisprime** [comment]
I just want them to be the same. Add it to the others or remove it here.

**Comment by EricJizbaMSFT** [comment]
I agree it should have an ellipses
