### ISSUE TITLE
Add user agent

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurestorage#185]
https://github.com/Microsoft/vscode-azuretools/issues/200

**Comment by PrashanthCorp** [comment]
Need to verify that it's fully implemented.

**Comment by PrashanthCorp** [comment]
Currently among the clients we can create, we only create a StorageManagementClient. I verified that we use `createAzureClient<T>` whenever we create a client of type T. This directly adds the extension user agent. This is similar to how other extensions do it. 

Closing this. 

Question: This feels like a probable issue every time there's new code using an azure client. If the author forgets to wrap it in a `createAzureClient` call, we would not have the user agent info.
