### ISSUE TITLE
Creating a new text file defaults to text/plain content type

### ISSUE THREAD

**Issue by lenardg** [microsoft/vscode-azurestorage#186]
When using the 'Create Empty Text Blob' feature it will add a Content-Type header to the blob. See picture:

![image](https://user-images.githubusercontent.com/5020576/42084109-76443b32-7b95-11e8-8240-b04d33012a68.png)

Even if I rename it to be HTML, it will still be text/plain for the browser, preventing usage in the new static web site hosting feature of Azure Storage.

I would recommend either

- Sniffing the file type and setting an appropriate content type header
- Allowing to change the content type after upload

Currently it is too easy to break the static web hosting by uploading files that default to text/plain. The error is not immediately obvious.

**Comment by StephenWeatherford** [comment]
That's why the menu item is named "Create Empty Text Blob". But we've extended beyond our original goals, and we should reconsider this decision.

**Comment by EricJizbaMSFT** [comment]
@wwlorey I was looking into 🕵🏻‍♂️ [this comment](https://github.com/microsoft/vscode-azurestorage/pull/499#discussion_r343959949) and seems like you slipped in part of this feature at some point 😛. The titles in package.json are still "Create Empty Text File..." and "Create Empty Text Blob..." which implies it _should_ be text, but it's not based on your changes. We should make it consistent
