### ISSUE TITLE
Provide a visual indicator for remote files

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestorage#188]
I'm not sure what the options are for this, but some kind of visual indicator in the tab showing that the file is remote would be helpful.

I believe we talked about this before and it wasn't an issue. Now that we're supporting deployment of apps, we should reconsider.

**Comment by nturinski** [comment]
@wwlorey Discuss with @fiveisprime about potential solutions

**Comment by wwlorey** [comment]
After talking with Matt, this is no longer necessary
