### ISSUE TITLE
Hash mismatch error clicking on a binary blob

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurestorage#19]
Try clicking on a binary blob (e.g. a PNG), and I get this:

Opening '106-5428.bmp' ... Failed.
Error Details: Hash mismatch (integrity check failed), Expected value is zcv7JnXe0kve8NUS4aUCtw==, retrieved PsRNDm383kGjriJSE6jdiw==.

Not what the expected behavior is, but I'm sure it's not this.  :-)

**Comment by StephenWeatherford** [comment]
Probably related to #21

**Comment by JakeRadMSFT** [comment]
Resolved in V0.1.3

**Comment by StephenWeatherford** [comment]
@JakeRadMSFT Works great, thanks.
