### ISSUE TITLE
Doesn't display the corresponding error message for the tooltip when creating an existing blob

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurestorage#190]
Repro Steps:
1. Go to subscription -> Storage Accounts.
2. Choose one blob container then create an existing blob.
3. Focus on the red border then check the error message of the tooltip.

Expect:
It displays the corresponding error message 'A blob with the same name already exists'.

Actual:
It dispalys 'Enter a name for the new block blob'.
![inconsistent_message](https://user-images.githubusercontent.com/34729022/42156210-f8063224-7dd9-11e8-8f83-c4320b26c28e.png)

**Comment by wwlorey** [comment]
That tooltip is determined by the `placeHolder` option which doesn't change when an input error happens.

I verified that VoiceOver speaks the error out loud despite the tooltip not updating.

**Comment by nturinski** [comment]
This seems to be a VS Code bug so I'll close this as external.
