### ISSUE TITLE
The deleted blob isn't auto added back to tree view after updating it in editor successfully

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#196]
Repro Steps:
1.Right click one 'Blob Container' and select 'Create Blob Container'.
2.Right click the blob container and select 'Create Empty Text Blob' named 'testblob'.
3.Open the text blob, then delete the 'testblob'.
4.Edit the test blob in the opened blob editor, then update it.
5. Check whether the blob is auto added back in the tree view or not.

Expect:
The text blob is auto added back and displays in the tree view.

Actual:
The blob doesn't auto display in the tree view without refreshing.

**Comment by nturinski** [comment]
This is a very edge case.
