### ISSUE TITLE
Fail to open the second service in Storage Explorer

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#197]
Repro steps:
1. Make sure Storage Explorer is installed.
2. Expand one storage account -> Right click one blob container and select 'Open in Storage Explorer'.
3. Check the blob container can be opened in Storage Explorer successfully.
4. Right click another blob container -> Select 'Open in Storage Explorer'.
5. Check whether it can be opened in Storage Explorer successfully or not.

Expect:
The second opened blob container can be opened successfully in Storage Explorer.

Actual:
Fail to open the second blob container in Storage Explorer.

**Comment by v-xianya** [comment]
This issue doesn't reproduce, So close it.
