### ISSUE TITLE
Show only V2 storage accounts for quick pick when deploying static website

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurestorage#201]

**Comment by PrashanthCorp** [comment]
Closing via #275. The only accounts shown are those capable of hosting Static websites. 
The check is done here: 

https://github.com/Microsoft/vscode-azurestorage/blob/63565f960505aca2af3fe2704d9e058ff4d78ce6/src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts#L47
