### ISSUE TITLE
The blob size is not auto updated in Storage Explorer when it has opened 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#207]
Repro Steps:
1. Create a new blob container and new empty text file.
2. Right click the blob container and select 'Open in Storage Explorer'.
3. Make changes for this new text file in VS Code.
4. Repeat Step2.
5. Check whether the blob size is auto updated in Storage Explorer or not.

Expect:
The blob size is auto updated in Storage Explorer.

Actual:
The blob size is not auto updated in Storage Explorer. The content is updated when opening it from Storage Explorer.
![not-updated](https://user-images.githubusercontent.com/34729092/43393516-01491a4a-93e7-11e8-800e-823be69c35ef.png)

**Comment by StephenWeatherford** [comment]
I think it's reasonable for users to need to click Refresh to see data modified from another application.  Thanks, but won't fix.
