### ISSUE TITLE
fail deploy to static web site

### ISSUE THREAD

**Issue by jcyamacho** [Microsoft/vscode-azurestorage#215]
Repro steps:
<Enter steps to reproduce issue>

Action: azureStorage.createBlobContainer
Error type: AuthenticationFailed
Error Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0f68c108-601e-0098-4dc6-2d49fc000000
Time:2018-08-06T20:49:15.4072258Z

Version: 0.4.1
OS: win32

**Comment by StephenWeatherford** [comment]
@jcyamacho Sorry for the delayed response. Do you still get this? Do you know how to reproduce it?  Thx.
