### ISSUE TITLE
Implement pre-publish action for Static Websites

### ISSUE THREAD

**Issue by gabrielvdk** [Microsoft/vscode-azurestorage#216]
Would be great if you can do some pre-processing before the files go to Azure.

Eg.
- Configure some settings based on target storage account
- Increase a build number / date-time
- etc.

**Comment by StephenWeatherford** [comment]
@fiveisprime Do we do something like this for publishing in any of the other extensions?

**Comment by fiveisprime** [comment]
We don't; however it makes sense to be able to configure some kind of pre-publish build for SPAs. Maybe we could hook into VS Code's build system to trigger the command that you could customie how you see fit?

**Comment by EricJizbaMSFT** [comment]
In Functions, we run `dotnet publish` before deploying a C# project. VS Code has a tasks api that you can leverage to list and execute tasks from an extension. See here for more info: https://github.com/Microsoft/vscode-azurefunctions/blob/master/src/commands/deploy.ts#L201

I'm not sure what the user experience would be in the storage extension, but I'm guessing you could leverage the same tasks api

**Comment by StephenWeatherford** [comment]
I like that idea.  prepublishStaticWebsite?
