### ISSUE TITLE
Unable to sign in with code-insiders

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/vscode-azurestorage#218]
Issue Type: <b>Bug</b>

When entering the code in aka.ms/devicelogin, I get authenticated on the browser and the "Waiting for Azure sign-in..." dissapears as expected, but instead of getting the list of storage accounts I have access to, I get back the "Sign in to Azure..." and "Create a Free Azure Account..." options.

Extension version: 0.4.1
VS Code version: Code - Insiders 1.27.0-insider (8727085fff33bf7d8f5e27483b10f72508d4167a, 2018-08-14T07:42:59.172Z)
OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.93GB (2.56GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by StephenWeatherford** [comment]
@omartin2010 Is this consistent?  If you try again, or exit and restart vscode, do you see the subscriptions?  Thx.

**Comment by omartin2010** [comment]
I can repro from my end. Happy to share screen if you want to see (I`m internal MSFT).

**Comment by StephenWeatherford** [comment]
Weird, haven't been able to repro.  I assume that it works if you restart vscode?

**Comment by omartin2010** [comment]
It doesn't work. I can't get it to work in this configuration, but that is on WSL. Not sure if that makes a difference or not but that's what I've been trying to get to run properly. Most other things work ok but not that one.

**Comment by omartin2010** [comment]
If I do that, I get “Not signed in, sign in first”…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by StephenWeatherford** [comment]
That makes it an [Azure Account Extension](https://github.com/microsoft/vscode-azure-account/issues) issue.  Can you enter an issue there, hopefully they can help you.  Thanks.
