### ISSUE TITLE
Error: server failed to authenticate

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode-azurestorage#219]
Issue Type: <b>Bug</b>

I wish I knew how to repro but I don't. Sometimes I get the error saying Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:.... Time: 2018-08-21T14...
![image](https://user-images.githubusercontent.com/11371870/44407927-45535280-a52d-11e8-92eb-240658bd7d81.png)

Extension version: 0.4.1
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.80GB free)|
|Process Argv|C:\Users\omartin\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by omartin2010** [comment]
BTW, I see this on every one of my storage accounts, and in 3 subscriptions I have access to (my view was filtered to 2 subs, I've added one more to see and I'm seeing the same). I only see the behavior with Files, Queues and Tables. Not with blob. And I only have to click to expand the File Shares, for example to see that message appear. No need to drill down, in fact, I'm no longer able to drill down. I didn't restart VSCode yet but I suspect that would help. If you want to see a repro, ping me internally.

**Comment by awyl** [comment]
I have the same issue.

**Comment by StephenWeatherford** [comment]
@awyl Does it repro for blobs or only for Files/Queues/Tables?

**Comment by awyl** [comment]
Files and Queues

**Comment by StephenWeatherford** [comment]
Just to verify... Some storage accounts only support blobs (like a Blob storage account).  Is it possible you're looking at one of these?  Do you see tables/queues/files in the portal for this account?  Thx.

**Comment by awyl** [comment]
I can browse the file shares for a while whenever I reload vscode, then this error occurs randomly.  It is not always, it just happen from time to time.  I cannot repo it consistently.

**Comment by nturinski** [comment]
We'll check telemetry to see if this is still occurring.

**Comment by nturinski** [comment]
Offline: Maybe we can do a retry loop on getting resources from Azure if we see this error message.
