### ISSUE TITLE
[Suggestion]Add solutions/links to prompt the customers to upgrade v1 storage account on the prompting error dialog

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#220]
Repro Steps:
1. Create a v1 storage account on portal.
2. Right click this new v1 account -> Select 'Configure Static Website...'.
3. Make sure there is an error dialog.

Actual:
Display "Only general purpose V2 storage accounts support static website hosting".

Suggestion:
Add solutions/links to prompt the customers to upgrade v1 storage account on the prompting error dialog.
![sugg](https://user-images.githubusercontent.com/34729092/44511355-bf5b1700-a6a6-11e8-8d10-aad2c3f845bf.png)

**Comment by StephenWeatherford** [comment]
Good idea, didn't know about that, thanks.

**Comment by nturinski** [comment]
v1 isn't really used that frequently these days
