### ISSUE TITLE
[Suggestion]Add more commands for Azure Storage extension

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#221]
Repro Steps:
1. F1 -> Type 'Storage'.
2. Check the listed commands.

Actual:
Only list 3 commands about 'Static Website'.

Suggestion:
Add more commands for Azure Storage extension.
![suggestion](https://user-images.githubusercontent.com/34729092/44510807-32fc2480-a6a5-11e8-8647-397f3b73edd1.png)

**Comment by StephenWeatherford** [comment]
We'd just need to add code to prompt the user for which node to use in these commands.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.

**Comment by nturinski** [comment]
The amount of commands @EricJizbaMSFT has added I think should cover most main line scenarios.  I don't think we need to add the rest of the commands to the command palette.
