### ISSUE TITLE
Azure problem

### ISSUE THREAD

**Issue by andersbor** [Microsoft/vscode-azurestorage#225]
Repro steps:
<Enter steps to reproduce issue>

Action: azureStorage.deployStaticWebsite
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{"statusCode":400,"request":{"rawResponse":false,"queryString":{},"url":"https://management.azure.com/subscriptions/edaa3574-d80b-4170-9ad2-f9b619fb3f91/providers/Microsoft.Storage/storageAccounts?api-version=2018-03-01-preview","method":"GET","headers":{"Content-Type":"application/json; charset=utf-8","x-ms-client-request-id":"48ffdf75-f638-42cc-9181-8a7b29217ad7","accept-language":"en-US","user-agent":"Node/v8.9.3 (x64-Windows_NT-10.0.17134) ms-rest/2.3.6 ms-rest-azure/2.5.7 azure-arm-storage/5.1.1-preview Azure-SDK-For-Node"},"body":null},"response":{"body":"{\"error\":{\"code\":\"DisallowedProvider\",\"message\":\"The operation is not permitted for namespace 'Microsoft.Storage'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web,SuccessBricks.ClearDB'.\"}}","headers":{"cache-control":"no-cache","pragma":"no-cache","content-type":"application/json; charset=utf-8","expires":"-1","x-ms-failure-cause":"gateway","x-ms-request-id":"b9f6d4c4-d776-4a44-9e87-0f0661eea6c5","x-ms-correlation-request-id":"b9f6d4c4-d776-4a44-9e87-0f0661eea6c5","x-ms-routing-request-id":"WESTEUROPE:20180829T110329Z:b9f6d4c4-d776-4a44-9e87-0f0661eea6c5","strict-transport-security":"max-age=31536000; includeSubDomains","x-content-type-options":"nosniff","date":"Wed, 29 Aug 2018 11:03:29 GMT","connection":"close","content-length":"361"},"statusCode":400},"code":"DisallowedProvider","body":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.Storage'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web,SuccessBricks.ClearDB'."}},"_listeners":null,"_isException":false,"_errorId":2}}

Version: 0.4.1
OS: win32

**Comment by StephenWeatherford** [comment]
Do you have any trouble viewing the storage account in the Azure treeview?

**Comment by andersbor** [comment]
The problem starts right after logging in to Azure (from Code).
I do not see the Azure treeview.

Version problems?


-          Anders

Fra: Stephen Weatherford (MSFT) <notifications@github.com>
Sendt: 29 August 2018 23:00
Til: Microsoft/vscode-azurestorage <vscode-azurestorage@noreply.github.com>
Cc: Anders Kristian Børjesson <AnBo@easj.dk>; Author <author@noreply.github.com>
Emne: Re: [Microsoft/vscode-azurestorage] Azure problem (#225)


Do you have any trouble viewing the storage account in the Azure treeview?

**Comment by StephenWeatherford** [comment]
@andersbor Sorry for the delayed response.  From the error message it looks like you don't have permissions for storage?

> The operation is not permitted for namespace 'Microsoft.Storage'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web,SuccessBricks.ClearDB'
