### ISSUE TITLE
Azure Storage. help! what does this mean???

### ISSUE THREAD

**Issue by JTBmoonie** [microsoft/vscode-azurestorage#226]
Repro steps:
<Enter steps to reproduce issue>

Action: azureStorage.deployStaticWebsite
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{},"_listeners":null,"_isException":false,"_errorId":31}}

Version: 0.4.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
We fixed the error parsing in this PR: https://github.com/Microsoft/vscode-azuretools/pull/240

I'll let @StephenWeatherford decide whether or not to close this issue based on that. I'm not sure if there's anything else we can do until we release that fix and the actual error is displayed

**Comment by StephenWeatherford** [comment]
So once we get that fix, we would see more information that is currently shown?

**Comment by EricJizbaMSFT** [comment]
Yes that is correct. `JSON.stringify` doesn't actually stringify everything on an object. I ran into at least one case where the error was in a field like `value._value.response.body`, which resulted in an error like this before my fix (where response wasn't stringified), but resulted in an actually helpful error after my fix.

**Comment by StephenWeatherford** [comment]
@JTBmoonie Do you have repro steps on how to get this error?  Thx.

**Comment by StephenWeatherford** [comment]
Same as #225?

**Comment by nturinski** [comment]
Closing due to lack of response.  Please reopen if you are still having issues.
