### ISSUE TITLE
The log info is not clear after uploading a blob to blob containers

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#228]
Repro Steps:
1. Drill down from one storage account -> Create a new blob container -> Right click the new blob container -> Select 'Upload Block Blob...'.
2. Check the log info after uploading successfully.

Expect:
The log info is clear.

Actual:
The log info is not clear and miss the forward slash between the blob container name and blob name.
![actual](https://user-images.githubusercontent.com/34729092/45350740-10727280-b5a4-11e8-93ed-60d5d4de97ff.PNG)

**Comment by EricJizbaMSFT** [comment]
Fixed in #274
