### ISSUE TITLE
No "Sign in to Azure" button

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#233]
From marketplace:

> I've installed the extension Azure Storage, but not able to log into my Azure account - in the Activity Bar.
> My actions (atep by step according to guide https://code.visualstudio.com/tutorials/static-website/getting-started): 
> click on the Azure logo, AZURE STORAGE is shown in explorer. But there is NO "Sign in to Azure" button at all.
> There are 2 buttons: "deploy to static website" and "Refresh".

Needs further investigation. I think the main question is - did the extension fail to activate or was it just slow to activate? Did the user have the azure account extension installed?

**Comment by StephenWeatherford** [comment]
@Pavlo Kyrylenko The "command not found" issue only happens before the extension is fully activated by vscode or fails to activate (still, it shouldn't happen and we will have a fix soon).

As for the issue of no sign-in button, likewise these won't appear until vscode has finished activating the extension.  Normally this is quick but on older machines I've seen it a minute or so (I've filed https://github.com/Microsoft/vscode/issues/59645 against vscode to improve this experience).

So the question then is, if you open the view for the storage explorer and then wait a few minutes, do the buttons appear?  If an error is occurring activating the extension, there should be an error message from vscode.

Thanks!
Stephen

**Comment by StephenWeatherford** [comment]
@kyrylenko Pavlo, would appreciate more info so we can track down issue, thanks.

**Comment by PrashanthCorp** [comment]
Hi @kyrylenko, 
Thanks for filing the issue. There's a new version (0.8.0) of the azure account extension. Please let us know if the issue still reproduces. That release also has speed improvements. 

Feel free to re-open with additional detail if you still see the issue.
