### ISSUE TITLE
[Suggestion]Add a button to view the log message in output after creating a file share with existing name

### ISSUE THREAD

**Issue by v-haiz** [microsoft/vscode-azurestorage#240]
**Version**: 0.4.2
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra

**Repro Steps**:
1. Create one file share with existing name.
2. Check the content of the popped error dialog. 

**Suggestion**:
Add a button on the error dialog to view the log message in output. It is more friendly and quickly for customers to navigate to output.

**Actual**:
There is only 'Report an issue' button.

**Comment by nturinski** [comment]
Currently, it automatically opens the output channel with this error so closing it.
