### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by dvdobrovolskiy** [microsoft/vscode-azurestorage#244]
All files in folders listed in one level. If you have many files in container it is completely impossible to use tool.

I have static websites with 18000 files for ex.

![image](https://user-images.githubusercontent.com/7299951/47778590-03a70b00-dd19-11e8-99ae-cd8cb9594454.png)

**Comment by StephenWeatherford** [comment]
Thanks for letting us know, I believe you're the first that's wished for hierarchical display. I will say that the Azure Storage Explorer (https://storageexplorer.com) is more designed for heavy-duty management tasks than the extension, which is intended to focus more on dev tasks.

That said, to make sure we're prioritizing scenarios correctly, what types of actions do you perform where a folder display would help?  Thanks.

cc @fiveisprime

**Comment by fiveisprime** [comment]
This was requested from the NPS survey as well.

I'm definitely interested in the scenario, is this just for better visual organization or are there folder level features that need to exists? I tend to agree with the need for this just for the visual organization, it's jarring to see versus every OS.

**Comment by dvdobrovolskiy** [comment]
@StephenWeatherford thanks for reply. I found it extremely convenient to edit content in azure storage online. in Azure Storage Explorer you need to download file, change it and upload again. Here you can just edit in in almost real time

**Comment by wwlorey** [comment]
This is fixed in #441
