### ISSUE TITLE
Azure Storage Local Emulator

### ISSUE THREAD

**Issue by junalmeida** [microsoft/vscode-azurestorage#247]
Feature Request: Provide a way to access local azure storage emulator.

**Comment by Cpcrook** [comment]
I, too, would appreciate this functionality.  Seems like it _should be_ a feature of this, as the Storage Explorer standalone picks up the local emulator account already.

**Comment by JustinGrote** [comment]
Just add a vscode command that lets specifying the connection string. Preferably it would support '
'UseDevelopmentStorage=true'

**Comment by cnkcb** [comment]
I also prefer 'UseDevelopmentStorage=true', so I can get it to work with the Azurite Extension and just do the whole thing from within VS Code.

**Comment by wwlorey** [comment]
This feature was included in the 0.9.0 release. Thanks for suggesting!

**Comment by junalmeida** [comment]
@wwlorey This is awesome, thank you for taking it in consideration :)
