### ISSUE TITLE
No subscriptions list when prompting to select a subscription

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#251]
**OS:** Win10
**Node.js:** V8.12.0
**Build Definition:** [20181120.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=716&view=logs)

**Repro Steps:**
1. Make sure there are 2 selected subscriptions at least --> Sign out.
2. F1 --> Type and select 'Azure Storage: Deploy to Static Website...'.
3. Select 'Sign in to Azure...' according to the notification.
![image](https://user-images.githubusercontent.com/34729092/48834264-532ca400-edb8-11e8-84a8-6da912d86405.png)
4. Check whether the available subscriptions list or not after signing in successfully.

**Expect:**
List the available subscriptions according to the notification.

**Actual:**
No subscriptions list.
![image](https://user-images.githubusercontent.com/34729092/48834338-8b33e700-edb8-11e8-9a6c-5b695d112ce1.png)

**Comment by nturinski** [comment]
This doesn't repro in the latest build. Please let us know if you can still repro it.
