### ISSUE TITLE
Show an unmatched context menu when right clicking on a folder in Explorer

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurestorage#252]
OS: Win10
Node.js: V8.11.3
Build Definition: 20181125.1

**Repro Steps**:

1. Launch VS Code and make sure have storage extension installed.
2. Go to view -> Explorer -> Open a folder.
3. Right click the folder in Explorer -> Check the context menu of the folder.

**Expect**:
The context menu shows like below.
![image](https://user-images.githubusercontent.com/41351993/49002640-205d2400-f19b-11e8-8594-c7b6017f1075.png)

**Actual**:
The context menu shows like below.
![image](https://user-images.githubusercontent.com/41351993/49002657-28b55f00-f19b-11e8-85a5-5d59226e5127.png)

**Comment by StephenWeatherford** [comment]
You're clicking on the menu bar. For the main folder, you have to click below all the files in it (I agree, it's confusing, but this is vscode's behavior).  Thanks!
![image](https://user-images.githubusercontent.com/6913354/49109843-a4b5b280-f240-11e8-998c-53c5ab91706a.png)

**Comment by StephenWeatherford** [comment]
Entered a vscode bug: https://github.com/Microsoft/vscode/issues/63876
