### ISSUE TITLE
command 'azureStorage.refresh' not found

### ISSUE THREAD

**Issue by benc-uk** [Microsoft/vscode-azurestorage#27]
I've installed the extension, reloaded and I see nothing in the Azure Storage panel. 
I'm logged into Azure with the standard Azure account extension. When I click the refresh icon in the storage panel, I get an error **"command 'azureStorage.refresh' not found"**

Running VSCode 1.18.1 on Windows 10

**Comment by JakeRadMSFT** [comment]
I'm unable to reproduce the issue. Can you try to  reinstall?

Perhaps something didn't install properly the first time.

**Comment by AtillaYadik** [comment]
I am getting the same error message - "command 'azureStorage.refresh' not found"

**Comment by JakeRadMSFT** [comment]
Could you open up the Dev Tools and see if there are any errors in the console?

Help -> Toggle Developer Tools

**Comment by benc-uk** [comment]
Ahha! **Activating extension `ms-azuretools.vscode-azurestorage` failed: Cannot find module 'regedit'**
![image](https://user-images.githubusercontent.com/14982936/33956230-dc380ca8-e035-11e7-8779-c205b92c0248.png)

**Comment by JakeRadMSFT** [comment]
Thanks! I'll push an update!

**Comment by JakeRadMSFT** [comment]
Could you try out https://github.com/Microsoft/vscode-azurestorage/releases/tag/V0.1.2 before we publish to the gallery?

**Comment by benc-uk** [comment]
Hi @JakeRadMSFT I can confirm 0.1.2 loads OK, thanks!

**Comment by JakeRadMSFT** [comment]
Resolved with V0.1.2
