### ISSUE TITLE
[static websites] Fail gracefully when static websites aren't supported

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurestorage#270]
**OS**: Win10/MacOS/Linux
**Node.js**: V10.13.0
**Build Definition**: [20181213.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1522)

The portal continues to load when trying to enable website hosting for a Mooncake/Blackforest account (more than 20 mins)

**Repro Steps**:
1. Sign in storage extension with 'Azure China' account. 
2. Create a GPV2 account in portal.
3. Right click this storage account in VS Code -> Select 'Deploy to Static Website...'.
4. Click 'yes' on the prompted dialog on the bottom right corner -> Check the result in portal.

**Expect:**
Succeed to enable website hosting for a Mooncake account in portal.

**Actual:**
Keep loading in Portal more than 20 mins.

**More Info:**
1. This issue also reproduces for Azure Germany account.
2. **Suggestion:** Add notification to prompt customers that this action doesn't support. Due to there is no 'State website' for Mooncake and Azure Germany accounts.
![image](https://user-images.githubusercontent.com/41351993/49991948-93e59a80-ffbd-11e8-89b1-f799a5b8488f.png)

**Comment by nturinski** [comment]
@v-dantch Could you reconfirm this?  Mooncake might support static websites by now.

**Comment by nturinski** [comment]
@jinglouMSFT Please get @wwlorey access to a Mooncake account so he can test this.

**Comment by v-dantch** [comment]
Hi @nturinski , verified this issue with Azure China and Azure Germany accounts on the latest build [20200318.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16405&view=artifacts&type=publishedArtifacts). And now we can succeed to deploy to static website.
![image](https://user-images.githubusercontent.com/34729092/77023420-43d84f00-6949-11ea-8b3b-8d796e4c4e38.png)

**Comment by nturinski** [comment]
Great, thanks @v-dantch 😁
