### ISSUE TITLE
Update 'Delete' to 'Delete Blob…' on the context menu of blobs

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurestorage#272]
**OS**: Win10/MacOS/Linux
**Node.js**: V10.13.0
**Build Definition**: [20181213.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1522)

**Repro Steps:**
1. Expand a storage account -> Expand a blob container which contains at least one blob.
2. Right click the blob -> Check the context menu.

**Expect:**
Show 'Delete Blob...' on the context menu.

**Actual:**
Show 'Delete' on the context menu.
![image](https://user-images.githubusercontent.com/41351993/49992737-dc9e5300-ffbf-11e8-95ba-6ea9fd317867.png)

**More Info:**
1. This issue also reproduces for files of file share.
2. It would be better to keep consistent with the context menu of blob container/file shares/directory for file share/tables/queues.
![image](https://user-images.githubusercontent.com/41351993/49995238-87197480-ffc6-11e8-82ca-bec73461c630.png)

**Comment by nturinski** [comment]
Change `Delete Directory` to `Delete..` and update `Delete` label to be `Delete...`
