### ISSUE TITLE
Display inconsistent log messages when creating empty text between blobs and files in Output window

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurestorage#273]
**OS**: Win10/MacOS/Linux
**Node.js**: V10.13.0
**Build Definition**: [20181213.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1522)

**Repro Steps:**
1. Expand a storage account -> Expand 'Blob Containers' and create a new blob container.
2. Right click the new blob container -> Select 'Create Empty Text Blob...' to create a new block blob.
3. Under the same storage account -> Expand 'File Shares' and create a new file share.
4. Right click the new file share -> Select 'Create Empty Text File...' to create a new file.
5. Check the 'OUTPUT' window.

**Expect:**
Display consistent messages when creating empty text blobs and empty text files.

**Actual:**
Display inconsistent log messages.
![image](https://user-images.githubusercontent.com/41351993/49996063-eb3d3800-ffc8-11e8-8709-fdf0e55e5f48.png)

**Comment by nturinski** [comment]
This is fixed now.
