### ISSUE TITLE
Able to enable/disable the Static Website for hierarchical namespace accounts even though there is no 'Static Website' item in Azure Portal

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurestorage#281]
**OS**: Win10
**Node.js:**  V10.14.0
**Build Version**: [20190121.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2306)

**Repro Steps:**
1. Create one hierarchical namespace account in Azure Portal.
2. Right click the created account -> Select 'Broswer Static Website' ->Click 'Enable website hosting' on the popped diaalog.
3. Use the default document name and document path -> Press 'Enter' -> Check the shown notification.
4. Right click the same account then select 'Disable Static Website'-> Check the result.

**Expect:**
Enable/Disable Static Website doesn't support for hierarchical namespace accounts.

**Actual:**
Able to enable/disable Static Website for hierarchical namespace accounts.

**Comment by v-xianya** [comment]
Verified on build [20190214.4](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3207&view=results). 
This issue also reproduces for Azure China accounts and Azure Germany accounts.
