### ISSUE TITLE
VSTS Support

### ISSUE THREAD

**Issue by MouthOfMadness** [Microsoft/vscode-azurestorage#284]
Can this be automated in VSTS and is it a replacement for storage-preview?

**Comment by StephenWeatherford** [comment]
@MouthOfMadness I don't understand your question.  Do you have the right repro?  This is for the vscode Azure Storage extension (https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage).

**Comment by MouthOfMadness** [comment]
Recently my powershell command for configuring a static website on V2 storage (a CDN) quit working:  az extension add --name storage-preview

I receive the following error: No matching extensions for 'storage-preview'. Use --debug for more information.

I started looking for a replacement and thought maybe this is it.  However, reading through it, I get the impression that this is not a Devops extension, but rather an interactive extension.

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT Do you know where he should go to file this issue?  Thx.

**Comment by MouthOfMadness** [comment]
Yes I do, thank you for asking.

**Comment by StephenWeatherford** [comment]
I think you should start here: https://github.com/Azure/azure-cli-extensions/issues.  Good luck!

**Comment by MouthOfMadness** [comment]
Unfortunately, I’ve already been here.

**Comment by StephenWeatherford** [comment]
You entered an issue there?

**Comment by MouthOfMadness** [comment]
It would be duplication, but from what I read, you need to use a clean installation of azure-cli, which works great on my desktop.

I attempted to update the VSTS hosted agent’s az cli, but the agent wouldn’t accept the installation, even with the full path URL.
