### ISSUE TITLE
[Linux] Handle 'Open in Storage Explorer' commands better

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-azurestorage#289]
Related to #140 

The crux is that we currently cannot open a view focused on a specific resource. This is a know Storage Explorer behavior. 
For linux we should either: 
1. Change all commands to merely opening Storage Explorer, or
2. Hide the command. 

The code as of v0.6.0 currently _does not consider Linux_ as a possible OS for the user w.r.t these commands.

**Comment by ejizba** [comment]
Fixed in https://github.com/microsoft/vscode-azurestorage/pull/900 and https://github.com/microsoft/vscode-azurestorage/pull/908
