### ISSUE TITLE
"An incorrect number of bytes was read from the connection." error

### ISSUE THREAD

**Issue by alexandair** [Microsoft/vscode-azurestorage#29]
Some files from a File Share open correctly, some files fail with the following error message:

Opening 'Microsoft.PowerShell_profile.ps1' ... Failed.
Error Details: An incorrect number of bytes was read from the connection. The connection may have been closed.

**Comment by JakeRadMSFT** [comment]
@alexandair - Thanks for reporting! We have a new release going out soon that should fix this issue.

**Comment by JakeRadMSFT** [comment]
Resolved with V0.1.3

**Comment by alexandair** [comment]
That was fast. Great!
