### ISSUE TITLE
Sign in to Azure not working

### ISSUE THREAD

**Issue by kristianjaeger** [Microsoft/vscode-azurestorage#292]
Issue Type: <b>Bug</b>

Actual: Sign in to Azure not working.  Extension provides no error but does not sign in.

Expected: sign in works

Repro steps:
1) install extension 
2) click the 'A' type icon for the Azure Storage extension
3) click 'sign in to azure...'

Any known workarounds?  Use CLI instead?

Extension version: 0.5.0
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (2 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>

**Comment by StephenWeatherford** [comment]
@chrmarti Any ideas?

**Comment by kristianjaeger** [comment]
Thanks.  Any help would be appreciated.  It's pretty easy to do this with AWS or Github so it's a little disappointing this isn't working...

**Comment by StephenWeatherford** [comment]
@kristianjaeger We use the Azure Account extension to sign in to Azure, unfortunately there's no work-around if that's not working. If @chrmarti doesn't reply soon, you should probably create an issue there (https://github.com/Microsoft/vscode-azure-account).

Can you provide more info of exactly what you're seeing?  Also, could you try another of our extensions, such as https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb and see if you get the same behavior?  Thanks!

**Comment by chrmarti** [comment]
@kristianjaeger When you trigger the sign-in, does the browser open or does VS Code show a notification bottom-right? Can you follow these and at which point does it get stuck?

**Comment by kristianjaeger** [comment]
Thanks @chrmarti .  So what happens is I click "Sign in to Azure..." on any of the Azure extensions (storage, app service, functions, cosmos db) and it quickly says changes to like "Waiting for Azure..." and nothing else.  It does not open a browser and it does not show a notification.  If there's a way to do the same thing with Azure CLI that's fine too for a workaround.  Cheers.

**Comment by kristianjaeger** [comment]
Also @chrmarti let me know if you want me to get more detailed logs or attach a debugger or something.  Cheers.

**Comment by chrmarti** [comment]
@kristianjaeger Is there anything in the console (Help > Toggle Developer Tools)? Can you check if the browser opens for the "Azure: Create an Account" command?

**Comment by kristianjaeger** [comment]
Thanks @chrmarti .  I had not tried the "Developer Tools" section of VS Code before.  Here are more details from trying the Sign In option from the extension.

2console.ts:134 [Extension Host] Error: self signed certificate in certificate chain
	at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
	at TLSSocket.emit (events.js:182:13)
	at TLSSocket._finishInit (_tls_wrap.js:635:8)
t.log @ console.ts:134
e.$logExtensionHostMessage @ mainThreadConsole.ts:39
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Error: Acquiring user code failed
	at module.exports.t.AzureLoginHelper.login.o.acquireUserCode (C:\Users\kjaeger\.vscode\extensions\ms-vscode.azure-account-0.8.0\dist\extension.js:229:29435)
	at B.module.exports.e.exports.createRequestHandler [as _callback] (C:\Users\kjaeger\.vscode\extensions\ms-vscode.azure-account-0.8.0\dist\extension.js:1:181962)
	at module.exports.B.init.t._callback.t.callback.t.callback (C:\Users\kjaeger\.vscode\extensions\ms-vscode.azure-account-0.8.0\dist\extension.js:181:5498)
	at B.emit (events.js:182:13)
	at B.module.exports.B.onRequestError (C:\Users\kjaeger\.vscode\extensions\ms-vscode.azure-account-0.8.0\dist\extension.js:181:14553)
	at ClientRequest.emit (events.js:187:15)
	at TLSSocket.socketErrorListener (_http_client.js:382:9)
	at TLSSocket.emit (events.js:182:13)
	at emitErrorNT (internal/streams/destroy.js:82:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
	at process._tickCallback (internal/process/next_tick.js:63:19)

How do I run that command that you mentioned?  I use VS2017 most of the time so I'm not sure how to do that.  Thanks.

**Comment by chrmarti** [comment]
Are you behind a proxy with self-signed certificates? This might be fixed once we have: https://github.com/Microsoft/vscode/issues/52880

You can run the command with `Ctrl + Shift + P` and then filtering down to it.

**Comment by kristianjaeger** [comment]
Thanks.  So, regarding the proxy question (this is a corporate network).  I'm not sure my browser proxy settings are set to 'Auto Detect'.

The "Azure: Create an Account" command succeeds in opening a new browser window (Chrome is my default). Cheers.

**Comment by kristianjaeger** [comment]
FYI, if others are hitting this issue this looks like a workaround (using a different Azure feature) - https://www.ntweekly.com/2018/01/03/deploy-static-web-site-microsoft-azure-app-services/ .  When I get time I can try this from my home computer to see if I can get around the cert issue. Cheers.

**Comment by StephenWeatherford** [comment]
@kristianjaeger I'm confused from the above comments. Is this issue resolved for you?  If not, can you try installing this extension: https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca?

Thx.

**Comment by kristianjaeger** [comment]
@StephenWeatherford No, it's not resolved.  I'll try that extension.  I was just mentioning a, non-ideal, workaround for the issue.

**Comment by kristianjaeger** [comment]
Thank you @StephenWeatherford and @chrmarti !  Stephen's workaround resolved my issue!  Cheers.

**Comment by StephenWeatherford** [comment]
@kristianjaeger Glad to hear it!  @chrmarti Will be happy when that gets incorporated! :-)
