### ISSUE TITLE
'Download' button doesn't work when trying to download Azure Storage Explorer on Linux

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#297]
**OS:** Linux
**Build Version:**[20190211.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3041)

**Repro Steps:**
1. Right click one storage account -->Select 'Open in Storage Explorer'.
2. Click 'Download' button on the prompting dialog.
![image](https://user-images.githubusercontent.com/34729092/52623372-00b3ce80-2e61-11e9-9018-4f2cebb3063d.png)

**Expect:**
Succeed to take you to the storageexplorer.com.

**Actual:**
'Download' button doesn't work.

**More Info:**
This issue doesn't reproduce on Windows and Mac.

**Comment by EricJizbaMSFT** [comment]
Yikes need to get rid of this code and just use the same `openUrl` logic as other repos: 
https://github.com/microsoft/vscode-azurestorage/blob/master/src/storageExplorerLauncher/windowsStorageExplorerLauncher.ts#L95

**Comment by wwlorey** [comment]
Fixed in 2c365fd3a43729f1bc32babec14a553d37a09afc
