### ISSUE TITLE
Navigate to 'Download Storage Explorer free with Windows OS' page after clicking 'Download' button on Mac

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#298]
**OS:** Mac
**Build Version:**[20190211.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3041)

**Repro Steps:**
1. Make sure 'Azure Storage Explorer' is not installed.
2. Right click one storage account --> Select 'Open in Storage Explorer'.
3. Click 'Download' button --> Check the result.

**Expect:**
Succeed to storageexplorer.com with Mac OS.

**Actual:**
Succeed to storageexplorer.com with Windows OS.
![image](https://user-images.githubusercontent.com/34729092/52623889-491fbc00-2e62-11e9-82ad-45b2f6590669.png)

**Comment by PrashanthCorp** [comment]
I don't think we have a URL where that option defaults to Mac.
