### ISSUE TITLE
Cannot open a blob container in Storage Explorer by 'Open in Storage Explorer' command

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#299]
**OS:** All
**Build Version:**[20190211.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3041)

**Repro Steps:**
1. F1 --> Type and select 'Azure Storage: Open in Storage Explorer'.
2. Select the subscription and storage account according to the prompting.
![image](https://user-images.githubusercontent.com/34729092/52624121-db27c480-2e62-11e9-9dad-51a4067e8fb1.png)

**Expect:**
Prompt the customers that this command only supports to open a storage account in Storage Explorer, 

**Actual:**
There is no any prompting and the customers cannot continue to select a blob container.
![image](https://user-images.githubusercontent.com/34729092/52624380-79b42580-2e63-11e9-9677-6f0c1c477ded.png)

**Comment by nturinski** [comment]
While people can open blobs in Storage Explorer, I don't think users would use the command palette to select a blob for Open in Storage Explorer.  They would be able to right-click it instead. 🔨
