### ISSUE TITLE
Self Signed Certificate in certificate chain

### ISSUE THREAD

**Issue by LeoStack** [Microsoft/vscode-azurestorage#30]
Hi guys. Trying to use the extension behind our firewall. There we have a proxy that re-encrypts traffic on a self signed certificate. I have "http.proxyStrictSSL": false in the user settings. However, that doesn't seem to apply to the extension. Is there a setting that could disable this feature?

**Comment by JakeRadMSFT** [comment]
Hey LeoStack,
We don't support that setting yet. It's a global setting but each extension needs to abide by the setting. 

Have you tried our other tool - https://azure.microsoft.com/en-us/features/storage-explorer/. Do your proxy settings work there?

We might be able to implement the same solution in our extension.

Best Regards,
Jake

**Comment by LeoStack** [comment]
@JakeRadMSFT , 

Thanks for the reply. The short answer is yes we have used Storage explorer, and we had the same error result. We use it to inspect our traffic as it leaves our domain for security purposes. Thanks for the assistance.

**Comment by JakeRadMSFT** [comment]
@LeoStack 

In Storage Explorer, did you try Edit -> Configure Proxy? Were you able to get that to work?

**Comment by StephenWeatherford** [comment]
Closing due to lack of response. @LeoStack feel free to reopen if you'd like us to look into this further, and please verify if this works for you in Storage Explorer.
