### ISSUE TITLE
Fail to expand the attached services for Azure Germany accounts

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#300]
**OS:** All
**Build Version:**[20190211.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3041)

**Repro Steps:**
1. Sign in with Azure Germany account.
2. Right click one storage account --> Select 'Copy Connection String'.
3. Attach with the copied connection string in Azure Storage Explorer with '**Azure Germany' environment**.
4. Expand the attached storage account in Storage Explorer --> Check the services.

**Expect:**
Succeed to check the services without error.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/52624811-740b0f80-2e64-11e9-8ea6-f912c95489db.png)

**More Info:**
1. This issue also reproduces for Azure China accounts.
![image](https://user-images.githubusercontent.com/34729092/52624844-88e7a300-2e64-11e9-8921-bf6d8aeababc.png)
2. This issue doesn't reproduces for Azure accounts.

**Comment by v-dantch** [comment]
More Info:
There is no any extra info in Connection String to indicate that the account belongs to Azure China & Azure Germany accounts.

**Comment by EricJizbaMSFT** [comment]
Need to do the same thing as this:
https://github.com/microsoft/vscode-azurefunctions/blob/ec65cbf9d0f4a2b7a45c250bd7c5c56587daafe1/src/utils/azure.ts#L79
