### ISSUE TITLE
[Suggestion]Provide a default directory name

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#302]
**OS:** All
**Build Version:**[20190211.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3041)

**Repro Steps:**
1. Right click one file share --> Select 'Create Directory'.
2. Check the prompting.

**Actual:**
Prompt to enter a name for the new directory.

**Suggestion:**
Provide a default directory name like it is in Azure Storage Explorer.
![image](https://user-images.githubusercontent.com/34729092/52625629-44f59d80-2e66-11e9-8f34-8f438b64b657.png)

**Comment by nturinski** [comment]
We're going to follow VS Code's convention of not giving a default name to a new folder.   Also with a default name, the user would never see the placeholder text that provides pretty much the same information.
