### ISSUE TITLE
Deploying to static website is terminated after configuring for a new storage account

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#303]
**OS:** All
*Build Version:** [20190211.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3041)

**Repro Steps:**
1. Create a new GPV2 storage account in AZURE PORTAL.
2. Click the "Deploy to Static Webaite..." button to deploy a website project to this storage account.
3. Prompt to enable website hosting like below.
![image](https://user-images.githubusercontent.com/34729092/52626084-483d5900-2e67-11e9-9d32-00857bbad937.png)
4. Click 'Enable website hosting'.
5. Succeed to configure the static website --> Check the result.

**Expect:**
The progress of deploying is not terminated, or prompt the customers to configure the static website firstly, then deploy again.

**Actual:**
Deploying to static website is terminated.

**Comment by wwlorey** [comment]
Fixed in 0.8.0
