### ISSUE TITLE
Browsing static website is terminated after configuring website hosting

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#313]
**OS**: All
**Build Version:** [20190216.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3285)
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one GPV2 storage account -->Select 'Configure Static Website...' with index document name and 404 document path.
2. Deploy one project to this storage account.
3. Navigate to Azure portal and do not set the index document name --> Save.
4. In VS Code, right click the account in Step1 --> Select 'Browse Static Website'.
5. Prompt to set index document name.
![image](https://user-images.githubusercontent.com/34729092/52937653-9beeed00-3314-11e9-83a6-6b9163a1e47f.png)
6. Check the result after updating the website hosting configuration.
![image](https://user-images.githubusercontent.com/34729092/52937685-b1641700-3314-11e9-873d-ee49020e1b02.png)

**Expect:**
Continue to browse the static website.

**Actual:**
Browsing static website is terminated.

**Comment by v-dantch** [comment]
Verified on the latest build [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=results), this issue also reproduces.

**Comment by wwlorey** [comment]
This still reproduces in master although I'm not sure if the behavior is bad necessarily

**Comment by nturinski** [comment]
This seems like an edge case to me.  Also, I'm not convinced that a user would expect the browse command to continue after it errors out.
