### ISSUE TITLE
It is supernumerary to display '+ Create New Table' when deleting a table

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#314]
**OS**: All
**Build Version:** [20190216.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3285)
**Regression:** Not a Regression

**Repro Steps:**
1. F1 --> Type and select 'Azure Storage: Delete Table...'
2. Select a subscription --> Select a storage account according to the prompt.
3. Check the listed item.

**Expect:**
Only list the existing tables.

**Actual:**
Display '+ Create New Table' command.
![image](https://user-images.githubusercontent.com/34729092/52938067-92b25000-3315-11e9-990c-5f2da9ee3c0e.png)

**More Info:**
This issue also reproduces when deleting storage accounts, deleting tables and so on.

**Comment by StephenWeatherford** [comment]
Good observation. Unfortunately, our current code doesn't easily allow this and although we could fix it, we don't feel it provides enough benefit for the cost.

**Comment by v-dantch** [comment]
Got it.
