### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by mauriciosaa** [microsoft/vscode-azurestorage#317]
Repro steps:
1) Open react Project in VSCode
2) Right click on build folder
3)  Deploy to Static WebSite
4) Ok to remove all files on storage

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "f:/GIT/br.a82efeaf.svg": connect ETIMEDOUT 191.xxx.xxx.xxx:443 

Version: 0.7.0
OS: win32

**Comment by felixbaron** [comment]
Same here

**Comment by PrashanthCorp** [comment]
Hi @felixbaron , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
