### ISSUE TITLE
Azure Storage: Configure static website. Failed to Authenticate

### ISSUE THREAD

**Issue by saffiali** [microsoft/vscode-azurestorage#318]
Action: azureStorage.configureStaticWebsite
Error type: AuthenticationFailed
Error Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:1a378ca8-301e-0022-0704-caf422000000
Time:2019-02-21

Output: 
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Version: 0.7.0
OS: win32

**Comment by wwlorey** [comment]
Hi @saffiali, were you using a VM when this error ocurred? We were able to reproduce the issue on a VM and fix it by restarting the machine.

**Comment by wwlorey** [comment]
duplicate of #501
