### ISSUE TITLE
Use vscode's env.open to open outbound links 

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-azurestorage#320]
We have code that handles environment-dependent  logic to open resources. 

Consider using [`vscode.open`](https://github.com/Microsoft/vscode/blob/0fc0db3a7fe903f825bccf97391b366da7dd8af7/src/vs/vscode.d.ts#L5925-L5935). 

Affects the following bugs: 
#299 #297 #289 #142 #140 #64

**Comment by StephenWeatherford** [comment]
Required for headless vscode.

**Comment by EricJizbaMSFT** [comment]
Closing due to https://github.com/microsoft/vscode-azuretools/issues/476 and since VS Code made `opn` work in most cases
