### ISSUE TITLE
Don't prompt to configure when creating a new account from deploy action

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestorage#322]
1. Click the deploy icon
1. Choose new storage account and create all the things
1. **Prompt to configure static website hosting**
1. Enter index document path
1. Enter error document path
1. ...

Skip step 3 when I've chosen to deploy to a new storage acount. Drop the users immediately into the configuration step.

**Comment by wwlorey** [comment]
This issue is still applicable (we always prompt for enable static website in advanced create)

**Comment by fiveisprime** [comment]
Nope. Just ran through a deployment and it's perfect!
