### ISSUE TITLE
An error occurs when browsing a folder to deploy to static website

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurestorage#324]
**Node.js:** 10.2.0
**OS**: Windows_NT x64 10.0.17134
**Extension Build**: [master/20190304.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3705)

**Steps to reproduce:**
1. Choose one GPV2 account -> Make sure the website hosting is enabled.
2. Right click the container '$web' then select 'Deploy to Static Website...'.
3. Click 'Browse' on the prompting -> Check the result.

**Expect**:
Succeed to select one folder to deploy.

**Actual**:
![image](https://user-images.githubusercontent.com/34729022/53794117-2a05ce80-3ee4-11e9-87c1-a54366869b9f.png)

**Comment by StephenWeatherford** [comment]
Having trouble reproing this, can you provide more details?  For instance, do you have a workspace or folder open, or none?

**Comment by v-xuanzh** [comment]
Hi @StephenWeatherford ,I verified this issue on latest master build 20190313.1. It DOES NOT reproduce now. Could you help to resolve it?

**Comment by StephenWeatherford** [comment]
Thanks!
