### ISSUE TITLE
When uploading blob .wasm files content type set to application/wasm rather then application/octet-stream

### ISSUE THREAD

**Issue by Lupusa87** [microsoft/vscode-azurestorage#325]
I do publish blazor apps on azure storage accounts from visual studio code using command - deploy to static website.

Uploaded .wasm file's content type is set to application/octet-stream.

Browser expects for .wasm files content type to be application/wasm, so we are forced to correct later content types using different ways, which is not convenient and requires extra time.

If it is possible please address this issue.

![untitled3](https://user-images.githubusercontent.com/40779557/54047179-68311580-41a4-11e9-8372-dc04a5f0ac69.png)

![untitled](https://user-images.githubusercontent.com/40779557/54047188-6c5d3300-41a4-11e9-8128-da1b0ae945a8.png)

**Comment by StephenWeatherford** [comment]
Created an issue here: https://github.com/Azure/azure-storage-node/issues/568

When they fix it, we can pick up the fix.

**Comment by Lupusa87** [comment]
Thank you.

**Comment by StephenWeatherford** [comment]
Np, thanks for using our extension!

**Comment by StephenWeatherford** [comment]
Their reply:
> The .wasm is not involved in the browserify-mime package version 1.2.9 used by SDK. Would you try to use option e.g. options.contentSettings.contentType to customize contentType temporarily?
[https://github.com/Azure/azure-storage-node/issues/568#issuecomment-471846740]

**Comment by Lupusa87** [comment]
@StephenWeatherford 

Thank you, so I am waiting for your new release.

**Comment by wwlorey** [comment]
Verified fixed in latest [build](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13474&view=results).
