### ISSUE TITLE
please stop this azure message in vs code every time i open it

### ISSUE THREAD

**Issue by jimecox2** [Microsoft/vscode-azurestorage#331]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.activate
Error type: Error
Error Message: Extension `ms-vscode.azure-account` is not known or not activated

Version: 0.7.0
OS: win32

**Comment by StephenWeatherford** [comment]
@jimecox2 Sorry for the inconvenience.  The Azure Storage extension requires the ms-vscode.azure-account extension to work properly. Normally vscode takes care of this dependency, so the state of having the storage extension and not the account extension shouldn't normally happen.

Are you using the Storage extension?  If not, you should uninstall it. If you are using it, I'm assuming it doesn't work, correct?  Can you try uninstalling/reinstalling both https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage and https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account?  Let me know if this doesn't help, thanks!
