### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by ssskram** [Microsoft/vscode-azurestorage#332]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Could not obtain the primary web endpoint for sites

Version: 0.7.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@ssskram Haven't seen this message before. Does it repro every time?  Is there something unique about your storage account?  Maybe you don't have required permissions?
