### ISSUE TITLE
I can't up load static file to azure

### ISSUE THREAD

**Issue by Hoangpnse62077** [Microsoft/vscode-azurestorage#333]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "/Users/macintoshhd/Downloads/realestate/img/i7.jpg": connect ETIMEDOUT 52.239.128.36:443 

Version: 0.7.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@Hoangpnse62077 Do you get this error every time?  Is it always with the same file?  And how big is that file?  Thx.
