### ISSUE TITLE
connect ETIMEDOUT 13.71.200.240:443

### ISSUE THREAD

**Issue by Ram-Dixital** [microsoft/vscode-azurestorage#334]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "c:/Users/J_Sundaraneedi/Desktop/nodeuploads-practise/node_modules/content-disposition/README.md": connect ETIMEDOUT 13.78.152.64:443 

Version: 0.7.0
OS: win32

**Comment by StephenWeatherford** [comment]
Does this happen every time?

**Comment by Ram-Dixital** [comment]
yes, I am experiencing many times.
________________________________

**Comment by felixbaron** [comment]
Same here

**Comment by viljamis** [comment]
Same here.

**Comment by PrashanthCorp** [comment]
Hi @Ram-Dixital  @felixbaron  @viljamis , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
