### ISSUE TITLE
Display "The specified account is disabled" after expanding the servers for attached storage account 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#336]
**OS:** Windows, Mac
**Build Version:**[20190409.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4832)
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure you have installed Azure Storage Explorer.
2. Sign in with Azure China account.
3. In VS Code, right click one storage account and select "Copy Connection String".
4. In Azure Storage Explorer, attach with the copied connection string and "Azure China" environment.
![image](https://user-images.githubusercontent.com/34729092/55861409-2db3f300-5b2b-11e9-978c-6753238aa48b.png)
5. Try to expand it.

**Expect:**
Succeed to expand the attached storage account and servers.

**Actual:**
Pop up an error when expanding the servers like Blob Containers.
![image](https://user-images.githubusercontent.com/34729092/55861379-1d037d00-5b2b-11e9-9bbd-1bbd030ea842.png)

More Info:
For Azure Germany account, pop up below error:
![image](https://user-images.githubusercontent.com/34729092/55861667-af0b8580-5b2b-11e9-9669-a6c25f3c2d71.png)

**Comment by wwlorey** [comment]
Related to #429

**Comment by nturinski** [comment]
Hi @v-dantch 

Could you confirm that this bug is resolved?  I think that the linked PR should have fixed it.

**Comment by nturinski** [comment]
Unfortunately, adding the endpoint suffix did not resolve the issue.

**Comment by nturinski** [comment]
@v-dantch  Actually, does this issue reproduce if you copy the connection string from the Portal?

**Comment by nturinski** [comment]
Confirmed with @v-dantch that actually #633 did resolve this issue.  Hooray!
