### ISSUE TITLE
Error Message: Extension `ms-vscode.azure-account` is not known or not activated

### ISSUE THREAD

**Issue by andrei-apps** [Microsoft/vscode-azurestorage#337]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.activate
Error type: Error
Error Message: Extension `ms-vscode.azure-account` is not known or not activated

Version: 0.7.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
@andrei-apps do you have the [azure account extension](https://marketplace.visualstudio.com/itemdetails?itemName=ms-vscode.azure-account) installed? It's a dependency of the storage extension.

VS Code recently improved the experience for this: https://code.visualstudio.com/updates/v1_33#_install-missing-dependencies
