### ISSUE TITLE
cannot deploy static website

### ISSUE THREAD

**Issue by xeiterko** [microsoft/vscode-azurestorage#338]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.configureStaticWebsite
Error type: AuthenticationFailed
Error Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:40b65209-501e-005c-38fd-f1363a000000
Time:2019-04-13T13:36:12.0756487Z

Version: 0.7.0
OS: darwin

**Comment by PrashanthCorp** [comment]
Hi @xeiterko , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
