### ISSUE TITLE
created new angular app, upload to storage, timed out

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestorage#339]
Repro steps:

```
ng new foo
cd foo
```

Then upload to storage

error

```
Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "/Users/papa/_play/foo/node_modules/zone.js/lib/node/rollup-main.ts": ESOCKETTIMEDOUT 

Version: 0.7.0
OS: darwin
```

cc @fiveisprime

**Comment by fiveisprime** [comment]
Probably related to the files you were uploading. You have to build the app first then deploy only the `dist` directory for the app to work correctly.

**Comment by PrashanthCorp** [comment]
Hey John, we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.

**Comment by johnpapa** [comment]
hi - the build is  "not found"
