### ISSUE TITLE
azureStorage.deployStaticWebsite error

### ISSUE THREAD

**Issue by dengjfatqq** [microsoft/vscode-azurestorage#340]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "h:/VS2017/Projects/Linker.link static web/Linker.link/linker.link.apk": write ECONNRESET 

Version: 0.7.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @dengjfatqq ,  I could repro this error when I physically unplugged and plugged in the connection again.
Does this error occur every time? Did you encounter the error on trying to deploy again?

**Comment by PrashanthCorp** [comment]
Hi @dengjfatqq , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
