### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mohamadalitellawi** [microsoft/vscode-azurestorage#342]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error deleting blob "images/card01.svg" : connect ETIMEDOUT 51.141.128.100:443

Version: 0.7.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @mohamadalitellawi , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
