### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by viniciushfreitas** [microsoft/vscode-azurestorage#345]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "/Users/viniciusfreitas/Documents/Dev/Projetos/nodejs/hedz/site-company/node_modules/@vue/cli-service/node_modules/caniuse-lite/data/features/css-page-break.js": connect ETIMEDOUT 191.233.128.100:443 

Version: 0.7.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@viniciushfreitas Does this happen consistently, or was it simply a one-time network issue?  If it happens consistently, how big is the folder you're deploying?  Thx.

**Comment by PrashanthCorp** [comment]
Hi @viniciushfreitas, we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
