### ISSUE TITLE
Configuring static websties

### ISSUE THREAD

**Issue by kibitok** [microsoft/vscode-azurestorage#349]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.configureStaticWebsite
Error type: AuthenticationFailed
Error Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6a44041e-a01e-002c-29dd-169859000000
Time:2019-05-30T11:51:04.7589032Z

Version: 0.7.0
OS: win32

**Comment by wwlorey** [comment]
@kibitok can you still reproduce this issue? If so, can you share the steps you took with us?
