### ISSUE TITLE
ECONNRESET error when deploying static website

### ISSUE THREAD

**Issue by lowzijian** [microsoft/vscode-azurestorage#354]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error deleting blob "vendor/fontawesome-free/svgs/brands/pagelines.svg" : read ECONNRESET

Version: 0.7.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @lowzijian  , I could repro this error when I physically unplugged and plugged in the connection again. 
Does this error occur every time? Did you encounter the error on trying to deploy again?

**Comment by lowzijian** [comment]
@PrashanthCorp  Sorry for the late reply, i have removed unnecessary svg files and somehow it works just fine. Moreover, i think the main reason behind this issue is the unstable network connection of my university wifi.
