### ISSUE TITLE
Rename extension to "Azure Storage and Static Websites"

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestorage#360]
Thoughts on this @burkeholland?

**Comment by burkeholland** [comment]
One too many "S"s.

I like it.

**Comment by StephenWeatherford** [comment]
It sure seems somewhat excessively sibilant, though.  Would "Azure Storage and Static Websites" be better?  Also wondering if people would be likely to search for website?

**Comment by burkeholland** [comment]
TIL: Sibilant: Characterized by a hissing sound.

Level up that vocab, kids.

**Comment by StephenWeatherford** [comment]
LOL and today I learned what TIL means.

**Comment by ejizba** [comment]
Not gonna happen now that we have the static web apps extension
