### ISSUE TITLE
Deploy website to storage fails (ETIMEDOUT)

### ISSUE THREAD

**Issue by alfiuzzo** [microsoft/vscode-azurestorage#362]
Hi guys, i'm trying to deploy a website (html/css/js framework bootstrap) with Visual studio code on azure storage. But my deploy always fail with that ETIMEDOUT error.
I use VSC:
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

And i have installed the azure extension for azure storage

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "..../vendors/bootstrap/less/list-group.less": connect ETIMEDOUT 20.38.108.228:443 

Version: 0.7.0
OS: win32

**Comment by felixbaron** [comment]
Same here

**Comment by PrashanthCorp** [comment]
Hi @alfiuzzo , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
