### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by felixbaron** [microsoft/vscode-azurestorage#370]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error deleting blob "css/chunk-vendors.29dc4e16.css" : connect ETIMEDOUT 52.239.143.196:443

Version: 0.7.0
OS: win32

**Comment by nturinski** [comment]
Hi @felixbaron 

Thanks for reporting this issue.  Could you please add repro steps?

**Comment by PrashanthCorp** [comment]
Hi @felixbaron , we have a fix [here](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7219). Please try it out and let us know if it solves your problem.
