### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by kingsleytth** [microsoft/vscode-azurestorage#373]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "/Users/kingsley/Tricor Dropbox/Kingsley Tan/01. IT Team/01. Projects/03. DocuTax/06. Prototype/01. Site v1/libs/bootstrap-table/locale/bootstrap-table-ru-RU.js": read ECONNRESET 

Version: 0.7.0
OS: darwin

**Comment by PrashanthCorp** [comment]
Could be a part of #352?

**Comment by PrashanthCorp** [comment]
Hi @kingsleytth , I could repro this error when I physically unplugged and plugged in the connection again. 
Does this error occur every time? Did you encounter the error on trying to deploy again?
