### ISSUE TITLE
Error deleting file

### ISSUE THREAD

**Issue by RodrigoSedano** [microsoft/vscode-azurestorage#383]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error deleting blob "helpcontent/no/std/ISA_610_files/image001.jpg" : connect ECONNREFUSED 52.239.137.228:443

Version: 0.7.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @RodrigoSedano . sorry to hear this. We released a hot fix last week that addresses some instances when such an error occurs. Can you try updating the extension and tell us whether the error still repros?
