### ISSUE TITLE
"Open in File Explorer" should be at the top

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestorage#386]
It's currently sorted alphabetically with the files so it's typically at the bottom and sometimes in the middle of the list. It should be the first option.

**Comment by v-dantch** [comment]
Verified on the build [20200114.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13766&view=artifacts&type=publishedArtifacts). The current context menu is like below:
![image](https://user-images.githubusercontent.com/34729092/72499780-c40d0600-386d-11ea-9fed-962309091b79.png)
