### ISSUE TITLE
Error on deploy

### ISSUE THREAD

**Issue by gcaldeira** [microsoft/vscode-azurestorage#391]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: AuthorizationFailure
Error Message: This request is not authorized to perform this operation.
RequestId:bbc58ce8-101e-0045-1710-383e98000000
Time:2019-07-11T17:44:51.3190904Z

Version: 0.7.0
OS: win32

**Comment by nturinski** [comment]
Hi @gcaldeira 

Thanks for reporting.  It seems like you had an authorization failure.  Do you have access to the storage account?  If not, you'll have to request to be a contributor to the account.

If yes, then please provide repro steps.
