### ISSUE TITLE
Support changing the content-type of a file.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/vscode-azurestorage#401]
I want to be able to quickly create a file in VSCode that is hosted on Azure and can immediately be referenced from a web app.  The Create Empty Text Blob _almost_ does the trick, except that it sets the content-type of the file to `text/plain`.  This is a fine/reasonable default, but I need a way to change that to `text/html; charset=utf-8` or `application/javascript` so that I can quickly hack on a text file in the cloud, hosted in a place that can be referenced by other text files.

Use case: I'm trying to test cross-origin functionality of a locally hosted web app, so I need to quickly host a number of different simple files _anywhere other than localhost_ while I'm testing so that I can see cross-origin functionality.  I want something that is quick, simple, and fully inside of VSCode (I don't want to have to switch out to another application to do file management).

**Comment by MicahZoltu** [comment]
Hmm, maybe this is actually addressed in the not-yet-released https://github.com/microsoft/vscode-azurestorage/pull/392?

**Comment by StephenWeatherford** [comment]
@MicahZoltu As a work-around, you can use the cross-platform storage explorer (https://storageexplorer.com) to do this.

**Comment by MicahZoltu** [comment]
@StephenWeatherford Am I correct that this is addressed in #392 and just waiting for a release, or am I misunderstanding that change set?  If it is in the pipe, I can just wait.  If it isn't, then I'll look for another solution to my problem as I don't want to have to use a separate desktop app for this.

**Comment by wwlorey** [comment]
Hi @MicahZoltu, unfortunately there's no native service support for renaming files in the storage extension. If you don't want to use a desktop app, you can try using the [portal](https://portal.azure.com).
