### ISSUE TITLE
Only general purpose V2 storage accounts support static website hosting.

### ISSUE THREAD

**Issue by sriramachandramacharayya** [microsoft/vscode-azurestorage#402]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.configureStaticWebsite
Error type: Error
Error Message: Only general purpose V2 storage accounts support static website hosting.

Version: 0.7.0
OS: linux

**Comment by StephenWeatherford** [comment]
@sriramachandramacharayya If you want to deploy to a static website, you'll need to create a new storage account and make sure it's a general purpose V2 account when you create it (from the portal). If you choose to create a new one from the extension, it will automatically be a general purpose V2 storage account.
