### ISSUE TITLE
Fail to create services with an error

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#408]
OS: All
Build Version: [20190724.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8080)
Branch: rel/0.7.1
Regression: Previous Release

Repro Steps:

1. Create a new storage account --> Ceate a new blob container like "test".
2. Create a new file share with the same name "test".
3. Create a new queue with the same name "test".
4. Check the result.

Expect:
The queue "test" is created successfully without any error.

Actual:
An error occurs when creating queue "test".
![image](https://user-images.githubusercontent.com/45614674/61860956-77b7bd80-aefd-11e9-80ae-0d938bf430d2.png)

More Info:

1. This issue also reproduces with the different service names.
2. This issue is unstable, it can be reproduced 5 times in 10.

**Comment by EricJizbaMSFT** [comment]
Tracked by https://github.com/microsoft/vscode/issues/71698

**Comment by v-dantch** [comment]
Verified on the latest build [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=results), this issue doesn't reproduce for now like below screenshot:
![image](https://user-images.githubusercontent.com/34729092/74222174-d48a9200-4cee-11ea-8634-d93142364bce.png)
How about closing this issue for now?
