### ISSUE TITLE
Casing of "Open container in Storage Explorer" is wrong

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#410]
**OS:** All
**Build Version:** [20190724.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8080)
**Branch:** rel/0.7.1
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure there is one blob larger than 4MB--> Right click and select "Download...".
2. The extension tells you  to use Storage Explorer --> Check the transform.

**Expect:**
Display "Open Container in Storage Explorer".

**Actual:**
Display "Open **container** in Storage Explorer".
![image](https://user-images.githubusercontent.com/34729092/61928815-34685800-afac-11e9-80a0-bb952054f4b4.png)

**Comment by wwlorey** [comment]
Our button naming isn't consistent so we'll leave this as it is :)
