### ISSUE TITLE
Refresh button doesn't clear the cache

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#413]
**OS:** Win10
**Build Version:** [20190730.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8267)
**Regression**: Not a Regression

**Repro Steps:**
1. Enable "Azure Storage: Enable View in File Explorer" in User Setting.
2. Drill down from one storage account --> "Blob Containers" node -->Expand one blob container -->Click "Open in File Explorer...".
3. Refresh the File Explorer.

**Expect:**
The File Explorer refreshes well with obvious indication.

**Actual:**
There is no any indication.

**Comment by monalgarg** [comment]
There is a loading bar at the top. I also have noticed if a folder is open, then a spinning disk will appear on the left.

**Comment by v-dantch** [comment]
Hi @monalgarg , yes there is indication when opening in File Explorer and there is a spinning disk when opening a folder. But there is no obvious indication when clicking "Refresh Explorer" button. Is it related to the number of files/folders?
![image](https://user-images.githubusercontent.com/34729092/62261800-1174f280-b449-11e9-985b-54c86d1801ac.png)

**Comment by EricJizbaMSFT** [comment]
The problem is you don't see an indication because it's so fast. We need to investigate if we can make the refresh button clear the cache and _actually_ refresh

**Comment by v-dantch** [comment]
Yes, actually "Refresh" button works well. And we hope there is an indication, regardless of the number of files/folders.

**Comment by wwlorey** [comment]
We think this is fixed but it needs to be verified.

**Comment by v-dantch** [comment]
Verified on the latest build [20191112.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12368), fixed. 
We will close this issue for now :) .
