### ISSUE TITLE
The new created empty folder doesn't disappear after refreshing the File Explorer

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#415]
**OS:** Win10
**Build Version:** [20190730.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8267)
**Regression**: Not a Regression

**Repro Steps:**
1. Enable "Azure Storage: Enable View in File Explorer" in User Setting.
2. Drill down from one storage account --> "Blob Containers" node -->Expand one blob container --> Click "Open in File Explorer...".
3. Click the "New Folder" button to create a new empty folder in File Explorer.
4. Refresh the File Explorer --> Check the result.

**Expect:**
The new created empty folder disappears from the File Explorer.

**Actual:**
The new created empty folder still lists.
![image](https://user-images.githubusercontent.com/34729092/62200669-c076d880-b33a-11e9-817c-d0fb1274f1d7.png)

**Comment by monalgarg** [comment]
Sorry, meant to change this test case. It should be the following...

1. Enable "Azure Storage: Enable View in File Explorer" in User Setting.
2. Drill down from one storage account --> "Blob Containers" node -->Expand one blob container --> Click "Open in File Explorer...".
3. Click the "New Folder" button to create a new empty folder in File Explorer.
4. Exit out of this session and reopen VS code. 
5. When reopening this same blob container, the empty folder should not show up on the UI.

Refreshing File Explorer should not remove any empty virtual folders.

**Comment by v-dantch** [comment]
Hi @monalgarg , verified this issue on the new build [20190731.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8307) and the new created empty folder disappears after reopening VS Code according to the updated test case. Could you help to close this bug?
