### ISSUE TITLE
[Suggestion]Remove the files from the editor after deleting its parent folder 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#425]
**OS:** Windows_NT x64 10.0.17763
**Version**: 1.37.0-insider (user setup)
**Commit**: 5e08ee01b7daee99cdda2456f19d77e715fb8762
**Build Version:**[ 20190805.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8478)
**Regression:** Not a Regression

**Repro Steps:**
1. Drill down from one storage account -> File Shares node.
2. Create a file share -> Create a directory -> Select "Create Empty Text File..." from the directory context menu -> Open the file in editor.
3. Delete the directory -> Check whether the file in editor auto removes or not.

**Actual:**
The file still lists in editor.

**Suggestion:**
Remove the files from the editor.

**More Info:**
The file opened in editor auto removes after deleting its parent folder in File Explorer.

**Comment by EricJizbaMSFT** [comment]
Might be fixed if we implement watch

**Comment by EricJizbaMSFT** [comment]
Never mind - this is the Azure View not file view

**Comment by PrashanthCorp** [comment]
We don't have an API call to close the editor view

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
