### ISSUE TITLE
Connection Strings: Cannot attach sovereign storage account in Storage Explorer using our generated connection string 

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-azurestorage#429]
See https://github.com/microsoft/AzureStorageExplorer/issues/1598 for more details. 

Our `getConnectionString()` function does not add an `EndpointSuffix` for sovereign accounts. 

For Azure CN - EndpointSuffix=core.chinacloudapi.cn
Azure Vanilla  - EndpointSuffix=core.windows.net

**Comment by nturinski** [comment]
Clsoing as a dupe of https://github.com/microsoft/vscode-azurestorage/issues/336
