### ISSUE TITLE
[Discussion] Finalize uri format for storage file provider

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#431]
File share uris currently look like this:
> azurestoragefile:/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgname/providers/Microsoft.Storage/storageAccounts/accountname/File Shares/filesharename

Blob uris currently look like this:
> azurestorageblob:/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgname/providers/Microsoft.Storage/storageAccounts/accountname/Blob Containers/blobname

We should make extra sure we agree on the format of the uri because changing this will break users in the future. A few things to consider:
1. Do we need separate 'azurestoragefile' and 'azurestorageblob' schemes? The id's above already say if it's a blob or file share, so I don't see any reason to have separate ones
1. Do these uris still work in sovereign accounts?
1. Should we make our uri more similar to storage explorer? This is what a storage explorer uris looks like:
> storageexplorer://v=1&accountid=%2Fsubscriptions%2F00000000-0000-0000-0000-000000000000%2FresourceGroups%2Frgname%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Faccountname&subscriptionid=00000000-0000-0000-0000-000000000000&source=VSCODE-AzureStorage&resourcetype=Azure.BlobContainer&resourcename=filesharename

**Comment by fiveisprime** [comment]
1. Nope, that seems redundant.
1. That's definitely something that should be tested..
1. Is there any compelling reason not to follow that pattern? It's a bit uglier, but what does that matter?

**Comment by EricJizbaMSFT** [comment]
I agree it's uglier and I'm not sure we need all those extra parameters haha. I would probably advocate for something like this:
> azurestorage:///folder1/subfolder2/hello.txt?resourceId=%2Fsubscriptions%2F00000000-0000-0000-0000-000000000000%2FresourceGroups%2Frgname%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Faccountname%2FFile%20Shares%2Ffilesharename

I think I'm sold on leveraging the query section for two reasons:
1. VS Code displays the uri in the open editors section, so I'm hoping just "folder1/subfolder2/hello.txt" would get displayed instead of the whole id like it is in master today:
![Screen Shot 2019-08-08 at 9 13 12 AM](https://user-images.githubusercontent.com/11282622/62719872-c2393f80-b9bd-11e9-8b5c-f3074c86ea76.png)
1. It just seems more flexible. If we have problems with sovereign accounts, we can just add another query parameter if necessary

I am diverging a bit by using resourceId instead of accountId/resourcetype/resourcename, but that just feels cleaner and it gives the same information. We could easily use the same pattern for Cosmos DB and App Service.

If you use standard node.js URL to parse the above URL, you get this:

- host: ""
- hostname: ""
- pathname: "/folder1/subfolder2/hello.txt"
- protocol: "azurestorage:"
- search: "?resourceId=%2Fsubscriptions%2F00000000-0000-0000-0000-000000000000%2FresourceGroups%2Frgname%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Faccountname%2FFile%20Shares%2Ffilesharename"

If you use VS Code URL to parse the above URL, you get this:

- fsPath: "/folder1/subfolder2/hello.txt"
- path: "/folder1/subfolder2/hello.txt"
- query: "resourceId=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rgname/providers/Microsoft.Storage/storageAccounts/accountname/File Shares/filesharename"
- scheme: "azurestorage"

**Comment by fiveisprime** [comment]
I like the query approach a lot 👌 Let's go with that.
