### ISSUE TITLE
Cross-file intellisense doesn't work with file provider

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurestorage#432]
Add two typescript files. One with:
```
export function helloWorld() {
    console.log('hello world');
}
```

And one with:
```
import * as test from './'
```

Type 'ctrl+space' after the slash to bring up intellisense

Expected:
![Screen Shot 2019-08-07 at 9 33 44 AM](https://user-images.githubusercontent.com/11282622/62640462-796a8380-b8f6-11e9-9367-f96a637a2d83.png)

Actual:
![Screen Shot 2019-08-07 at 9 31 43 AM](https://user-images.githubusercontent.com/11282622/62640372-4d4f0280-b8f6-11e9-8d78-632ff046a990.png)

**Comment by PrashanthCorp** [comment]
I came across this [comment thread](https://github.com/microsoft/vscode/issues/74611#issuecomment-497328583) that suggests this may be unsupported at this time.

**Comment by wwlorey** [comment]
Adding "azurestorage" to [`supportedSchemes`](https://github.com/microsoft/vscode/blob/5c02e4b2a149c1e2e9bb03b267d3b6727607cf72/extensions/typescript-language-features/src/utils/fileSchemes.ts#L11) doesn't fix intellisense on its own. We're waiting for VS Code to allow this sort of functionality (https://github.com/microsoft/vscode/issues/59650)

**Comment by ejizba** [comment]
VS Code issue was fixed: https://github.com/microsoft/vscode/issues/59650#issuecomment-712516291

Good enough for us at this point.
