### ISSUE TITLE
Support "Add to workspace" and "Open in current window" for file view

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#434]
Rather than always open in a new window, we might want to support three options:
1. Open in current window
1. Open in new window
1. Add to workspace

Similar to what Azure functions does when creating a new project
![Screen Shot 2019-08-07 at 10 08 08 AM](https://user-images.githubusercontent.com/11282622/62642758-45de2800-b8fb-11e9-9b40-b83b6dea46e9.png)

Might help https://github.com/microsoft/vscode-azurestorage/issues/387

**Comment by PrashanthCorp** [comment]
For the 0.7 release, support just open in current window.
