### ISSUE TITLE
Investigate disabling rename for file explorer

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#437]

**Comment by PrashanthCorp** [comment]
After talking offline to Matt, we know we cannot disable this button


TODO: 
1. Verify telemetry is present for rename. 
2. Add error message if someone calls rename. 
3. Verify if rename works on File Share. We know it doesn't work on blobs.

**Comment by wwlorey** [comment]
@fiveisprime do you know if disabling rename on the VS Code side is possible?

**Comment by fiveisprime** [comment]
I asked about this a while back and it wasn't possible. I doubt that's changed.

**Comment by wwlorey** [comment]
1. Telemetry is present for rename
2. Error messages exist when rename is called
3. Rename isn't supported for file shares
