### ISSUE TITLE
not able to deploy site to storage account

### ISSUE THREAD

**Issue by preetb123** [microsoft/vscode-azurestorage#440]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND lubecompadmin.blob.core.windows.net lubecompadmin.blob.core.windows.net:443

Version: 0.7.1
OS: darwin

**Comment by PrashanthCorp** [comment]
Can you add some repro steps? 
And does this repro consistently?
