### ISSUE TITLE
Cmd + clicking one a file path does not correctly open the file

### ISSUE THREAD

**Issue by monalgarg** [microsoft/vscode-azurestorage#446]

**Comment by monalgarg** [comment]
The problem is that when you cmd + click a link "/filepath", it tries to read "azurestorage://filepath", which doesn't exist without information about what subscription it is under or what blob container/file share it is under. So, we would have to append the same query part of the uri of the file that you are cmd + clicking from to this readFile call.

**Comment by PrashanthCorp** [comment]
Related #431?
