### ISSUE TITLE
The icons of some folders and files are changed after refreshing the File Explorer

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#451]
**OS:** Win10
**Build Version:** [20190820.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8990)
**Regression:** Not a Regression

**Repro Steps:**

1. Enable "Azure Storage: Enable View in File Explorer" in User Setting.
2. Drill down from one storage account --> "Blob Containers" node -->Expand one blob container -->Upload/Create some blobs->Click "Open in File Explorer...".
3. Click 'Refresh Explorer' to refresh the File Explorer.
4. Check the result.

**Expect:**
The File Explorer refreshes and all icons shows well.

**Actual:**
The icons of some folders and files are changed after refreshing.
![image](https://user-images.githubusercontent.com/45614674/63407589-6d66e180-c41f-11e9-8833-516d7e9db754.png)

**Comment by v-dantch** [comment]
Verified on the latest build [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=results), this issue does not reproduces with below blobs.
![image](https://user-images.githubusercontent.com/34729092/74221128-57f6b400-4cec-11ea-9f29-fcb867eb1dca.png)
