### ISSUE TITLE
Deploy to static website ignores .well-known folder

### ISSUE THREAD

**Issue by mbondoso** [microsoft/vscode-azurestorage#457]
![image](https://user-images.githubusercontent.com/8534161/64537628-10ba6080-d313-11e9-8c1c-ac7db447a3ee.png)

When I click on Deploy Static Website on my webapp folder, it ignores the .well-known folder.

Has anyone had this issue or do I need to change any config ?

**Comment by PrashanthCorp** [comment]
We originally hid `.xyz` directories so that we don't deploy `.git` and `.vscode` directories. 

Is there a production use case for hidden folders?

**Comment by PrashanthCorp** [comment]
TODO: Ignore only `.git` and `.vscode` folders in deployment.

**Comment by mbondoso** [comment]
@PrashanthCorp .well-known is the folder that keeps the assetlinks for android verification of PWA's. Since we deploy our website on azure storage, that's were it came needed.

Thanks!
