### ISSUE TITLE
Blob file CacheControl value is cleared on update

### ISSUE THREAD

**Issue by stevenjh** [microsoft/vscode-azurestorage#464]
When using the the Azure Storage extension to open and update a blob file, the CacheControl values are reset.

It would be good if an existing value is persisted / re-applied on save.

Thanks!

**Comment by wwlorey** [comment]
This was fixed in https://github.com/microsoft/vscode-azurestorage/pull/499 and is included in our latest [release](https://github.com/microsoft/vscode-azurestorage/releases/tag/v0.8.0).

Thanks for reporting!
