### ISSUE TITLE
Pop up 2 confirming dialogs when deleting a blob in File Explorer

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#467]
**OS:** Win10 & Mac
**Build Version:** [20190926.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10489)
**Regression:** Previous Build

**Repro Steps:**
1. Enable feature "Azure Storage: Enable View in File Explorer..." in User Setting.
2. Drill down from one storage account --> Blob Containers node --> one blob --> Click "Open in File Explorer".
3. Right click one blob file in File Explorer --> Select "Delete Permanently".

**Expect:**
Pop up one dialog to ask whether want to delete the file or not.

**Actual:**
Pop up 2 confirming dialog.
![image](https://user-images.githubusercontent.com/34729092/65753856-6cbe1b00-e142-11e9-85f1-0e1f1f381af9.png)

**More Info:**

1. This issue does not reproduce for file share.
2. This issue does not reproduce for a blob folder.
3. The blob file has been deleted and disappears from the view actually after selecting "Cancel" on the second dialog.

![image](https://user-images.githubusercontent.com/34729092/65754136-fa016f80-e142-11e9-922f-ad803fadfd7b.png)

**Comment by wwlorey** [comment]
@v-dantch I'm only seeing one prompt with the current build. Can you still repro?

**Comment by v-dantch** [comment]
Hi @wwlorey ,verified this issue with [20191203.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12802), this issue does not reproduce for now. So we will close it for now.
