### ISSUE TITLE
cant connect to  azureStorage.browseStaticWebsite

### ISSUE THREAD

**Issue by vency-pcci** [microsoft/vscode-azurestorage#468]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.browseStaticWebsite
Error type: Error
Error Message: Entry not found in cache.

Version: 0.7.1
OS: win32

**Comment by wwlorey** [comment]
As a workaround you could try refreshing the tree using the refresh button in the explorer.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
