### ISSUE TITLE
Expand the service node and focus on the new created resource for all services

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#470]
**OS:** All
**Build Version**: [20190929.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10596)
**Regression:** Not a Regression

**Repro Steps:**
1. Make sure the Blob Containers node is collapsed.
2. Right click it and select "Create Blob Container..." --> Enter a valid blob container name.

**Actual:**
Succeed to create the new blob container, but the fail to focus on the new created resource.

**Suggestion:**
Succeed to create a new blob container. Meanwhile expand the Blob Containers node and focus on the new resource.

**More Info:**
This issue also reproduces for file share/table/queue.

**Comment by wwlorey** [comment]
We don't have this functionality on our other extensions
