### ISSUE TITLE
Pop up an error after expanding Blob Containers for the second attached storage account

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#48]
Repro Steps:

1. Right click one storage account and select 'Copy Connection String'.
2. Attach the storage account using the copied Connection String in Storage Explorer.
3. Attach the same account again using the copied Connection String.
4. Expand the Blob Containers node for the second attached storage account.

Expect:
There is no error dialog.

Actual:
Pop up an error dialog.
![443](https://user-images.githubusercontent.com/34729092/35733873-eaf6a73c-0816-11e8-8d40-a498f9d0da24.png)

More Info:

1. This issue reproduces on Mac/Windows.
2. This issue also reproduces for File Shares, Queues and Tables.

**Comment by StephenWeatherford** [comment]
Moved to Storage Explorer bugs.
