### ISSUE TITLE
Getting error when followed the instructions provided in MS Learn

### ISSUE THREAD

**Issue by amitjaipaul** [microsoft/vscode-azurestorage#481]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.configureStaticWebsite
Error type: Error
Error Message: Only general purpose V2 storage accounts support static website hosting.

Version: 0.7.1
OS: darwin

**Comment by wwlorey** [comment]
What type of storage account are you using? A V2 account is required for static website hosting.

**Comment by amitjaipaul** [comment]
Ok Thanks. That fixed the problem

**Comment by wwlorey** [comment]
Glad we could help! Let us know if you run into any more issues
