### ISSUE TITLE
Clicking the + button in the Azure Storage section tries to connect to SQL instead of Azure Storage

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/vscode-azurestorage#490]
Clicking the + button next to Azure Storage seems linked to the wrong behavior.

When I first clicked it, it installed the SQL tools for VS Code.
Also, it asks for a SQL connection string.

See screenshot:
![image](https://user-images.githubusercontent.com/3463496/67145863-78a28600-f285-11e9-9c0b-77d52b7a9212.png)

**Comment by EricJizbaMSFT** [comment]
@hansmbakker I don't think that "plus" button is contributed by this extension. I don't see it on v0.7.2:
![Screen Shot 2019-10-21 at 9 50 11 AM](https://user-images.githubusercontent.com/11282622/67225487-3180d600-f3e8-11e9-8183-a90d43da34e0.png)

Can you let us know what other extensions you have installed? We probably want to file an issue on the one contributing that...

**Comment by hansmbakker** [comment]
I installed [Azure Tools](https://github.com/microsoft/vscode-node-azure-pack) (extension pack by Microsoft) which installs all kinds of Azure-related extensions including the Storage extension.

The string that you get (`hostname\instance or <server>.database.windows.net or ADO.NET connection string`) [comes from the mssql extension](https://github.com/search?p=1&q=%22hostname%5Cinstance+or+%3Cserver%3E.database.windows.net+or+ADO.NET+connection+string%22&type=Code).

Why it is triggered by the Storage section I don't know.

**Comment by EricJizbaMSFT** [comment]
Looks to be addressed in https://github.com/microsoft/vscode-mssql/pull/1456
