### ISSUE TITLE
Update subscription icon

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurestorage#5]
Use the gold key icon instead, it's here: https://github.com/Microsoft/vscode-azuretools/tree/master/ui/resources

See also: https://github.com/Microsoft/vscode-azuretools/blob/bee3003c84c1ac1843a47b9a5ae83275bbbedb79/ui/src/treeDataProvider/SubscriptionNode.ts#L24

![image](https://user-images.githubusercontent.com/1186948/33583250-441db2fc-d90e-11e7-9c9b-027fbb9b8624.png)

**Comment by EricJizbaMSFT** [comment]
Looks like this was already fixed
