### ISSUE TITLE
Create new file share should validate against existing shares

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurestorage#50]
If I try to create a file share with a name that already exists, I get this error:
![screen shot 2018-02-02 at 11 26 12 am](https://user-images.githubusercontent.com/11282622/35751074-f3746576-080b-11e8-843b-4a9492071b99.png)

Not the worst experience, but would be better if we validated as the user was typing. This probably repros for other types of storage resources

**Comment by v-mengwe** [comment]
If I try to create a Queue/Tables with a name that already exists, I get this error:
![image](https://user-images.githubusercontent.com/62053665/84862462-cfc35980-b0a5-11ea-94b7-8a60841a2874.png)
It would be better if validated as the user was typing.
