### ISSUE TITLE
Azure Storage (The server is busy) Error

### ISSUE THREAD

**Issue by piyushkacha7** [microsoft/vscode-azurestorage#502]
Repro steps:
I try to update Storage account but I can't perform to azure storage update 

Action: azureStorage.deployStaticWebsite
Error type: ServerBusy
Error Message: The server is busy.
RequestId:d4d1bd34-d01e-006d-2c3b-9527ff000000
Time:2019-11-07T07:19:09.4697076Z

Version: 0.7.2
OS: win32
![Annotation 2019-11-07 131049](https://user-images.githubusercontent.com/47378765/68369341-13dd9b80-0160-11ea-85a5-498950b4bfe6.png)

**Comment by piyushkacha7** [comment]
Also some time this kind of error rise for update storage 
![image (1)](https://user-images.githubusercontent.com/47378765/68369888-56ec3e80-0161-11ea-95d5-d52e303f1d22.png)

**Comment by nturinski** [comment]
Hi @piyushkacha7,

Is this consistently happening?  Typically this error means that the server is under load, but if you wait a bit and retry, you should be able to deploy.

If  it is happening consistently, could you provide repro steps including the type of project that you are trying to deploy?

**Comment by piyushkacha7** [comment]
Hey @nturinski , It's working 5 days ago West Europe in under a maintenance. It's not working for faw hours only.
