### ISSUE TITLE
[Suggestion]Auto focus on the new created files and folders

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#507]
**OS:** All
**Build Version:** [20191112.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12368)
**Regression:** Not a Regression

**Repro Steps:**
1.  Enable "Azure Storage : Enable View In File Explorer" in User Settings.
2. Create a storage account --> Create a new blob container --> Click "Open in File Explorer" --> Create a new file or folder in File Explorer.

**Actual:**
Fail to focus on the new created resource.

**Suggestion:**
Auto focus on the new created files and folders.

**Comment by wwlorey** [comment]
TODO: Verify this matches VS Code behavior

**Comment by wwlorey** [comment]
I wasn't able to reproduce this - new files would automatically focus.

@v-dantch can you still repro?

**Comment by v-dantch** [comment]
Hi @wwlorey , thanks for your response. Verified on the latest nightly build [20191119.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12559), details as below:

For a new created file, it will focus on the new file **editor**.
For a new created folder, it will focus on the blob container/file share **panel** not the particular resource.

Is it necessary and possible to focus on the particular resource?

**Comment by wwlorey** [comment]
Ah I see what you mean. We'll look into this during our next triage

**Comment by wwlorey** [comment]
We decided that this behavior is OK. Nice catch though!
