### ISSUE TITLE
[Suggestion]Update the button from "View Errors" to "View Output"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#509]
**OS:** All
**Build Version:** [20191112.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12368)
**Regression:** Not a Regression

**Repro Steps:**
1. Enable "Azure Storage : Enable View In File Explorer" in User Settings.
2. Create a storage account --> Create a new blob container --> Upload one folder which contains one blob at least.
3. Acquire lease in Azure Storage Explorer for the new uploaded blob --> Delete this folder in File Explorer.

**Actual:**
Pop up an **error** "Errors occurred when deleting '_**resource_name**_' " both from VS Code -Insiders and Azure Storage Extension.
![image](https://user-images.githubusercontent.com/34729092/68746067-c5823e00-0632-11ea-95ce-bb48a06e432b.png)

**Suggestion:**
Update the button from "View Errors" to "View Output". Due to it will take you to "OUTPUT" window after click "View Output" button and there are more error message in "Output" window.
![image](https://user-images.githubusercontent.com/34729092/68746025-a84d6f80-0632-11ea-9684-1bc1c74de2d5.png)

**Comment by wwlorey** [comment]
Thanks for reporting, but we've decided not to fix this one :)
