### ISSUE TITLE
"Don't show again" is confusing when uploading a file

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#51]
![screen shot 2018-02-02 at 11 28 52 am copy](https://user-images.githubusercontent.com/11282622/35751242-a3ffbe40-080c-11e8-8bba-bdadd3cd0485.png)
![screen shot 2018-02-02 at 11 28 52 am](https://user-images.githubusercontent.com/11282622/35751248-a6aaab32-080c-11e8-86b7-e0f8620e945f.png)

Does "Don't show again" mean 'OK, Don't show again" or "Cancel, Don't show again"?

In other repos we fixed it like this:
![screen shot 2018-02-02 at 11 29 41 am](https://user-images.githubusercontent.com/11282622/35751258-af138140-080c-11e8-83fd-2084df7ba9fb.png)

**Comment by StephenWeatherford** [comment]
Thanks for entering, I found it confusing, too.
