### ISSUE TITLE
[Suggestion] Simplify the deploying log message

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#510]
**OS:** All
**Build Version:** [20191112.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12368)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new storage account --> Right click this new storage account --> Select "Deploy to Statics Website...".
2. Select one project to deploy according to the notification --> Check the log message when deploying.

**Actual:**
Display "Deploying to '_**target_file'**_ from '_local_path_' : Deploying xx files to '_**target_file**_' ".
![image](https://user-images.githubusercontent.com/34729092/68748476-74c11400-0637-11ea-92ad-2663b12d3944.png)

**Suggestion:**
Simplify the deploying log message like "Deploying to '_**target_file'**_ from '_local_path_' : xx files".

**Comment by wwlorey** [comment]
Part of #344
