### ISSUE TITLE
Warning on folders in untitled multi-root workspaces

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestorage#515]
If multiple blob containers or file shares are opened in a multi-root workspace, they display this warning:

![Screen Shot 2019-11-19 at 2 20 58 PM](https://user-images.githubusercontent.com/22795803/69196056-3ec1db00-0ae2-11ea-8e14-a89ef2989490.png)

Interacting with these containers/shares works as expected despite the warning. Manually reloading VS Code fixes the problem, but calling the reload command in the extension didn't fix the issue.

Maybe create a flag in the tree items to signify they're done loading?

**Comment by EricJizbaMSFT** [comment]
I tested and this only repro-ed for me on untitled workspaces

**Comment by nturinski** [comment]
🙈 🙉 🙊
