### ISSUE TITLE
Fail to deploy a project to storage account while logging in

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#517]
**OS:** Mac
**Build Version:** [20191201.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12756)

**Repro Steps:**
1. Open a project and create a storage account in VS Code.
2. F1->Azure: Sign Out, F1->Azure: Sign in with Device Code.
3. Click the 'Copy & Open', but not paste the code to the webpage.
4. Right click the project folder in the explorer and select 'Deploy to Static Website...'.
5. Paste the code to the sign in webpage and complete sign in.
6. Check the result in VS Code.

**Expect:**
Show a subscription list.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/69950328-35972c00-152e-11ea-81b3-b3bb19bf0059.png)

**Comment by wwlorey** [comment]
This should work fine if you complete the sign in process then deploy
