### ISSUE TITLE
Do not shift to the File Explorer after selecting "Add to workspace ->Open in current window"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#520]
**OS:** Win10
**Build Version:** [20191202.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12764)
**Regression**: Not a Regression

**Repro Steps:**
1. Enable "Azure Storage : Enable View In File Explorer".
2. Create a storage account --> Create a blob container --> Click "Open in File Explorer". 
3. Select "**Add to workspace**" when asked.
![image](https://user-images.githubusercontent.com/34729092/70036967-b28ada00-15f0-11ea-9bff-c7e779ecb870.png)
4. Back to Azure Storage panel --> Click "Open in File Explorer" again for a same blob container.
5. Select "**Open in current window**".

**Expect:**
Focus should shift to the File Explorer.

**Actual:**
Stay in Azure Storage panel and nothing works.

**Comment by nturinski** [comment]
Cleaning up Will's mess >:(
