### ISSUE TITLE
The error message "Unexpected entry BlobContainerGroupTreeItem" is not very clear 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#523]
**OS:** Win10
**Build Version:** [20191202.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12764)
**Regression:** Not a Regression (for the previous release build )

**Repro **Steps:****
1. Enable "Azure Storage: Enable View in File Explorer.
2. Create a storage account --> Create a blob container --> Click "Open in File Explorer...".
3. Save the workspace locally --> Modified the folders.uri like below:
azurestorageblob:/subscriptions/..../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/.../Blob Containers
4. Re-open the edited workspace in VS Code again --> Pop up an error.

**Expect:**
Display a clear error.
![image](https://user-images.githubusercontent.com/34729092/70039590-2b8c3080-15f5-11ea-9a63-d4c59f88f38a.png)

**Actual:**
Display " Unexpected entry BlobContainerGroupTreeItem ".
![image](https://user-images.githubusercontent.com/34729092/70039683-4bbbef80-15f5-11ea-9686-2536d35c6d26.png)

**Comment by wwlorey** [comment]
I modified the workspace `folders.uri` with an old version of the URI like you provided but I couldn't repro that error. Do you have any more info on how to repro?

**Comment by v-xinda** [comment]
Verified on the latest build [20200116.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13842&view=artifacts&type=publishedArtifacts), there is no error message for now. And it only displays a waring "\<workspacename> Can not resolve workspace folder" in File Explorer like below screenshot:
![image](https://user-images.githubusercontent.com/57662131/72602539-669eb500-3952-11ea-984c-c520d913bdd5.png)

**Comment by wwlorey** [comment]
Thanks for taking another look! That behavior looks good 👍
