### ISSUE TITLE
Deploy static website without deleting all files

### ISSUE THREAD

**Issue by mbondoso** [microsoft/vscode-azurestorage#524]
Is there any chance to deploy static website without deleting all files in the storage?

In my application, we use an internal update website feature that detects new files and forces reload of the website, but we need the old version still there.

**Comment by nturinski** [comment]
We can accomplish this by supporting a setting that allows users to have an "overwrite" deployment instead of deleting everything.

**Comment by wwlorey** [comment]
A setting that accomplishes this called [`deleteBeforeDeploy`](https://github.com/microsoft/vscode-azurestorage/blob/b650a53f6b8a24366027402231d9261f6543f34f/package.json#L823-L827) was just shipped in version 0.11.0.
