### ISSUE TITLE
There are some front-end problems for the conflict error message when creating blob container

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#538]
**OS**: Win10 & Mac
**Build Version:** [20191216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13157&view=results)
**Regression**: Previous Release (0.7.2)

**Repro Steps:**
1. Create a new storage account -->Create a new blob container named "test".
2. Delete the new created blob container "test" --> Create a new blob container named "test" again.
3. Display an error --> Check the error message.

**Expect:**
Display below error.
![image](https://user-images.githubusercontent.com/34729092/70980480-5cd52800-20ee-11ea-8312-b6edd71fa796.png)

**Actual:**
There are some front-end problems.
![image](https://user-images.githubusercontent.com/34729092/70980743-bb020b00-20ee-11ea-8549-a23d760c47bf.png)

**More Info:**
1. This issue doesn't reproduce for file share, queue and table.
2. This issue also reproduces when deleting a blob which has required lease.
![image](https://user-images.githubusercontent.com/34729092/70985797-ad04b800-20f7-11ea-8fb8-3ca652d39870.png)

**Comment by wwlorey** [comment]
Related: https://github.com/Azure/azure-sdk-for-js/issues/6927
