### ISSUE TITLE
Fail to open blob url

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#539]
**OS**: Win10 & Mac
**Build Version:** [20191216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13157&view=results)
**Regression**: Not a Regression

**Repro Steps:**
1. Create a new storage account --> Create a new blob container --> Create an empty blob.
2. Right click the new empty blob --> Select "Copy URL".
3. Ctrl /CMD +Click to open the blob url in Output window.

**Expect:**
Succeed to open the blob url.

**Actual:**
On Windows:
Display "ResourceNotFound".
![image](https://user-images.githubusercontent.com/34729092/70982536-1bdf1280-20f2-11ea-99d1-7f4b229b8404.png)
On Mac:
Display "Unable to open".
![image](https://user-images.githubusercontent.com/34729092/70982584-344f2d00-20f2-11ea-88ff-b5ae16fb41af.png)
Meanwhile, the format of blob url is strange on Mac.
![image](https://user-images.githubusercontent.com/34729092/70982703-6791bc00-20f2-11ea-8882-1fdc9ebdac58.png)

**Comment by wwlorey** [comment]
Fixed by #561. Note: it's ok to see `%2F` in place of `/` in blob, file, and directory URLs.
