### ISSUE TITLE
[Suggestion]Add a command to collapse the Azure Storage Explorer panel

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#542]
**OS:** All
**Build Version:** [20191222.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13295&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. F1 --> Type "Collapse All".
2. Check the result.

**Actual:**
Only display "Search: Collapse All" and there is no such a command for Azure Storage Extension like  "Azure Storage: Collapse All".
![image](https://user-images.githubusercontent.com/34729092/71339935-05243a00-2590-11ea-937f-daa83608cf43.png)

**Suggestion:**
Add a command "Azure Storage: Collapse All".

**Comment by wwlorey** [comment]
This unfortunately looks like a VS Code problem, not something we can fix
