### ISSUE TITLE
Miss "+ Create new Storage Account... Advanced" option in command palette

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#543]
**OS:** All
**Build Version:** [20191222.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13295&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. F1 --> Type and select "Azure Storage: Delete Storage Account...".
2. Prompt to select a storage account to delete --> Check the result.

**Expect:**
Display the existing storage accounts and both 2 creation methods(Basic Creation and Advanced Creation).

**Actual:**
Miss the advanced creation "+ Create new Storage Account... Advanced" option.
![image](https://user-images.githubusercontent.com/34729092/71340572-330a7e00-2592-11ea-9225-c8f9e3b28f41.png)

**More Info:**
This issue also reproduces when deploying a project to static website.

**Comment by EricJizbaMSFT** [comment]
Thanks for filing. To clarify the expected behavior: We want to display both advanced and basic create in all scenarios _except_ when running a delete command (where we don't want to display either)

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing and we have updated it in our side.
