### ISSUE TITLE
Pop up an error when executing "New File" in File Explorer for blob containers

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#545]
**OS:** All
**Build Version:** [20191222.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13295&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Enable "Azure Storage: Enable View In File Explorer".
2. Create a new storage account --> Create a blob container --> Open this blob container in File Explorer.
3. New a folder in File Explorer --> New a file in the new folder --> Update and save the new file.
4. Check the result.

**Expect:**
Succeed to create, update and save the new file in a folder.

**Actual:**
Fail to create and save the file which is in a folder.
![image](https://user-images.githubusercontent.com/34729092/71347028-52120b80-25a4-11ea-92e8-4cdde9296e3a.png)

**More Info:**
1. No error pops up if creating a new file directly in the root folder.
2. This issue doesn't reproduces for file shares.

**Comment by wwlorey** [comment]
I'm not able to repro on the latest [build](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13639&view=results). @v-dantch can you repro?

**Comment by v-dantch** [comment]
Verified on the latest nightly build [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=results), this issue does not reproduce. How about closing it for now?
