### ISSUE TITLE
Display multiple errors when the folders.url is invalid for a blob container

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#546]
**OS:** All
**Build Version:** [20191222.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13295&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Enable "Azure Storage: Enable View In File Explorer".
2. Create a new storage account --> Create a blob container --> Open this blob container in File Explorer.
3. Save the workspace locally --> Set the folders.url as invalid like remove the blob container name.
4. Open the edited workspace in VS Code --> Pop up an error.
5. Check the Output window.

**Expect:**
Pop up one error.

**Actual:**
Display multiple errors.
![image](https://user-images.githubusercontent.com/34729092/71347881-4889a300-25a6-11ea-9914-e2fb4fea0435.png)

**More Info:**
This issue doesn't reproduce for file share.

**Comment by wwlorey** [comment]
I'm having trouble reproducing this issue. When I invalidate the `.code-workspace` file, here's the only warning I see (no error popups)

![Screen Shot 2020-01-02 at 11 46 31 AM](https://user-images.githubusercontent.com/22795803/71688898-a9a73880-2d55-11ea-9704-374e3e850347.png)

Did you open the edited workspace in a fresh VS Code window?

**Comment by wwlorey** [comment]
Per email discussion: I'm waiting on access to the test VM to try and repro this issue
