### ISSUE TITLE
Fail to display the static website with 404 after deploying

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#552]
**OS:** Win10
**Build Version:** [20200105.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13436&view=results)

**Repro Steps:**
1. Create a storage account --> Deploy a project to the static website.
2. Check the result.

**Expect:**
Succeed to deploy and the static website displays well.

**Actual:**
Succeed to deploy, but there displays 404 when browsing the website.
![image](https://user-images.githubusercontent.com/34729092/71808128-ece00f00-30a7-11ea-8dc5-f9d43ef80a69.png)

**More Info:**
This issue also reproduces on the previous release (0.7.2) **for now**. But this issue didn't reproduce when tested the previous release (0.7.2).

**Comment by wwlorey** [comment]
This looks like it was a temporary problem with Azure (especially since a possibly similar [issue](https://github.com/microsoft/vscode-azureappservice/issues/1346) was filed near the same time.) Can't repro so closing for now
