### ISSUE TITLE
Advanced creation should prompt for static site config before creating account

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurestorage#553]
Originally from https://github.com/microsoft/vscode-azurestorage/pull/550#discussion_r362671685

Right now advanced creation will prompt for account, create account, prompt for config, change config. We want it to prompt for account, prompt for config, create account, change config

**Comment by wwlorey** [comment]
Per offline discussion: at some point, static website configuration was removed from advanced create. So add it back in using this order: 

> We want it to prompt for account, prompt for config, create account, change config
