### ISSUE TITLE
Azure static website deployment not working.  Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by jlazlab** [microsoft/vscode-azurestorage#559]
Repro steps:
&lt;Enter steps to reproduce issue&gt;

1. Create storage account (v2, hot, ZRS, Public endpoint -- no other options mostly default)
2. Enable Static website feature (index.html and 404.html set)
3. Deploy from VS Code using Right-click, Deploy Static Website

Action: azureStorage.deployStaticWebsite
Error type: AuthenticationFailed
Error Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:f88a18bf-501e-0033-371d-c76322000000
Time:2020-01-09T18:47:56.7757000Z

Version: 0.7.2
OS: win32

I dont know what I am doing wrong or if the feature is just botched.  There is no real good documentation on it.

**Comment by jlazlab** [comment]
So I went back through and removed the storage account.  I added another accepting all defaults and it worked.  Please update the documentation to reflect this.  There seems to be a lot of confusion as to what can and cannot be used

thanks
jlazlab

**Comment by wwlorey** [comment]
@jlazlab did you create that storage account in the portal? We only support deployments from V2 storage accounts, which is the default if you create a storage account in VS Code
