### ISSUE TITLE
[Suggestion] Enrich the command "Open in Storage Explorer" 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#566]
**OS**: All
**Build Version:** [20200113.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13678&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. F1 --> Type "Open in Storage Explorer" in Command Palette.
2. Check the result.

**Actual:**
Only list "Azure Storage: Open in Storage Explorer".

**Suggestion:**
How about enriching the command with below commands?

- "Blob Container: Open in Storage Explorer".
- "File Share: Open in Storage Explorer".
- "Queue: Open in Storage Explorer".
- "Table: Open in Storage Explorer".
- "Storage Account: Open in Storage Explorer".

**Comment by wwlorey** [comment]
Thanks for the suggestion!
