### ISSUE TITLE
No error pops up when deleting a non-existing storage account 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#568]
**OS**: All
**Build Version:** [20200113.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13678&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Open 2 windows of VS Code --> Select and delete one storage account like "test" in one window.
2. Navigate to another window --> Try to delete the same storage account like "test" again without refreshing this window.
3. Check the result.

**Expect:**
Pop up an error told the users that the special storage account is non-existing.

**Actual:**
No error pops up when deleting a non-existing storage account.

**Comment by EricJizbaMSFT** [comment]
I would close this as by-design. The user got what they wanted (the account was deleted) and there's no further action required on their part - thus a warning seems unnecessary and/or confusing

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing.
