### ISSUE TITLE
The process of "Browse Static Website" will be terminated when executing "Browse Static Website" for a new created storage account

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#582]
**OS:** Windows
**Build Version**: [20200120.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13943&view=results)
**Regression:** Previous Release (0.7.2)

**Repro Steps:**
1. Create a new storage account with advanced creation.
2. Make sure this new account has not been enabled static website.
3. Right click this account --> Select "Browse Static Website".

**Expect:**
1. Prompt to enable the static website.
2. Browse the static website in browser.

**Actual:**
Only prompt to enable the static website. And the process of "Browse Static Website" will be terminated after enabling the static website.

**More Info:**
This issue also reproduces on the candidate [20200114.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13766&view=artifacts&type=publishedArtifacts)

**Comment by wwlorey** [comment]
This is actually by design. If the site isn't configured before a browse, we throw an error and force them to config before clicking browse again 🙂

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
