### ISSUE TITLE
Remove unsued settings azureStorage.blob.showSavePrompt and azureStorage.file.showSavePrompt

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurestorage#592]
![image](https://user-images.githubusercontent.com/5290572/73499998-7a94de80-4376-11ea-978e-fa0c39da9300.png)

This was the old behavior when overwriting files to Azure.  With the new FileSystemProvider, we don't have that confirmation anymore.

@fiveisprime Should we add this back in?  If not, we can remove the setting from the package.json

**Comment by EricJizbaMSFT** [comment]
Personally I would love to get rid of that dialog if at all possible. It just feels so clunky

**Comment by fiveisprime** [comment]
Please don't add that back.
