### ISSUE TITLE
Icons do not reflect theme

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#6]
It's not a HUGE issue because the icons are still visible in both themes, but it would seem to always use the 'light' theme icons. The dark theme icons shouldn't have those white borders
![screen shot 2017-12-06 at 1 40 33 pm](https://user-images.githubusercontent.com/11282622/33686908-3cf01cd0-da8b-11e7-8407-05291fc38dbf.png)![screen shot 2017-12-06 at 1 40 14 pm](https://user-images.githubusercontent.com/11282622/33686910-3e0ab5a8-da8b-11e7-9cac-179ed836f468.png)

**Comment by StephenWeatherford** [comment]
The current icons are all the same, and they're PNGs. Ideally should be using .svgs.
