### ISSUE TITLE
[Suggestion]Add "Deploy" and "View Output" buttons on the notification of creating new storage accounts

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#604]
**OS**: All
**Build Version:** [20200209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14542&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new storage account.
2. There is a notification about creating new storage account.

**Actual:**
The notification disappears after succeeding to create new storage account.

**Suggestion:**
Add "Deploy" and "View Output" buttons on the notification.

**Comment by wwlorey** [comment]
@fiveisprime what are your thoughts on this suggestion?

**Comment by wwlorey** [comment]
Closing after discussing offline. We want to push those deployments to SWAG
