### ISSUE TITLE
Support to copy text on the notifications from Azure Storage Extension with a shortcut key 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#605]
**OS**: All
**Build Version:** [20200209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14542&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new storage account --> Deploy a dist directory to the new storage account.
2. There is a notification about deploying to the new storage account.
3. Right click the notification --> Display "Copy Text" opetion.
![image](https://user-images.githubusercontent.com/34729092/74128792-fca7c180-4c18-11ea-865e-d60cd4232608.png)
4. Try to copy the text with "Ctrl + C" on Windows OS.

**Actual:**
Fail to copy the text of the notification with this shortcut key.

**Suggestion:**
Support to copy text on the notifications with this shortcut key.

**Comment by nturinski** [comment]
This is likely a VS Code issue rather than something that we can resolve.
