### ISSUE TITLE
[Suggestion]Update the icon of "File Shares" node like Azure Portal

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#610]
**OS**: Windows
**Build Version:** [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=artifacts&type=publishedArtifacts)
**Regression**: Previous Release (0.8.0)

**Repro Steps:**
1. Create a new storage account.
2. Check the icon of "File Shares" node.

**Actual:**
It is different from the Azure Portal.

**Suggestion:**
Update the icon of "File Shares" node like Azure Portal.
![image](https://user-images.githubusercontent.com/34729092/74209507-fcfc9700-4cc2-11ea-96d4-a9577ba1b182.png)

**Comment by nturinski** [comment]
While that is what the Portal uses, it doesn't really fit with the other icons and would look awkward in our tree UI.  If the other icons change, we can revisit this issue.
