### ISSUE TITLE
Adding to workspace fails to list the resource in File Explorer when there is a resource with existing name

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#611]
**OS**: Windows
**Build Version:** [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14551&view=artifacts&type=publishedArtifacts)
**Regression**: Not a Regression

**Repro Steps**:
1. Create a storage account --> Create a new blob container named "test"--> Upload or create a blob --> Add this blob container to workspace.
2. Expand the new created storage account --> Create a file share with same name "test" and **different content** --> Add this file share to workspace.
3. Check the result in File Explorer.
 
**Expect:**
Actually we are not sure the expected or correct operation. Below are some suggestions:
1. Display a warning or error to prompt the user that there is an existing resource with same name.
2. The existing resource will be overwrited.

**Actual:**
1. There is no any error or warning to prompt the user that there is a resource with existing name. 
2. Shift to the File Explorer after selecting to add the file share to worksapce.
3. The file share isn't added to the workspace.

**Comment by nturinski** [comment]
This also applies to `Open in Current Window` and `Open in New Window`

@fiveisprime What behavior do you expect here?

**Comment by fiveisprime** [comment]
I would expect a warning that a resource with that name already exists.

**Comment by wwlorey** [comment]
This now works as expected in all three "Open in File Explorer" scenarios. 

For "Open in current window" and "Add to workspace", they display side by side: 
<img width="412" alt="Screen Shot 2020-07-20 at 1 27 54 PM" src="https://user-images.githubusercontent.com/22795803/87983532-614f2e00-ca8d-11ea-9c67-52cd7481a4e4.png">

And "Open in new window", opens each container/share in a new window
