### ISSUE TITLE
Unable to see Azure storage tables

### ISSUE THREAD

**Issue by augcampos** [microsoft/vscode-azurestorage#613]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.openTable
Error type: ERR_INVALID_ARG_VALUE
Error Message: The argument 'file' cannot be empty. Received ''

Version: 0.8.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code - Insiders
Product Version: 1.43.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
normalizeSpawnArguments child_process.js:414:11
Object.spawn child_process.js:547:16
extension.bundle.js:157:126096extension.bundle.js:157:126096
Function.<anonymous> extension.bundle.js:157:125951
extension.bundle.js:157:125780extension.bundle.js:157:125780
i extension.bundle.js:157:125466
Function.launch extension.bundle.js:157:125911
Function.<anonymous> extension.bundle.js:398:822905
fulfilled extension.bundle.js:398:820688
```

</details>

**Comment by nturinski** [comment]
Hi @augcampos 

Thanks for reporting.  Could you provide repro steps so that we can investigate this issue?

**Comment by augcampos** [comment]
Hi there,
I can see the values of the blobs, files but the tables do NOT show the values, and I can´t edit.

**Comment by nturinski** [comment]
I don't think the Azure Storage Extension supports opening and editing tables in VS Code yet.  The command you're using should be opening [Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/).

If you need to manipulate tables, please use Storage Explorer for now and we'll keep this in mind when adding new features to the Storage Extension.  Thanks for using it!

That being said, the error that you're receiving is odd and we should investigate that.

**Comment by augcampos** [comment]
Storage Explorer installed yes, but is not needed for files and blobs( and tables has http(s) API to CRUD )
It was a nice feature :D
