### ISSUE TITLE
Storage Accounts inaccessible because of Private Link crash extension

### ISSUE THREAD

**Issue by cwiederspan** [microsoft/vscode-azurestorage#614]
If I have an Azure Storage Account that's protected by Private Link, and I try and navigate to the Blob Container node in the treeview, it seems to "crash"... Essentially the extension gets stuck with the blue progress bar fast-cycling in the top-left titlebar area. And trying to click on any further nodes in the treeview fails to do anything.

**Comment by nturinski** [comment]
Thanks for reporting @cwiederspan 

I wanted to clarify, but in order to have a private link, would you create a private endpoint?

**Comment by cwiederspan** [comment]
@nturinski Sorry for the delay. I was just testing setting up a Storage account with private link, but I didn't actually create any endpoints to it. Then, from my local laptop, I tried to connect to it from VS Code via the extension. It bombs out at that point. So, the private-ness of it seems to be working, but the extension should probably recover a little more gracefully.

**Comment by wwlorey** [comment]
@cwiederspan could you provide the steps you used to set up a storage account with a private link?
