### ISSUE TITLE
not able to deploy a static app

### ISSUE THREAD

**Issue by mjiotrl** [microsoft/vscode-azurestorage#615]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿<?xml version="1.0" encoding="utf-8"?>
<StorageServiceProperties><Cors/><DeleteRetentionPolicy><Enabled>false</Enabled></DeleteRetentionPolicy></StorageServiceProperties>.

Version: 0.8.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:117127
errorHandler extension.bundle.js:31:228616
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting.  Could you provide repro steps please?  Does this happen consistently?
