### ISSUE TITLE
Can't attach storage account using connection string copied from the extension

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestorage#629]
For non-attached storage accounts, we don't include `DefaultEndpointsProtocol` when copying connection strings and attached accounts expect that (or endpoints for each resource type)

**Comment by nturinski** [comment]
So we do include `DefaultEndpointsProtocol`, but what we don't include is `EndpointSuffix`.  That should fix this and this https://github.com/microsoft/vscode-azurestorage/issues/336
