### ISSUE TITLE
Pop up an error when opening an attached account in Storage Explorer

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#636]
**OS**: Windows
**Build Version:** [20200312.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16152&view=results)
**Regression**: Not a Regression

**Repro Steps:**
1. Drill down from "Attached Storage Accounts" --> "Local Emulator" -->"Blob Containers" --> Click "Start Blob Emulator".
2. Prompt to install Azurite --> Install.
![image](https://user-images.githubusercontent.com/34729092/76496141-564b1800-6473-11ea-82d6-c0c8e7424dea.png)
3. Create a local blob --> Select "Open in Storage Explorer" from the context menu.

**Expect:**
Not sure if it is by design.
1. No error pops up
2. Remove the un-supported actions from the context menu for attached resources.

**Actual:**
Pop up an error "Cannot retrieve storage account id for an attached account".
![image](https://user-images.githubusercontent.com/34729092/76498521-0458c100-6478-11ea-9c98-84a6da4cec03.png)

**More Info:**
This issue also reproduces when downloading a blob file.
![image](https://user-images.githubusercontent.com/34729092/76506659-7a642480-6486-11ea-9e5f-75345d229a67.png)

**Comment by wwlorey** [comment]
As discussed here https://github.com/microsoft/vscode-azurestorage/pull/642 it's not worth changing that many context values to fix this
