### ISSUE TITLE
[Suggestion]Add a confirming dialog when detaching a storage account

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#637]
**OS**: Windows
**Build Version:** [20200312.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16152&view=results)
**Regression**: Not a Regression

**Repro Steps:**
1. Attach a storage account with connection string.
2. Select "Detach Storage Account" from the context menu.

**Actual:**
The attached storage account is been detached directly without confirming.

**Suggestion:**
Add a confirming dialog when detaching a storage account, like there will be a confirming dialog when deleting a storage account.

**Comment by EricJizbaMSFT** [comment]
IMO confirmation dialogs should only be used for destructive actions that can't be un-done. Users can easily just reattach

**Comment by v-dantch** [comment]
Got it.
