### ISSUE TITLE
Do not support to upload local files for command "Upload to Azure Storage..."

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#638]
**OS**: Windows
**Build Version:** [20200312.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16152&view=results)
**Regression**: Not a Regression

**Repro Steps:**
1. F1 -->Type and select "Azure Storage: Upload to Azure Storage...".
2. Check the placeholder .
![image](https://user-images.githubusercontent.com/34729092/76501004-7a5f2700-647c-11ea-9d96-3e7cd603fdcc.png)
3. Browse -->Check the result.

**Expect:**
1. Display a clearer placeholder like "Select files/folders to upload".
2. Support to upload local folders and files.

**Actual:**
Only display the folders to select.
![image](https://user-images.githubusercontent.com/34729092/76501279-f0638e00-647c-11ea-9891-bd96b028d352.png)

**More Info:**
Actually we can upload a file in File Explorer from the file context menu.
![image](https://user-images.githubusercontent.com/34729092/76508976-35da8800-648a-11ea-9b5c-dcc1e1cde81a.png)

**Comment by wwlorey** [comment]
Good suggestion! We're addressing this in https://github.com/microsoft/vscode-azurestorage/issues/623
