### ISSUE TITLE
Storage Explorer can't find newly-created blob container when choosing to open in Storage Explorer

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurestorage#64]
Repro Steps:
1. Expand one Storage account.
2. Create a new blob container then select 'Open Azure Account from Storage Explorer' on context menu for it.

Expect:
It will fucus on the new created blob container in Storage Explorer.

Actual:
Pop up an error massage in Storage Explorer as below.
![error](https://user-images.githubusercontent.com/34729022/35962960-275e9d2c-0cab-11e8-8226-ec1db73e3eab.png)

More Info:
This issue also reproduces on file share.

**Comment by StephenWeatherford** [comment]
@JakeRad @MRayermannMSFT @craxal  When's the plan to fix this? Thx.

**Comment by alexweininger** [comment]
Closing as stale
