### ISSUE TITLE
Opening in File Explorer fails to expand the blob from Local Emulator 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#646]
**OS:** Windows
**Build Version:** [20200313.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16209&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a blob container and a new blob under Local Emulator --> Open the blob in File Explorer.
2. Check the result in File Explorer.

**Expect:**
Succeed to display the blob and it can be expanded.

**Actual:**
1. Display an error "Unable to resolve the workspace folder".
![image](https://user-images.githubusercontent.com/34729092/76598322-e44cf000-64bf-11ea-99a3-c3f3e239dc83.png)
2. Fail to expand with error.
![image](https://user-images.githubusercontent.com/34729092/76598376-fb8bdd80-64bf-11ea-88cf-780bc4eff13b.png)
3. Back to Azure Storage view -->Drill down from Local Emulator --> Blob Containers --> Start Blob Emulator --> blob.
![image](https://user-images.githubusercontent.com/34729092/76598531-4e659500-64c0-11ea-892f-9db023aaea58.png)
4. Navigate to File Explorer --> Refresh --> Succeed to expand and display the blob.
![image](https://user-images.githubusercontent.com/34729092/76598613-794fe900-64c0-11ea-80ce-a5ac17671a77.png)

**Comment by nturinski** [comment]
Let's disable `Open in Current Window` or default to `Open in new window` for opening Local Emulator blobs in File Explorer.
