### ISSUE TITLE
Fail to upload a block blob to the Blob Container under Local Emulator

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#647]
**OS:** Mac
**Build Version:** [20200313.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16209&view=results)

**Repro Steps:**
1. Create a Blob Container under Local Emulator.
2. Right click this blob container->Upload Block Blob...->Select one local file.
3. Check the result.

**Expect:**
Succeed to upload the blob to the Blob Container.

**Actual:**
Display an error "Failed with code 400".
![image](https://user-images.githubusercontent.com/45614674/76601891-cf667000-6544-11ea-9276-928c2ed3196b.png)

**Comment by wwlorey** [comment]
I'm not able to reproduce this, it's possible it was just a transient error. Do you have the Azurite extension installed or were you using the CLI?

**Comment by v-ruizh** [comment]
@wwlorey This issue does not reproduce on the latest build 20200720.1, close it.
