### ISSUE TITLE
Fail to expand the attached storage accounts using key and name for Azure China accounts

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#651]
**OS**: Windows
**Build Version**: [20200314.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16232&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Sign in with Azure China account --> Copy the primary key of one storage account --> Attach this storage account using key and name in Azure Storage Explorer.
2. Expand the attached storage account.

**Expect:**
Succeed to expand the attached storage account.

**Actual:**
Fail to expand the attached storage accounts using key and name.

**More Info:**
There is no "EndpointSuffix" in the primary key.

**Comment by nturinski** [comment]
The primary key is the credential for connecting to the storage account.  It shouldn't include the endpoint suffix.  This is by design.

**Comment by v-dantch** [comment]
Got it. Thanks for your share. 

Meanwhile could you help to share more info about launching the attaching storage accounts using primary key and name in Azure Storage Explorer for Azure China and Azure Germany accounts?
