### ISSUE TITLE
There is no error when saving a blob larger than 4MB

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#655]
**OS:** Windows
**Build:** [20200325.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16690&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Right click a Blob Container under Subscription.
2. Upload a file smaller than 4MB.
3. Edit it, make it larger than 4MB and save.

**Expect:**
Display the notification "Please use Storage Explorer for blobs larger then 4MB".
![image](https://user-images.githubusercontent.com/57662131/77601777-a5e71480-6f46-11ea-84d3-5730a98acf3b.png)

**Actual:**
Saved successfully.
![image](https://user-images.githubusercontent.com/57662131/77601947-2a399780-6f47-11ea-83c9-bf3447d43ad7.png)

**Comment by wwlorey** [comment]
Add an error message if saving a file larger than 4MB

**Comment by wwlorey** [comment]
There is no longer a 4MB limit on blob size (https://github.com/microsoft/vscode-azurestorage/pull/729)
