### ISSUE TITLE
Support to upload files/folders to a blob container/file share from context menu

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#657]
**OS**: Windows
**Build Version:** [20200329.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16909&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Open a project in VS Code --> Right click the project --> Select "Upload to Azure Storage..." from the context menu --> Select one applied subscription --> Select a storage account.
2. Prompt to select resource type : Blob Containers and File Shares.
![image](https://user-images.githubusercontent.com/34729092/77900210-496e5700-72b0-11ea-9d7e-9355c20a57ce.png)
3. Navigate to Azure Storage View --> Check the context menu of one blob container and file share.

**Expect:**
Support to upload one file/folder both for blob containers and file shares.

**Actual：**
Blob containers: support to upload block blob from the context menu.
File shares: do not support to upload one file/folder.
![image](https://user-images.githubusercontent.com/34729092/77900498-b8e44680-72b0-11ea-8c93-0b6895aa4165.png)

**Comment by wwlorey** [comment]
Fixed in https://github.com/microsoft/vscode-azurestorage/pull/775
