### ISSUE TITLE
Display an error when uploading a project to a file share

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#658]
**Build Version:** [20200329.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16909&view=artifacts&type=publishedArtifacts)

**Does this occur consistently?**  Yes
**Repro steps:**

1. Open a project in VS Code --> Right click the project --> Select "Upload to Azure Storage..." from the context menu --> Select one applied subscription --> Select a storage account --> Select File Share.
2. Check the result.

Action: azureStorage.uploadToAzureStorage
Error type: Error
Error Message: Error uploading "c:/Users/VSCodetest/Desktop/dist/static/css/app.d41d8cd98f00b204e9800998ecf8427e.css": The specified parent path does not exist.
RequestId:0c258e96-a01a-0048-077a-065a9a000000
Time:2020-03-30T10:06:35.2481592Z 

Version: 0.9.1-alpha
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code - Insiders
Product Version: 1.44.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:132413
rejected extension.bundle.js:157:131773
processTicksAndRejections task_queues.js:85:5
```

</details>

**More Info:**
1. Succeed to upload the same folder to a blob container.
![image](https://user-images.githubusercontent.com/34729092/77901171-02db1700-7234-11ea-98ce-911907ff9fe1.png)
2. Succeed to upload the special file to a file share.
![image](https://user-images.githubusercontent.com/34729092/77901179-079fcb00-7234-11ea-83d3-87c0cabdbaaa.png)

**Comment by wwlorey** [comment]
@v-dantch did you right-click and select "Upload to Azure Storage..." on a workspace folder like "my_directory" in this example?

<img width="283" alt="Screen Shot 2020-10-14 at 11 38 36 AM" src="https://user-images.githubusercontent.com/22795803/96031205-e7231100-0e11-11eb-9778-17173a9464bc.png">

Or does "project" mean something different in this context?
