### ISSUE TITLE
Pop up an error when clicking "Load More..." from local emulator

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#659]
**OS:** Windows
**Build Version:** [20200330.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16923&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a new blob container from Local Emulator.
2. Open a folder in VS Code --> Upload the folder in Step1 to the new created blob container from Local Emulator.
3. Back to Azure Storage View --> Drill down from Local Emulator --> Blob Containers --> The new created blob container and refresh it.
4. Click the "Load More...".

**Expect:**
Succeed to load more.

**Actual:**
Pop up an error:
Element with id /attachedStorageAccounts/devstoreaccount1/Blob Containers/test0/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd is already registered.
![image](https://user-images.githubusercontent.com/34729092/77981470-a3b4f980-733c-11ea-9107-08dee5e06b39.png)

**More Info:**
There is no button on the error dialog.

**Comment by wwlorey** [comment]
@v-dantch are you using the Azurite extension here or the CLI?

**Comment by v-dantch** [comment]
Hi @wwlorey , yes, I have installed Azurite Extension and both Azurite Queue Service and Azurite Blob Service are running.
![image](https://user-images.githubusercontent.com/34729092/78202319-962b7b00-74c6-11ea-8ddb-d94470abc980.png)

Add more info:
The blob display empty after clicking "Load More...".
![image](https://user-images.githubusercontent.com/34729092/78202399-ca9f3700-74c6-11ea-83ba-324a995491df.png)

**Comment by wwlorey** [comment]
Related: https://github.com/Azure/Azurite/issues/605

**Comment by alexweininger** [comment]
Closing as stale
