### ISSUE TITLE
Could not obtain the primary web endpoint for <storageaccount>

### ISSUE THREAD

**Issue by RADV-INFRA** [microsoft/vscode-azurestorage#660]
Using Azure Government, while deploying static website I get the error "Could not obtain the primary web endpoint for <storageaccount>" - it happens every time. Not sure what other info is needed here.

Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Could not obtain the primary web endpoint for <storageaccount>

Version: 0.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
BlobContainerTreeItem.<anonymous> extension.bundle.js:31:228772
fulfilled extension.bundle.js:31:222469
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
@RADV-INFRA when you deploy, do you create a new storage account?

If you created a storage account using an old version of the extension, that could cause problems.

**Comment by RADV-INFRA** [comment]
This was actually an older storage account that I upgraded to v2. I have not tried yet with a new storage account.

Justin Ngayan | Azure Administrator Associate, MCSA, MCP, VCP-DCV
Sr. Systems Administrator
6518 Meadowridge Rd. | Ste. 100 | Elkridge, MD 21075

P 443.776.1996 | F 1.866.824.8914 | newwave.io<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsecure-web.cisco.com%2F1hWIF5pAZXIbH0vSbINoBfPMW-A0bQvAV3Fdp2pE7ajYcE9ca7S2y87RvG0rDdERCFhmHffJp6Um-AeCPuAWZkvnTwiInBNJKiWV99devNZvG7nZOeuh0-7LPve_WePRe02TwL2fL3cEhuO-mdnbaeTZRhbcZflG6T1R4XP7uNboOjKOtXDGdg2PyKi2JfoHrfuztezy7Ib0AqNxLPAG0nEb75C856wKeRu-t3ZQYzEML_8-26xxRqdtTdjav4l8KWX0zbwQG2_NC5gTfsGOomDlf8_EIo3OaK2O7QvG7-DWAscfyMmP6822LAxZ_j4Z60-52-9XUp_QYpFNZLIGwRB3uo6lFOWxzkXupkbOHGY7CvWXUnckzbgXsZRng3XC4GD1m1CmM4KMN1h0o2MAtVyYCV5M7F0x8INvMXyRY83GeCtB4Zd3v_rCCAWhSWgd1uwS1bODXNxVAvQGmi0MYv9_gm4hXjYnQAI1SZNy-kDOBdav35h8G9fFBiOC_lXwQ%2Fhttps%253A%252F%252Fwww.newwave.io%252F&data=02%7C01%7Cjustin.ngayan%40newwave.io%7C97f1d76334b546e05f6908d7b63edc74%7Ce23fb87b9a87474d9d8191d0af53601d%7C0%7C0%7C637178253418431132&sdata=7URXZyQ9msiaE%2F7hAGPDOcCXt3kZjZZhBnimA3E8NJE%3D&reserved=0>


[cid:image001.png@01D6194D.1F9BF8E0]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FNewWave.Telecom.and.Technologies%2F&data=02%7C01%7Cjustin.ngayan%40newwave.io%7C97f1d76334b546e05f6908d7b63edc74%7Ce23fb87b9a87474d9d8191d0af53601d%7C0%7C0%7C637178253418431132&sdata=kRZ2o4CfJwoSSA7Wh9YmCi6y2PP8Bxlxmm9Z4Bq4CEs%3D&reserved=0>
[cid:image002.png@01D6194D.1F9BF8E0]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsecure-web.cisco.com%2F1OI3OWxI-vLbPr430S2DpvCXVV8gABi4KhUfoKzWKHgYfCGEviQMKXDJ712dycJGVmVODH2DEyjWYUqHJCWMSg5EJ3A8om3CKQc-vUyL4s70FTTS2c_4jiDIUEAwGmdV5rg4GGp5pTWRAhcrsAXu5SQwMo383gNpGh-ZBsFWHj9CXN6OilkmUITGrnkjmTijf2O7JCBbiecIYp7pga5C5pkkP7cxap01rrGqojKzIpAhKtpD0ATRUGJZjKneK4AxxqxdpAc8gIWv5DOjYMwXiMstAogaDIxwKo9Z1XqPJDvq_67QLfmbHTUitsmzc0yvtndSjiWY8adzIiBYmLOVgJPt7roxapS5tbAcjH1cZQn6w8zGAyiqOkHpHpcaOA7A-DvLvL3irijr2WFaxIcrwtYAFCOgXl25lit7oAZ5c1mkf_epgzaiTKNb5MN74FCAXWMNXeECBjhvMrvVKbpQsO34KWod-XE75VLBhOO-9bP9l9JFCWAORa3VA3WC14HK0TGf7fX4nwJTzCeYUqlmAHw%2Fhttps%253A%252F%252Fwww.instagram.com%252Fnewwave_tech%252F&data=02%7C01%7Cjustin.ngayan%40newwave.io%7C97f1d76334b546e05f6908d7b63edc74%7Ce23fb87b9a87474d9d8191d0af53601d%7C0%7C0%7C637178253418441129&sdata=fW3Ds%2Fh9OPdEfgSqebS8zfr74go5qpFyV0oF2eW%2BNaM%3D&reserved=0>
[cid:image003.png@01D6194D.1F9BF8E0]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FNewWave_Tech&data=02%7C01%7Cjustin.ngayan%40newwave.io%7C97f1d76334b546e05f6908d7b63edc74%7Ce23fb87b9a87474d9d8191d0af53601d%7C0%7C0%7C637178253418441129&sdata=zpfyNLslUVTbKvfx%2BRSW%2FMWLAe4dvnLncKbj9aD%2FRTQ%3D&reserved=0>
[cid:image004.png@01D6194D.1F9BF8E0]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fnewwave_technologies&data=02%7C01%7Cjustin.ngayan%40newwave.io%7C97f1d76334b546e05f6908d7b63edc74%7Ce23fb87b9a87474d9d8191d0af53601d%7C0%7C0%7C637178253418451122&sdata=L1Omo%2BJjWO27L2PS3ZniJyoueJM3CGkyu7uWCqTB%2BpY%3D&reserved=0>

**Comment by wwlorey** [comment]
> This was actually an older storage account that I upgraded to v2. I have not tried yet with a new storage account.

I was able to deploy to an upgraded v1 --> v2 account using version 0.11.0 of the extension. Could you try upgrading the extension and seeing if your problem persists? Otherwise this problem is likely related to Azure Government.
