### ISSUE TITLE
Pop up an error notification "No matching resources found." when deploying while logging in

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#661]
**OS:** Win10
**Build Version:** [20200425.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18313&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Sign out.
2. Sign in with Device Code --> Click on "Copy & Open", but don't paste the code into the webpage.
3. Back to Explorer.
4. Right-click on a folder and select "Deploy to Static Website…" --> Display "Waiting for Azure sign-in…".
5. Back to the sign-in page in browser --> Enter the code and complete the sign-in.
6. Back to VS Code.

**Expect:**
No error pops up.

**Actual:**
Pop up an error notification.
![image](https://user-images.githubusercontent.com/57662131/80304220-24093600-87e7-11ea-94dd-562435ae6bc3.png)

**Comment by nturinski** [comment]
This also reproduces if you use `Azure: Sign In`.  The workaround is simple, just deploy again.  But this is a weird bug.  Also, if you aren't signed in and just try to deploy from the File Explorer, this bug doesn't repro (which is also weird.)
