### ISSUE TITLE
what's going on

### ISSUE THREAD

**Issue by yk3lee** [microsoft/vscode-azurestorage#662]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "/Users/alee/GIT_Local/7. MECA/meca-exchange-web/build/asset-manifest.json": Cannot read property 'pipesCount' of undefined 

Version: 0.9.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:132413
rejected extension.bundle.js:157:131773
```

</details>

**Comment by nturinski** [comment]
Hi @yk3lee

Sorry that you're having this problem.  At what point does this error occur?  Does the deployment start at all?

Looking into it, I've seen this error commonly linked to having old versions of Node.js.  Could you check your node version?
