### ISSUE TITLE
VS Code Deploy to static web site Create advanced storage

### ISSUE THREAD

**Issue by vglu** [microsoft/vscode-azurestorage#663]
Does this occur consistently? 
Repro steps:

1. VS Code, right click on folder 
2. Deploy to Static Web site
3. New account advanced  
4. Enter name - press Enter - get error

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48901
b.<anonymous> extension.js:229:179477
extension.js:229:174092extension.js:229:174092
extension.js:229:46175extension.js:229:46175
extension.js:229:44168extension.js:229:44168
extension.js:229:43790extension.js:229:43790
i.find extension.js:229:78283
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
