### ISSUE TITLE
Storage - Tables node not visible for Local Emulator

### ISSUE THREAD

**Issue by snerks** [microsoft/vscode-azurestorage#665]
**Version Info**
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Steps to Reproduce**
Using VSCode to work with an Azure Functions C# Project
Use the Azure Activity to view/manage Storage

**Expected Result**
`Tables` node is visible under `Local Emulator`

**Actual Result**
`Tables` node is not visible under `Local Emulator`

_Note_
_Tables node is visible in Microsoft Azure Store Explorer._

![VsCode Storage](https://user-images.githubusercontent.com/7326391/81184211-0e92c980-8fa8-11ea-8a35-1b44d3232417.png)
![Azure Storage Explorer](https://user-images.githubusercontent.com/7326391/81184230-118dba00-8fa8-11ea-9c4e-71b58c096828.png)

**Comment by nturinski** [comment]
We will add this when Azurite supports Table storage.

**Comment by wwlorey** [comment]
It turns out table support in Azurite is in preview now

**Comment by alexweininger** [comment]
Hi @snerks, this feature has been released in the latest version of the extension https://github.com/microsoft/vscode-azurestorage/releases/tag/v0.15.0 🎉
