### ISSUE TITLE
Better handle "Files above 50MB cannot be synchronized with extensions" error

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#666]
**OS:** Win10
**Build Version:** [20200508.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18973&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Left click on a text file larger than 4MB
2. Verify the extension tells you to use Storage Explorer

**Expect:**
The extension tells you to use Storage Explorer, such as:
![image](https://user-images.githubusercontent.com/62053665/81470935-4c9a2280-9220-11ea-8219-80f71fb6dd73.png)

**Actual:**
Another error notification pops up.
![image](https://user-images.githubusercontent.com/62053665/81469963-bca5aa00-921a-11ea-9d93-fd18ac388c3e.png)

**Comment by wwlorey** [comment]
We don't have the 4MB limitation anymore. But VS Code caps file size for editing files at 50MB: https://github.com/microsoft/vscode/blob/3b99352509cb2bf0cfc65fc567cea100e4a8a279/src/vs/workbench/api/browser/mainThreadDocuments.ts#L255
