### ISSUE TITLE
Succeed to deploy to Static Website after deleting the storage account during deployment

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#667]
**OS:** Win10
**Build Version:** [20200508.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18973&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Open a project in vscode
2. Create a storage account-->Right click this storage account--> Deploy to Static Website-->Select this project
3. Delete this storage account during deployment.

**Expect:**
Fail to deployment.

**Actual:**
Deploy to Static Website successfully without any error.
![image](https://user-images.githubusercontent.com/62053665/81470026-0abaad80-921b-11ea-9a66-facccc8fa5ca.png)

**More info:**
1. Browse to website failed after deployment.
2. Output logs:
Creating resource group "elsatest03" in location "westus"...
Successfully created resource group "elsatest03".
Creating storage account "elsatest0" in location "westus" with sku "Standard_LRS"...
Successfully created storage account "elsatest0".
Querying Azure... Method: listBlobsFlat blobContainerName: "$web" prefix: ""
Deploying to static website elsatest0/$web
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/.cache" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-144x144.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-192x192.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-256x256.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-36x36.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-384x384.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-48x48.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-512x512.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-72x72.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/android-chrome-96x96.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-114x114.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-120x120.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-144x144.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-152x152.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-167x167.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-180x180.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-57x57.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-60x60.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-72x72.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-76x76.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon-precomposed.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-icon.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-1182x2208.png" to "$web"...
Deleting storage account "elsatest0"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-1242x2148.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-1496x2048.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-1536x2008.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-320x460.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-640x1096.png" to "$web"...
### Successfully deleted storage account "elsatest0".
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-640x920.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-748x1024.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-750x1294.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/apple-touch-startup-image-768x1004.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/favicon-16x16.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/favicon-32x32.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/favicon.ico" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/firefox_app_128x128.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/firefox_app_512x512.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/firefox_app_60x60.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/manifest.json" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/favicons-c2a605fbc0e687b2e1b4b90a7c445cdd/manifest.webapp" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/index.html" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/css/app.d41d8cd98f00b204e9800998ecf8427e.css" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/0.0e0ae36daa22771f803e.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/0.0e0ae36daa22771f803e.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/1.87754b4f155e7b5857c2.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/1.87754b4f155e7b5857c2.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/10.43c20f52e64ba797642a.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/10.43c20f52e64ba797642a.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/11.2a796aa5d3d6bd2ce4f3.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/11.2a796aa5d3d6bd2ce4f3.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/2.99e4f0fc2910ea69673e.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/2.99e4f0fc2910ea69673e.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/3.4a14703849f24b2e2a3f.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/3.4a14703849f24b2e2a3f.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/4.645b2cc1a8da676edfd8.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/4.645b2cc1a8da676edfd8.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/5.6ffd9feaaa7c8adc6e60.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/5.6ffd9feaaa7c8adc6e60.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/6.9c990a87b3fdfa33f38f.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/6.9c990a87b3fdfa33f38f.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/7.b7c03b5a0ce8860eefd2.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/7.b7c03b5a0ce8860eefd2.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/8.f7086e0cd9f3e8ade960.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/8.f7086e0cd9f3e8ade960.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/9.9ad93289b6c795c76755.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/9.9ad93289b6c795c76755.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/app.22dbafb6873388a7830d.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/app.22dbafb6873388a7830d.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/manifest.3f71d0c31d0a273998be.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/manifest.3f71d0c31d0a273998be.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/vendor.6900163719948d69d2bd.js" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/js/vendor.6900163719948d69d2bd.js.map" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/logo.png" to "$web"...
Uploading "c:/Users/AzureTest/Desktop/dist/static/rwv-logo.png" to "$web"...
Uploaded to "$web".
### Deployment to static website complete. Primary web endpoint is https://elsatest0.z22.web.core.windows.net/

**Comment by wwlorey** [comment]
This is most likely a race condition that we can't control. Thanks for submitting!

**Comment by v-mengwe** [comment]
Got it. Thanks for your share.
