### ISSUE TITLE
[Unstable] There are two notifications during creating a storage account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#671]
**OS:** Windows
**Build Version:** [20200518.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19591&view=artifacts&type=publishedArtifacts)
Does this occur consistently? No

**Repro Steps:**

1. Right click the applied subscription -->Select 'Create Storage Account…(Advanced)'
2. Enter a name--> Select a resource group--> Select "No"--> Select a location
3. Check the result

**Expect:**
There is only one notification during creating a storage account.

**Actual:**
There are two notifications during creating a storage account.
![image](https://user-images.githubusercontent.com/62053665/82306279-6e01c800-99f1-11ea-96a8-1db67e28cae7.png)

**More info:**
This is an unstable issue, the frequency of occurrence is very low, maybe only one in ten.

**Comment by EricJizbaMSFT** [comment]
@nturinski it's unrelated to the PR you linked. We just have two progress notifications and we need to get rid of one lol:

https://github.com/microsoft/vscode-azurestorage/blob/720b070752e1b201541b25468b5fefa1b5668e49/src/tree/createWizard/storageAccountCreateStep.ts#L27

https://github.com/microsoft/vscode-azurestorage/blob/3ea68d7f2f868555c48b04d0b5395544ed4b1668/src/tree/SubscriptionTreeItem.ts#L77

**Comment by v-mengwe** [comment]
Verified on the latest build 20200826.13, this issue still reproduces for now, I will continue to track this issue.

**Comment by v-mengwe** [comment]
Verified on the latest build 20200926.1, this issue still reproduces for now, I will continue to track this issue.
