### ISSUE TITLE
when I want to open the storage explorer in the visual studio code extension from a table I get an error message

### ISSUE THREAD

**Issue by sandromustermann** [microsoft/vscode-azurestorage#674]
Dear Microsoft Team, 

when I want to open the storage explorer in the visual studio code extension from a table I get the message:
"Cannot retrieve storage account id for an attached account".
I have the newest installs.
Can you help me with this?
Please do not hesitate to contact me in case of questions.

Thank you and Best regards, Sandro

**Comment by nturinski** [comment]
Hi @sandromustermann 

Thanks for reporting. 

 Could you let me know what OS you're using?  Are there any other steps you can think of to help reproduce this?

**Comment by sandromustermann** [comment]
Hi Nathan,
I am using Microsoft Windows 10 Enterprise Version 10.0.18363 Build 18363.
Thank you and Best regards, Sandro


Am Mi., 20. Mai 2020 um 22:45 Uhr schrieb Nathan <notifications@github.com>:

**Comment by nturinski** [comment]
Do you have the account in your subscription?  If so, try to open it in storage explorer from that entry point.

With attached accounts, we aren't able to retrieve the storage account ID necessary to open the resource in storage explorer.  Unfortunately there isn't a way for us to know whether or not this account is attached in storage explorer either, so I'm not sure if there is much we can do about this issue.
