### ISSUE TITLE
Azure Functions: configure static website - from VS code 

### ISSUE THREAD

**Issue by AparnaDesaiUK** [microsoft/vscode-azurestorage#679]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.configureStaticWebsite
Error type: Error
Error Message: Only general purpose V2 storage accounts support static website hosting.

Version: 0.9.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
StorageAccountTreeItem.<anonymous> extension.bundle.js:31:214686
fulfilled extension.bundle.js:31:206644
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @AparnaDesaiUK

I believe your storage account is not compatible with Static Website hosting.  Please create a new storage account through the extension and you should be good to go 👍
