### ISSUE TITLE
Error trying to access Azure Storage

### ISSUE THREAD

**Issue by hanchintim** [microsoft/vscode-azurestorage#680]
Does this occur consistently? 
Repro steps:

1.
2.

Action: api.revealTreeItem
Error type: Error
Error Message: TreeError [azureStorage] Data tree node not found: [object Object]

Version: 0.9.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
U.getDataNode workbench.desktop.main.js:1107:184
U.expand workbench.desktop.main.js:1105:305
processTicksAndRejections task_queues.js:85:5
async expand workbench.desktop.main.js:6245:814
async e.reveal workbench.desktop.main.js:4016:589
```

</details>

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2136

**Comment by nturinski** [comment]
Without any repro steps, there's not a lot of headway into resolving this issue, but we see this infrequently and it shouldn't be blocking since if you try again, it should work.
