### ISSUE TITLE
Creating Azure static website

### ISSUE THREAD

**Issue by rahulmodu** [microsoft/vscode-azurestorage#683]
Does dis occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.configureStaticWebsite
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.0
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902
extension.js:229:54224
extension.js:229:52217
extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53

Also, if you are creating a Static Website, I recommend trying our new (https://github.com/microsoft/vscode-azurestaticwebapps)[Azure Static Web Apps Extension]!  This extension uses Azure's new Static Web App and streamlines deploying a SPA through GitHub Actions.
