### ISSUE TITLE
Error in use

### ISSUE THREAD

**Issue by rodrigoesilva** [microsoft/vscode-azurestorage#684]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.createGpv2Account
Error type: AuthorizationFailed
Error Message: The client 'rodrigo.silva@cloudtarget.com.br' with object id '65715e09-25b5-44fe-8da9-1efcf5b2e7a4' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/cc024908-8d8e-49ef-a084-cd01175a0958/resourcegroups/b3account' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.9.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:398:523821extension.bundle.js:398:523821
retryCallback extension.bundle.js:398:115103
retryCallback extension.bundle.js:157:56179
extension.bundle.js:157:57792extension.bundle.js:157:57792
handleRedirect extension.bundle.js:314:7748
extension.bundle.js:157:54964extension.bundle.js:157:54964
Request._callback extension.bundle.js:31:524641
Request.r._callback.r.callback.r.callback extension.bundle.js:374:5992
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:374:19264
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:374:18054
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
@rodrigoesilva  Thanks for reporting.  You might not have the access rights to create a new resource group.  You can try to right-click your subscription and use the advanced create option to pick the resource group.  You should be able to use an existing resource group to create the storage account in.
