### ISSUE TITLE
Extension does not allow multiple file/folder uploads

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-azurestorage#685]
As a data scientist, I would like to use Azure storage to store either 1 – my data sets (a folder with multiple subfolders with gigabytes of data), and 2 – my trained model (multiple files), such that if you want to create an API in azure based on that ML model, you can just grab it from azure storage.

**Comment by wwlorey** [comment]
Fixed by https://github.com/microsoft/vscode-azurestorage/pull/775
