### ISSUE TITLE
Extension limits upload size to be max 4MB, can't upload larger files

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-azurestorage#686]
As a data scientist, I am almost always dealing with big data/files. Some examples are uploading datasets for training (this could range from gigabytes to hundreds of gigabytes), or uploading your trained model (which could be from hundreds of MB to a gigabyte). It would be nice to be able to upload these files from the extension rather than having to install storage explorer. 

As well, in the codespaces scenario, VS Code is no longer running on the local machine,  its all running on a VM in the cloud, such that you can access the codespace in any browser. So having to install the storage explorer may not always be feasible depending on a data scientist's environment.

**Comment by wwlorey** [comment]
Fixed for uploads in https://github.com/microsoft/vscode-azurestorage/pull/729 and downloads in https://github.com/microsoft/vscode-azurestorage/pull/779
