### ISSUE TITLE
There is an error  when opening an empty file "!@@!@#@$"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#689]
**Build Version:** 20200616.1
Does this occur consistently?  Yes 
**Repro steps:**

1. Create a file share.
2. Create an empty file "!@@!@#@$".

**Expect:**
Succeed to create an empty file and open it.

**Actual:**
There is an error when opening it.
![image](https://user-images.githubusercontent.com/62053665/84861206-1b283880-b0a3-11ea-9864-8c975e6a7b0d.png)

**More info:**
This issue also reproduces when creating a subdirectory and opening it.

Action: azureStorage.editFile
Error type: Error
Error Message: cannot open azurestorage:/file/%21%40#%40%23%24%40%24%3FresourceId%3D%2Fsubscriptions%2F92be7e56-8a60-427c-a3e3-0ebd54a827a1%2FresourceGroups%2Fcti-elsa-storage%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Felsaadv1%2FFile%20Shares%2Ffile. Detail: Unable to read file 'azurestorage:/file/!@#@#$@$?resourceId=/subscriptions/92be7e56-8a60-427c-a3e3-0ebd54a827a1/resourceGroups/cti-elsa-storage/providers/Microsoft.Storage/storageAccounts/elsaadv1/File Shares/file' (Error: Unable to resolve non-existing file 'azurestorage:/file/!@#@#$@$?resourceId=/subscriptions/92be7e56-8a60-427c-a3e3-0ebd54a827a1/resourceGroups/cti-elsa-storage/providers/Microsoft.Storage/storageAccounts/elsaadv1/File Shares/file')

Version: 0.9.1-alpha
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6010:738
processTicksAndRejections task_queues.js:85:5
```

**Comment by nturinski** [comment]
This is a valid file name on Windows and the file does get created successfully.  Seems like this might be a bug in our Virtual File System provider giving VS Code the incorrect file path/not properly encoding it.
