### ISSUE TITLE
Fail to upload a 3.9MB text file to blob container by "Upload Block Blob..."

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#691]
**OS:** Win10
**Build Version:** 20200616.1

**Repro steps:**
Create a blob container --> Right click it --> Select "Upload Block Blob..." --> Select a 3.9MB text file.

**Expect:**
Upload this text file to blob container successfully.

**Actual:**
Upload this text file to blob container failed.
![image](https://user-images.githubusercontent.com/62053665/84876282-a01e4c80-b0b9-11ea-883a-c93e2acb460e.png)

**More info:**
Please get the detailed upload result from images:
![image](https://user-images.githubusercontent.com/62053665/84877517-330bb680-b0bb-11ea-907a-9af607b19edc.png)
![image](https://user-images.githubusercontent.com/62053665/84877423-0fe10700-b0bb-11ea-9073-c07659bc4ca6.png)

**Comment by nturinski** [comment]
Closing in favor of https://github.com/microsoft/vscode-azurestorage/issues/686
