### ISSUE TITLE
Only general purpose V2 storage accounts support static website hosting

### ISSUE THREAD

**Issue by lyesinfo** [microsoft/vscode-azurestorage#692]
Action: azureStorage.configureStaticWebsite
Error type: Error
Error Message: Only general purpose V2 storage accounts support static website hosting.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

**Comment by nturinski** [comment]
Please create a new storage account through the extension.  Every account we create should be V2, and you will be able to configure it as a static website.

But if you're using static websites, might I recommend checking out the https://github.com/microsoft/vscode-azurestaticwebapps extension instead?
