### ISSUE TITLE
400 Error When Uploading Blob Block to Local Emulator

### ISSUE THREAD

**Issue by EvanOman** [microsoft/vscode-azurestorage#693]
Does this occur consistently? Yes
Repro steps:

1. Ensure that Azurite has started
2. Use "Upload Block Blob..." to add a file to the emulated storage

Action: azureStorage.uploadBlockBlob
Error type: 400
Error Message: Failed with code "400".

Version: 0.9.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:141061
extension.bundle.js:31:442161extension.bundle.js:31:442161
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
@EvanOman I wasn't able to reproduce this. Are you still running into it when you use the latest Azurite extension?
