### ISSUE TITLE
Local emulator upload file failing 

### ISSUE THREAD

**Issue by manikantabandaru** [microsoft/vscode-azurestorage#694]
Does this occur consistently?  Yes 
Repro steps:

1. Created local emulator
2. Uploaded a sample file to blob container

Action: azureStorage.uploadBlockBlob
Error type: 400
Error Message: Failed with code "400".

Version: 0.9.0
OS: win32
OS Release: 6.3.9600
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:141061
extension.bundle.js:31:442161extension.bundle.js:31:442161
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
@manikantabandaru Are you using Azurite or the Windows specific Storage Emulator?

If you're using the emulator for Windows, make sure you're using version 5.10

**Comment by manikantabandaru** [comment]
Hi 
I have tried using azurite and faced the said error.
Also i tried with emulator for windows 5.10 also and faced same issue
Windows version is 8.1

**Comment by wwlorey** [comment]
@manikantabandaru I wasn't able to reproduce this error by

1. Making sure the Azurite extension is installed in VS Code
2. Expanding the "Local Emulator" node in the storage view
3. Selecting "Start Blob Emulator"
4. Creating a blob container and uploading a blob via "Upload Files..."

Are you still running into the problem when you follow those steps?
