### ISSUE TITLE
"Deploy to static website" context menu action confusing

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestorage#695]
Easily confused with Azure Static Web Apps. Perhaps rename to "Deploy to Azure Storage static website".

![image](https://user-images.githubusercontent.com/3982077/85306219-0660f180-b463-11ea-9d54-ef97a613c0e4.png)

**Comment by wwlorey** [comment]
@fiveisprime do you have any thoughts on this one?

**Comment by fiveisprime** [comment]
Yeah, we should definitely change that. Honestly, I would be fine with removing it from the file context menu 🙊

**Comment by anthonychu** [comment]
This sounds good. It’s still going to be available in the command palette right? It’s still useful until we can right click publish static web apps. 🙂

**Comment by nturinski** [comment]
TODO: Investigate the telemetry on entry point usage for this command

**Comment by Agendum** [comment]
> TODO: Investigate the telemetry on entry point usage for this command

I use this command for an Azure Storage SPA deployment. If the command is unfortunately removed from the context menu, please leave it in the command palette -- or provide some other alternative to easily deploy a static website to Azure Storage first.
