### ISSUE TITLE
The new created blob contains the contents of the deleted blob rather than empty

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#696]
**OS:** Mac
**Build Version:** 20200623.1

**Repro Steps:**

1. Delete a blob which contains some contents.
2. Create a new blob immediately with the same name.
3. Check the result.

**Expect:**
1. Fail to create a blob and pop up an error if the creating occurs during deleting.
![image](https://user-images.githubusercontent.com/57662131/85517048-758c4080-b631-11ea-9a89-3fd3ce983c8f.png)
2. Succeed to create the blob with empty content if the creating occurs after deleting.

**Actual:**
Succeed to create the blob and the contents are the same as the deleted one.
![image](https://user-images.githubusercontent.com/57662131/85517375-c4d27100-b631-11ea-8051-a6a9cc13ce47.png)

**More info:**
This issue reproduces for "File Shares" node.

**Comment by wwlorey** [comment]
Since it takes time to delete a blob completely, this behavior is expected
