### ISSUE TITLE
Sudden issue when trying to deploy a docs build to a preview site on Azure Storage - an action that's worked hundreds of times till now

### ISSUE THREAD

**Issue by rchrdgrace** [microsoft/vscode-azurestorage#697]
Does this occur consistently?  YES
Repro steps:

1. Select Deploy Static Website
2. Select xtdocsprev..z22.web.core.windows.net

Made minor changes to a single .RST file, build without errors, try to deploy to the preview site and I suddenly start getting these errors!

Thank you for looking into this.

Action: azureStorage.deployStaticWebsite
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'c:\ExperimentToolsDocs\docs\xt\_build\html\_static\css\fonts\Roboto-Slab-Regular.woff'

Version: 0.9.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

**Comment by nturinski** [comment]
@rchrdgrace

Thanks for reporting.  That error seems like the extension doesn't have authorization to access the `.woff` file.  Did you change the directory structure/location or is that a new file that could be potentially causing issues?
