### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by t4r0n** [microsoft/vscode-azurestorage#698]
Does this occur consistently? 
Repro steps:

1.
2.

Action: stat
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54285extension.js:229:54285
extension.js:229:52687extension.js:229:52687
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
propagateAslWrapper async-listener/index.js:504:23
index.js:541:70async-listener/index.js:541:70
glue.js:188:31async-listener/glue.js:188:31
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
As a workaround you could try refreshing the tree using the refresh button in the explorer.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
