### ISSUE TITLE
Failed to view file from file share

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#7]
I can't seem to view any file from a file share:

![screen shot 2017-12-06 at 1 47 08 pm](https://user-images.githubusercontent.com/11282622/33687143-0df6de36-da8c-11e7-8f43-55a874ad8474.png)
![screen shot 2017-12-06 at 1 47 02 pm](https://user-images.githubusercontent.com/11282622/33687145-0f286ed2-da8c-11e7-96dc-f7c5e5e03c57.png)

NOTE: I can download these just fine from Storage Explorer

**Comment by StephenWeatherford** [comment]
For me, .txt files seem to work fine on a file share, but if I click on a binary file (e.g. a PNG), I get:

Opening '1-525.txt' ... Done.
Opening 'slowmem.png' ... Failed.
Error Details: An incorrect number of bytes was read from the connection. The connection may have been closed.

**Comment by JakeRadMSFT** [comment]
@EricJizbaMSFT 
Can you try this again in V0.1.3?

**Comment by EricJizbaMSFT** [comment]
Works now
