### ISSUE TITLE
Display an extra invalid Storage account under the Subscription

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#706]
**OS:** Windows
**Build:** 20200715.1

**Repro Step:**
1. Create a new Storage account.
2. Refresh during the Storage account is creating.

**Expect:**
Display "Creating xxx…" under the Subscription.

**Actual:**
Display an extra invalid Storage account under the Subscription.
![image](https://user-images.githubusercontent.com/57662131/87642953-d1537080-c77c-11ea-843f-0878837f4388.png)

**More Info:**
1. There are two Storage accounts with same name after creating finished.
![image](https://user-images.githubusercontent.com/57662131/87643038-ea5c2180-c77c-11ea-8868-293b4919d452.png)
2. The invalid Storage account will disappear after refreshing.
![image](https://user-images.githubusercontent.com/57662131/87643085-f9db6a80-c77c-11ea-9539-ea00a1e35819.png)

**Comment by nturinski** [comment]
This is kind of expected behavior since the app is still being created at the time of the refresh.  While this is a bug, it's a pretty low-risk scenario and would take some work to fix.
