### ISSUE TITLE
There are multiple "Load More..." in a Blob Container which has one page blob

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#708]
**OS:** Windows 10
**Build Version:** 20200720.1

**Repro Steps:**
1. Create a new blob container --> Create a new blob with name "this/is/a/new/blob.txt".
2. Inspect the blob in Storage Explorer, then create a page blob in this/is/a/new folder.
3. Go back to VS Code and refresh the Azure view --> Drill down the blob this/is/a/new and check the result.

**Expect:**
There is no "Load More...".
![image](https://user-images.githubusercontent.com/45614674/88038580-009d1f80-cb79-11ea-818b-4cec8e086319.png)

**Actual:**
There are multiple "Load More..."
![image](https://user-images.githubusercontent.com/45614674/88038077-4efdee80-cb78-11ea-93bb-c4a31770382b.png)

**Comment by wwlorey** [comment]
@v-ruizh I'm not able to repro this. Please reopen if you run into more "Load More" weirdness
