### ISSUE TITLE
[Suggestion] Add an "Open" action for blob

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#709]
**OS:** Windows 10
**Build Version:** 20200720.1

**Repro Steps:**
Right click one blob and check its context menu.

**Actual:**
There is no "Open" action for blob.
![image](https://user-images.githubusercontent.com/45614674/88041379-e06f5f80-cb7c-11ea-9dbd-24be9c2e4e74.png)

**Suggestion:**
Add an "Open" action for blob.

**Comment by nturinski** [comment]
Could you clarify what you mean by "Open"?  Currently no other nodes have an Open context menu item. There is an "Open in..." action, but that's different from opening the file in VS Code.

**Comment by v-ruizh** [comment]
I mean add an "Open" action to open this blob. Like the action in Storage Explorer.
![image](https://user-images.githubusercontent.com/45614674/88246148-3e5e8d00-cccc-11ea-8f6b-8caf801cf79a.png)
