### ISSUE TITLE
The blob file which created from Azure view doesn't exist in "File Explorer"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#712]
**OS:** Windows 10
**Build Version:** 20200721.3

**Repro Steps:**
1. Expand one blob container and click "Open in File Explorer", it will open it in a new VS Code instance.
2. Create a file from "File Explorer" then refresh the blob container, the file shows in blob container.
3. Create empty blob or upload a file "one" to blob container from Azure view, then refresh the "File Explorer".
4. Check the result.

**Expect:**
The file "one" shows in "File Explorer".

**Actual:**
There is no file "one" shows in "File Explorer".
![image](https://user-images.githubusercontent.com/45614674/88149808-271f9100-cc33-11ea-8824-e910046333e2.png)

**Comment by wwlorey** [comment]
As Eric said [here](https://github.com/microsoft/vscode-azurestorage/pull/840#discussion_r499943538), its doubtful that the file explorer and azure view would be used at the same time
