### ISSUE TITLE
My file went to binary without knowing what I did.  Please help.

### ISSUE THREAD

**Issue by dannnyswiss** [microsoft/vscode-azurestorage#716]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.editFile
Error type: Error
Error Message: cannot open azurestorage:/appliance-configs/SRV-SVAM-IKON.unity.config.json?resourceId%3D%2Fsubscriptions%2F3190d125-e525-4108-b9b6-9a8ed719d274%2FresourceGroups%2Fsnow-commerce-production%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fstorageresortconfigprod%2FFile%20Shares%2Fappliance-configs. Detail: File seems to be binary and cannot be opened as text

Version: 0.9.0
OS: win32
OS Release: 10.0.16299
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6011:738
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
@danSwiss can you confirm that the file isn't somehow corrupted? You can download it using the Azure portal to check this.

**Comment by dannnyswiss** [comment]
Right it was corrupted and we aren't sure how it occurred.  It gave this
option to report the issue.   Issue reports that the file can become
corrupted, please create a warning before saving that my file could become
corrupted when changing it incorrectly.
It is up to you how you want to proceed.  But I suggest you create a way to
lint the file before saving.

**Comment by wwlorey** [comment]
@dannnyswiss thanks for the update. Just to verify - it sounds like you edited and saved the file in the extension before you saw this error. Or did the error occur when you opened the file for the first time?

**Comment by dannnyswiss** [comment]
I saw the error when I wanted to open the file for the first time.

**Comment by nturinski** [comment]
Potentially we could open files considered to be binary.  There seems to be a `acceptTextOnly` property in `IReadTextFileOptions` that is looked for before throwing this error.  That way even if a JSON is corrupt, we'd still be able to open it in the editor.

Related https://github.com/microsoft/vscode-azurestorage/issues/721
