### ISSUE TITLE
While deploy on static website on azure it gives an below error .

### ISSUE THREAD

**Issue by BhushanMehta** [microsoft/vscode-azurestorage#718]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "d:/American Airlines/ePays3/epays3-ui/build/static/js/13.e0011cbc.chunk.js": request to https://epays3npdevuialt2storage.blob.core.windows.net/%24web/static%5Cjs%5C13.e0011cbc.chunk.js failed, reason: getaddrinfo EAI_AGAIN epays3npdevuialt2storage.blob.core.windows.net 

Version: 0.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:132413
rejected extension.bundle.js:157:131773
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
@BhushanMehta, does this error reproduce consistently? And are you able to successfully upload files other than `13.e0011cbc.chunk.js` when deploying?
