### ISSUE TITLE
Add support for Azure Stack

### ISSUE THREAD

**Issue by yatna** [microsoft/vscode-azurestorage#720]
**Current Status** - Storage accounts within subscriptions don't show up.

**Approach** - The problem arises mainly because Azure Stack doesn't support the same API version of azure-arm-storage and azure storage-blob We plan to dynamically load the correct library versions depending on environment. Here the steps -

1. Install all required versions
```
"azure-arm-storage": "npm:azure-arm-storage@^5.1.1-preview",
"azure-arm-storage3": "npm:azure-arm-storage@^3.0.0",
```
2. Determine the environment by looking at the settings.json
3. Use the correct version of library dynamically using if...else... in all files.

**Here is the working PR for reference - https://github.com/microsoft/vscode-azurestorage/pull/699**

**Maintenance** - We only load a different library when the environment is Azure Stack, so functionality for Azure won't be affected in any way. If the version AzureStack supports changes, we only need to update the package.json file.

**Comment by alexweininger** [comment]
Done in https://github.com/microsoft/vscode-azurestorage/pull/905
