### ISSUE TITLE
Deploy to Static Web Site anomaly

### ISSUE THREAD

**Issue by mcorning** [microsoft/vscode-azurestorage#722]
Does this occur consistently? Yes
Repro steps:
1. Restart computer
2. Open VSC
3. Deploy to Static Web Site
4. Nothing happens
5. This trouble report icon appears
6. Deploy to Static Web Site
7. Sign in to Azure
8. Select web site
9. Done

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54285extension.js:229:54285
extension.js:229:52687extension.js:229:52687
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
