### ISSUE TITLE
Static website deployment, throws the below error during deployment from VS Code.

### ISSUE THREAD

**Issue by sekarsadasivamv** [microsoft/vscode-azurestorage#734]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Could not obtain the primary web endpoint for sekarsacctcentralus

Version: 0.9.0
OS: darwin
OS Release: 16.7.0
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
BlobContainerTreeItem.<anonymous> extension.bundle.js:31:228772
fulfilled extension.bundle.js:31:222469
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@sekarsadasivamv please add detailed repro steps
