### ISSUE TITLE
Cannot upload .pptx file to local emulator

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-azurestorage#735]
Does this occur consistently? Yes
Repro steps:

1. Right click one of the Blob containers in the Local Emulator in VS Code. Choose Upload Block Content, and select a file (I used a Powerpoint file "large_file.pptx")
2. Get pop-up: "Cannot retrieve storage account id for an attached account."

Action: azureStorage.uploadBlockBlob
Error type: Error
Error Message: Cannot retrieve storage account id for an attached account.

Version: 0.9.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

I can add that uploading this same file locally works in Microsoft Azure Storage Explorer.

<details>
<summary>Call Stack</summary>

```
AttachedStorageRoot.get storageAccountId [as storageAccountId] extension.bundle.js:31:438553
BlobContainerTreeItem.<anonymous> extension.bundle.js:31:231213
fulfilled extension.bundle.js:31:222469
```

</details>

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurestorage/issues/636

**Comment by wwlorey** [comment]
@Sti2nd I wasn't able to reproduce this error by

1. Making sure the Azurite extension is installed in VS Code
2. Expanding the "Local Emulator" node in the storage view
3. Selecting "Start Blob Emulator"
4. Creating a blob container and uploading a blob

Are you still running into the problem when you follow those steps?

**Comment by Sti2nd** [comment]
@wwlorey I cannot reproduce anymore, either. Must have been fixed, thanks! ❤️ 

When I could reproduce the menu option read "Upload Block Content" and now it reads "Upload Files".
