### ISSUE TITLE
deploy not working

### ISSUE THREAD

**Issue by nadav2150** [microsoft/vscode-azurestorage#744]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureStorage.deployStaticWebsite
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 0.7.1
OS: darwin

**Comment by wwlorey** [comment]
@nadav2150 please add steps to reproduce this issue
