### ISSUE TITLE
[Suggestion] It's better that the cursor in the editor

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#748]
**OS:** Win10
**Build:** 20200826.13

**Repro Steps:**
1. Drill down a Storage account.
2. Right click the "File Shares" node --> Click "Create File Share...".
3. Right click the file share --> Click "Create Empty File...".
4. Check the result.

**Actual:**
The cursor is not in the editor.
![image](https://user-images.githubusercontent.com/57662131/91540931-1c50ce00-e94e-11ea-9725-b5c8b69fa86d.png)

**Suggestion:**
It's better that the cursor in the editor, such as the below.
![image](https://user-images.githubusercontent.com/57662131/91541046-4efac680-e94e-11ea-9624-a4d92a009d72.png)

**More Info:**
This issue also reproduces for the blob container.

**Comment by wwlorey** [comment]
We can see if its possible to focus on the open editor
