### ISSUE TITLE
Exception in upload to azure

### ISSUE THREAD

**Issue by qurixtech** [microsoft/vscode-azurestorage#751]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "/Users/a.martens/Google Drive (qurix.tech@gmail.com)/qurix.tech-GD/quirix.de/NeuesDesign-ubeda/_gsdata_/Icon
": Bad Request - Invalid URL

HTTP Error 400. The request URL is invalid. 

Version: 0.9.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:132413
rejected extension.bundle.js:157:131773
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps
