### ISSUE TITLE
[Suggestion] Keep the message consistently when uploading a file to file share

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#763]
**OS:** All
**Build Version:** 20200903.1

**Repro Steps:**

1. F1 -> Type and select "Upload to Azure Storage..." --> Select one file to upload --> Select a subscription --> Select a storage account --> Select "File Shares" --> Select a file share --> Press "Enter".
2. Check the output logs and notification.

**Actual:**
The message is inconsistent between the notification and the output logs.
![image](https://user-images.githubusercontent.com/62053665/92102435-32a8cf00-ee11-11ea-8bee-70e3ac0c30a4.png)

**Suggestion:**
Keep the message consistently between the notification and the output logs.

**More Info:**
This issue also reproduces for upload a folder to file share.

**Comment by v-mengwe** [comment]
Verified on the latest build 20200909.18, this issue reproduces for now.
![image](https://user-images.githubusercontent.com/62053665/92676620-8d33b500-f354-11ea-9c46-4205bce89141.png)

1. This issue also reproduces when uploading a file to blob container.
2. This issue doesn't reproduce when uploading a folder to file share/blob container.

**Comment by wwlorey** [comment]
This is by design. Since we support multiple file uploads now, it could get cumbersome to display all the file names in the notification
