### ISSUE TITLE
Split uploadToAzureStorage into two separate commands

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestorage#768]
One for files and one for folders. Storage Explorer does this to get around Windows acting up when both `canSelectFiles` and `canSelectFolders` are true.

From https://github.com/microsoft/vscode-azurestorage/pull/760#discussion_r483268963

**Comment by wwlorey** [comment]
Duplicate of https://github.com/microsoft/vscode-azurestorage/issues/623

**Comment by EricJizbaMSFT** [comment]
If this comes up in another PR 6 months from now we're gonna block that PR until it's fixed

![3 strikes](https://media3.giphy.com/media/ORT8ZWCQf9mhSOUgny/giphy-downsized.gif)

**Comment by wwlorey** [comment]
Me @ this issue 

![tumblr_inline_nom5091NNB1r0utx7_500](https://user-images.githubusercontent.com/22795803/92270190-7267c900-ee9a-11ea-9e00-23bd1dfdae93.gif)
