### ISSUE TITLE
The delimiter of URL is "%2F" instead of "/"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#769]
**OS:** All
**Build:** 20200903.17

**Repro Steps:**
1. Create a Storage account and expand it.
2. Create a blob container --> Create a empty blob with a name "this/is/new.txt".
3. Right click the blob and copy URL.
4. Paste it in editor and check it.

**Expect:**
The URL should like this: `https://<account>.blob.core.windows.net/<blobcontainer>/folder1/folder2/.../<blob>`.

**Actual:**
The URL as the below: `https://nicoletest003.blob.core.windows.net/blobtest/this%2Fis%2Fnew.txt`.

**More Info:**
This issue also reproduces for file share.

**Comment by wwlorey** [comment]
This is by design. Related to https://github.com/microsoft/vscode-azurestorage/issues/539#issuecomment-573254545
