### ISSUE TITLE
Pop up a warning when uploading the "dist" folder to a Local Emulator blob container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#770]
**OS:** All
**Build Version:** 20200903.17

**Repro Steps:**

1. F1 --> Type and select "Upload to Azure Storage..." --> Select the "dist" folder to upload --> Select Attached Storage Accounts --> Select Local Emulator --> Select a blob container.
2. Check the result.

**Expect:**
Upload the "dist" folder successfully without any error/warning.

**Actual:**
Pop up a warning.
![image](https://user-images.githubusercontent.com/62053665/92219344-05215b80-eecd-11ea-970c-2c449eb6acc9.png)

**More Info:**

1. This issue doesn't reproduce for a storage account/attached storage account on Mac.
2. This issue also reproduces for a storage account/attached storage account on Windows.

**Comment by wwlorey** [comment]
Can you try uploading those files to a blob container that isn't being emulated? It's possible that that's why the transfer is failing

**Comment by v-mengwe** [comment]
Verified on the latest build 20200909.18, this issue doesn't reproduce for now. But expand the blob container after uploading the "dist" folder to blob container of Local Emulator, there are two extra invalid folders.  
![image](https://user-images.githubusercontent.com/62053665/92708799-fb926a80-f388-11ea-9cc0-ccfd368b9a1e.png)
