### ISSUE TITLE
[Suggestion] Add the clear output logs when uploading a file to blob container/file share

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#772]
**OS:** All
**Build Version:** 20200903.17

**Repro Steps:**
1. Upload a file to one blob container and one file share.
2. Check the output logs.

**Actual:**
The output logs are unclear.
Upload to file share:
![image](https://user-images.githubusercontent.com/45614674/92223933-c17e2000-eed3-11ea-86b7-84ba2c2a21e1.png)
Upload to blob container:
![image](https://user-images.githubusercontent.com/45614674/92224010-d8bd0d80-eed3-11ea-8f72-956886db8f73.png)

**Suggestion:**
Add the clear output logs, such as uploading to blob container/file share "xxx/xxx" from... and Successfully uploaded "xxx/xxx".

**Comment by wwlorey** [comment]
We removed the success log message

**Comment by v-mengwe** [comment]
Verified on the latest build 20201025.1.
The output logs only have "uploading..." when uploading a file to blob container/file share. Sometimes the following occurs: the output logs already show "100%", but there is an uploading notification at the same time-> Not sure whether the upload is complete or not.
![image](https://user-images.githubusercontent.com/62053665/97144496-885d8000-179f-11eb-8507-759da1ad9507.png)

So, it would be better add a success log message/notification after uploading a file.
