### ISSUE TITLE
Remove Local Emulator from the account list when executing create table command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#773]
**OS:** All
**Build Version:** 20200903.17

**Repro steps:**
F1 --> Type and select "Azure Storage: Create Table..." --> Select Attached Storage Accounts --> Check the account list.

**Expect:**
There is no Local Emulator in the account list.

**Actual:**
There is a Local Emulator in the account list.
![image](https://user-images.githubusercontent.com/62053665/92224945-1ec6a100-eed5-11ea-878b-01d511eea900.png)

**More Info:**
This issue also reproduces for Delete Table.../Create File Share.../Delete File Share... commands

Action: azureStorage.createTable
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.9.1-alpha
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
AttachedStorageAccountTreeItem.<anonymous> extension.bundle.js:37:9196
fulfilled extension.bundle.js:37:3145
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
I don't think this is worth fixing because I don't want to unintentionally create problems with selecting "Local Emulator" in other scenarios
