### ISSUE TITLE
[Suggestion] Remove an extra step when uploading to Azure Storage

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#774]
**OS:** All
**Build Version:** 20200903.17

**Repro steps:**

1. Right click a blob container of storage account --> Select "Open in the Explorer" --> Select "Open in the new window".
2. F1 in the opened new window --> Type and select "Upload to Azure Storage..." --> Select "Browse...".

**Actual:**
There is an extra step.
![image](https://user-images.githubusercontent.com/62053665/92227661-2ab46200-eed9-11ea-8d67-277a40e05a83.png)

**Suggestion:**
Remove this extra step and pop up the browse directly.

**More Info:**
This issue doesn't reproduce when uploading to Azure Storage with workspace opening.

**Comment by wwlorey** [comment]
We recently changed our entry points for "Upload to Azure Storage..." With that said, it looks like you're using VS Code remote and "Show Local" is expected there
