### ISSUE TITLE
Cannot list folder contents if a blob with the same name exist on the same level

### ISSUE THREAD

**Issue by amirgr-tr** [microsoft/vscode-azurestorage#776]
OS: Windows 10.0.18363
Version: v0.9.0

*Repro steps:*
1. Mount blob container with [goofys](https://github.com/kahing/goofys/blob/master/README-azure.md) to a linux VM and create a blob in a folder in that container.
2. OR create folders and empty blobs in the same level with the same name.
3. Right click on a blob container of storage account --> Select "Open in File Explorer" --> Select "Open in new window"
4. In the new window click on one of the folders to open

*Actual:*
Before clicking to open a folder
![image](https://user-images.githubusercontent.com/41578628/92310264-3ecd9180-efb5-11ea-95e3-0d23d9370497.png)
After clicking on the folder to open
![image](https://user-images.githubusercontent.com/41578628/92310278-6cb2d600-efb5-11ea-9127-e8b190d60d46.png)

This is how it looks from the Azure Storage Explorer
![image](https://user-images.githubusercontent.com/41578628/92310348-214cf780-efb6-11ea-9393-60b01c6d6bc8.png)
There is a blob file under the environments folder, which cannot be listed from the VSCode extension
![image](https://user-images.githubusercontent.com/41578628/92310369-4e010f00-efb6-11ea-87df-08d2f451998a.png)

*More Info:*
Fails the same way when opening in existing workspace either.

**Comment by wwlorey** [comment]
This is a limitation of VS Code and isn't something we can fix on our end unfortunately. 

<img width="348" alt="Screen Shot 2020-09-09 at 2 42 06 PM" src="https://user-images.githubusercontent.com/22795803/92657988-a3853680-f2aa-11ea-9362-8bd14fb163f8.png">

If this is still causing problems for you, please file an issue on https://github.com/microsoft/vscode
