### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aliciayuting** [microsoft/vscode-azurestorage#791]
Does this occur consistently? 
Repro steps:

1.
2.

Action: api.revealTreeItem
Error type: Error
Error Message: Element with id /subscriptions/ed150bce-3150-4fe4-b9e9-557ade4ccef5/resourceGroups/Cascade/providers/Microsoft.Storage/storageAccounts/blobstoragefordiary is already registered

Version: 0.9.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
m.createAndRegisterTreeNode extensionHostProcess.js:621:840
extensionHostProcess.js:620:542
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by wwlorey** [comment]
@aliciayuting please add steps to reproduce this issue
