### ISSUE TITLE
[Suggestion] Add a "View Output" button in the notification after deploying one project to storage account

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#792]
**OS:** All
**Build Version:** 20200911.6

**Repro Steps:**
1. Deploy a project to storage account.
2. Check the notification after deployment complete.

**Actual:**
There is no "View Output" button in the notification.
![image](https://user-images.githubusercontent.com/45614674/92872488-a9a91d80-f438-11ea-8b30-7f646e8b300e.png)

**Suggestion:**
Add a "View Output" button in the notification.

**Comment by nturinski** [comment]
Since this is just an upload blob command (technically) there isn't that much output compared to App Service or Functions.  I don't think it's necessary to guide the user to the output channel.  The message also doesn't ask the user to view output.
