### ISSUE TITLE
 A text box doesn't pop up to ensure the filename when uploading

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#793]
**OS:** All
**Build Version:** 20200911.6

**Repro Steps:**

1. Right click the blob container --> Select "Upload Files..." --> Select a file --> Click "Upload".
2. Check the result.

**Expect:**
A text box pops up to ensure the filename (may include a path).

**Actual:** 
Upload the file directly without any text box.

**More Info:**
1. This issue also reproduces when uploading a folder.
2. This issue also reproduces for the file share.

**Comment by nturinski** [comment]
Closing in favor of https://github.com/microsoft/vscode-azurestorage/issues/814.  We will use this logic for both single and multi-files that will overwrite this behavior.
