### ISSUE TITLE
The overwrite dialog doesn't pop up when downloading a folder to the path which has a duplicate folder

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#797]
**OS:** Windows 10
**Build Version:** 20200911.6

**Repro Steps:**
Download a folder from blob container/file share to the path which has a duplicate folder.

**Expect:**
The overwrite dialog pops up, like the screen on Mac.
![Screen Shot 2020-09-11 at 4 58 31 PM](https://user-images.githubusercontent.com/45614674/92898889-f00a7680-f450-11ea-9b74-5c7b814f0730.png)

**Actual:**
The overwrite dialog doesn't pop up and it will enter this folder.
![image](https://user-images.githubusercontent.com/45614674/92899166-28aa5000-f451-11ea-9d63-f1500bd9a176.png)

**More Info:**
1. This issue does not reproduce on Mac.
2. This issue does not reproduce if download the folder to the path which has no duplicate folder.

**Comment by wwlorey** [comment]
This is a Windows behavior that we aren't able to control unfortunately
