### ISSUE TITLE
The default name of the downloading .vsix file is different from the uploaded one

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#798]
**OS:** Windows 10
**Build Version:** 20200911.6

**Repro Steps:**
1. Upload a .vsix file to blob container/file share.
2. Right click this uploaded file -> Select "Download..." -> Check the default file name in "Save as" page.

**Expect:**
The default file name is the same as the uploaded one.

**Actual:**
The default file name is ".vsix..vsix".
![image](https://user-images.githubusercontent.com/45614674/92905277-1d0d5800-f456-11ea-9e48-4482fc3ce400.png)

**More Info:**
1. This issue does not reproduce on Mac.
2. This issue does not reproduce for .json/.txt/.png/.ts file.

**Comment by wwlorey** [comment]
It looks like this may be happening because ".vsix" isn't a recognized file extension on Windows. Since this is working as expected for other more standard file extensions, it doesn't seem like high priority

**Comment by jinglouMSFT** [comment]
Try to register vsix with Windows to see if you still see this issue. It'd be a good data point when fixing/no-fixing this issue.  Thanks.

**Comment by v-ruizh** [comment]
This issue does not reproduce on Windows which installed VSIXInstaller.exe. 
![image](https://user-images.githubusercontent.com/45614674/93305717-7b10b580-f831-11ea-94ae-2e249795259c.png)

**Comment by nturinski** [comment]
Closing this as external bug.  We can't control what files the Windows OS will recognize so it's kind of out of our control.
