### ISSUE TITLE
Child folders in file share don't have deep link action

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#8]
I get this context menu on 'emj1201-content', but not on child folders (like data or LogFiles)
![screen shot 2017-12-06 at 1 51 43 pm](https://user-images.githubusercontent.com/11282622/33687316-aa4bfa50-da8c-11e7-830f-55c30cb3417f.png)

Not sure if this is by design

**Comment by StephenWeatherford** [comment]
Won't fix
