### ISSUE TITLE
Succeed to upload the multiple files and folders from recent folder by "Upload Files..."

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#803]
**OS:** Linux
**Build:** 20200911.36

**Repro Steps:**
1. Right click a blob container --> Click "Upload Files..." --> Select multiple files and folders from the **recent** folder to upload.
2. Check the result.

**Expect:**
Can not to select the folder.

**Actual:**
Succeed to upload the multiple files and folders from **recent** folder, but the uploaded folder becomes a file.
![image](https://user-images.githubusercontent.com/57662131/93053872-07d53b00-f69b-11ea-942a-5dc035e51814.png)

**More Info:**
1. This issue also reproduces for file shares.
2. This issue only reproduce when selecting files and folders from the **recent** folder.

**Comment by wwlorey** [comment]
@v-xinda I'm not able to get folders to appear in the "Recent" folder. Only recent files appear there for me. And uploading files from there works as expected. What distro are you using?

**Comment by EricJizbaMSFT** [comment]
I can repro this on Ubuntu 18.04. I opened a folder in VS Code and then it showed up in "Recent"
