### ISSUE TITLE
https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/7-exercise-host-a-static-website-using-a-storage-account error

### ISSUE THREAD

**Issue by einrel** [microsoft/vscode-azurestorage#809]
Does this occur consistently? 
Repro steps:

https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/7-exercise-host-a-static-website-using-a-storage-account - recreate all steps via vscode.

Action: azureStorage.configureStaticWebsite
Error type: Error
Error Message: Only general purpose V2 storage accounts support static website hosting.

Version: 0.10.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
StorageAccountTreeItem.<anonymous> extension.bundle.js:31:211734
fulfilled extension.bundle.js:31:203744
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by wwlorey** [comment]
@einrel I see that the tutorial you linked has you "Select the (storage) account you created earlier". Was that account created in the portal or in VS Code? Storage accounts created in the storage extension should support static website hosting out of the box.

**Comment by einrel** [comment]
@wwlorey The storage was created using the sandbox of cloud shell and I just use the code provided as well. I search the net and saw that lots of modules regarding the AZ-204 is quite outdated already with steps and syntax. They are for updates by Microsoft already, so maybe that is why this error occurred.

**Comment by nturinski** [comment]
Could you please let the Learn squad know and report the issue [here](https://docs.microsoft.com/en-us/learn/support/troubleshooting?uid=learn.advocates.azure-functions-and-signalr.7-exercise-host-a-static-website-using-a-storage-account&documentId=43b12733-be26-a9b8-f492-b7923149571d&versionIndependentDocumentId=72304afc-4e47-2da2-297b-e3000884b7c7&contentPath=%2FMicrosoftDocs%2Flearn-pr%2Fblob%2Flive%2Flearn-pr%2Fadvocates%2Fautomatic-update-of-a-webapp-using-azure-functions-and-signalr%2F7-exercise-host-a-static-website-using-a-storage-account.yml&url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Flearn%2Fmodules%2Fautomatic-update-of-a-webapp-using-azure-functions-and-signalr%2F7-exercise-host-a-static-website-using-a-storage-account#report-feedback)?  We can't actually control what they have on their modules, so it'd be great if you could give them some feedback.
