### ISSUE TITLE
There is no 'Download...' in the context menu for one blob

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#82]
Repro Steps:

1. Create a blob container and create an empty text blob.
2. Right click the text blob and check whether there is 'Download...' in the context menu.

Expect:
Display 'Download...' in the context menu.

Actual:
There is no 'Download...' in the context menu.
![no](https://user-images.githubusercontent.com/34729092/36627886-825583f6-1941-11e8-925f-463af4ee91ba.png)

**Comment by StephenWeatherford** [comment]
Sorry, this is handled by #86. I was writing test cases but should have marked them as "not yet implemented."  I've done that now.
