### ISSUE TITLE
Deploy via Azure Storage extension in VSCode

### ISSUE THREAD

**Issue by Diogo1995** [microsoft/vscode-azurestorage#824]
Hello,

I'm trying to do a deploy via azure storage extension in VS Code (like I always did) and after removing the old files that I had in the static website, it shows the following error:

![Screenshot_1](https://user-images.githubusercontent.com/23064079/94041460-28e80b00-fdc2-11ea-87c2-350fd3782a93.png)

Please help,
Thanks!

**Comment by nturinski** [comment]
Hi @Diogo1995

Sorry for the issue.  Could you tell me how you deleted the old files?  Did you manually delete them yourself?  Whenever you deploy, it should automatically delete the old files.

Either way, it seems like something important was deleted.  If it's an option, I'd suggest just creating a new storage account and trying to deploy it to that.

**Comment by Diogo1995** [comment]
I didn't delete any files, it was an automatic prompt that appeared saying it would delete the old files.
To my knowledge, there was no change in anything.

I even tried deploying another project to another storage and the same happened...

**Comment by nturinski** [comment]
Would it be possible to use an older version of your project?  If this is happening to new storage accounts, maybe there was something that got changed in your project that is preventing the site to spin up?

**Comment by Diogo1995** [comment]
Already tried different projects and to different blobs and still having the same problem... It is deleting the old files without a problem automatically but it isn't deploying the new ones...

**Comment by EricJizbaMSFT** [comment]
@wwlorey can you take a look at this one ASAP? I would guess it's failing to spawn azcopy. I know we have the warning, but still pretty bad if we consistently succeed to delete and fail to upload. Even if you can't fix the root cause, we should find ways to handle errors in this situation more gracefully

@Diogo1995 can you give us some basic info about your situation, including your OS and version of VS Code

**Comment by EricJizbaMSFT** [comment]
Also @Diogo1995 as a workaround, you can downgrade the version of your Storage extension to v0.9.0 while we look into this. From the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), run the "Install Specific Version of Extension..." command: 
<img width="378" alt="Screen Shot 2020-10-09 at 10 41 12 AM" src="https://user-images.githubusercontent.com/11282622/95614921-346f3f00-0a1c-11eb-941a-fdb8321f7f86.png">
<img width="337" alt="Screen Shot 2020-10-09 at 10 41 22 AM" src="https://user-images.githubusercontent.com/11282622/95614928-36d19900-0a1c-11eb-9314-d6eaf84ed35b.png">
<img width="284" alt="Screen Shot 2020-10-09 at 10 41 54 AM" src="https://user-images.githubusercontent.com/11282622/95614934-3933f300-0a1c-11eb-92d4-d1f4b6b2fa18.png">

**Comment by Diogo1995** [comment]
@EricJizbaMSFT 
I'm using Windows 10 64bits,
VS Code i'm using the most recent version (1.49.3).

About downgrading the version, it worked. I can now successfully upload my files. Thanks!
If possible, is there a way to be notified when this is fixed and I could return to the newest version?

Thank you very much!

**Comment by wwlorey** [comment]
@Diogo1995 thanks for the info. Would you be able to verify that you can upload a folder by right clicking on a blob container and selecting "Upload Folder..."? Be sure you're using version 0.10.1 of the extension when giving it a try.

<img width="261" alt="Screen Shot 2020-10-14 at 3 39 01 PM" src="https://user-images.githubusercontent.com/22795803/96052997-80165400-0e33-11eb-8f7b-c8bfc0c314dc.png">

And we'll be sure to let you know when a fix is shipped 👍

**Comment by Diogo1995** [comment]
While trying to upload folder as in the image you sent, I got this error.

![image](https://user-images.githubusercontent.com/23064079/96115705-469b2280-0edf-11eb-8526-635035efff23.png)

Im currently using v0.10.1

![image](https://user-images.githubusercontent.com/23064079/96115796-6a5e6880-0edf-11eb-9036-463d67e1488d.png)

**Comment by Diogo1995** [comment]
@wwlorey is it possible for you to tell me the folder where that executable is created and the name of it? It is possible something like that you are saying is happening...

Thanks

**Comment by Diogo1995** [comment]
@wwlorey we already found that and yes it was the enterprise anti-virus/app-lock that was blocking that from executing.

Thank you very much!
