### ISSUE TITLE
Folder and files aren't supposed to coexist but this can be circumvented via `Upload Files...`

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurestorage#829]
Repro steps:

Only for blobs:
1. Create a file named "1234"
2. Upload Files...
3. When prompted for destination directory, type in "1234"
4. Files will upload, and it appears to be in the root
5. Refresh it, and you will have an invalid tree item
![image](https://user-images.githubusercontent.com/5290572/94861176-ef2f8980-03eb-11eb-9060-9701f4620dc7.png)
6. Open in file explorer, and it appears as a folder AND a file
![image](https://user-images.githubusercontent.com/5290572/94861208-feaed280-03eb-11eb-9065-eba8623fdf52.png)
7. ???
8. $$$$$PROFIT$$$$$

**Comment by wwlorey** [comment]
Lets see what Storage Explorer does

**Comment by wwlorey** [comment]
Storage explorer handles this gracefully 

<img width="673" alt="Screen Shot 2020-11-23 at 2 38 42 PM" src="https://user-images.githubusercontent.com/22795803/100012898-dc508a00-2d88-11eb-824a-2acb0c13c590.png">

**Comment by nturinski** [comment]
Now that's hot 🔥
