### ISSUE TITLE
The containers which name begins with $ don't display in VS Code

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#83]
Repro Steps:
1. Select and expand one storage account which contains the containers which name begins with $ in Storage Explorer.
2. Navigate to the same storage account and check whether the containers which name begins with $ display or not in VS Code .

Expect:
The containers beginning with $ display and they are consistent between Storage Explorer and VS Code. 

Actual:
The containers which name begins with $ don't display in VS Code.
![donot](https://user-images.githubusercontent.com/34729092/36629053-a73a161c-1948-11e8-85ce-2159f9581c4a.png)

More info:
Fail to expand the node which only contains the containers which name begins with $ like below.
![error](https://user-images.githubusercontent.com/34729092/36629072-e84cb07e-1948-11e8-8e49-9c60ab10388f.png)

**Comment by StephenWeatherford** [comment]
This is currently by design, but we should make sure it's documented in the README.

**Comment by StephenWeatherford** [comment]
It's in the README.
