### ISSUE TITLE
Open Azure view after `Upload to Azure Storage...`

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurestorage#831]
Not entirely sold on this, but it feels like I would want to be directed back to the Azure view after uploading my folders (to make sure it uploaded) but I might just feel that way right now because I'm testing and intentionally trying to break the extension lol

**Comment by wwlorey** [comment]
> I might just feel that way right now because I'm testing and intentionally trying to break the extension lol

Lol I agree. Probably something we don't need
