### ISSUE TITLE
Error while uploading the website content to Azure Storage

### ISSUE THREAD

**Issue by hareshbhai** [microsoft/vscode-azurestorage#844]
Does this occur consistently? 
Repro steps:

1.  I successfully uploaded files previously. 
2. This time I restarted my machine and tried to upload the files to Azure Storage again. 

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Entry not found in cache.

Version: 0.10.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:74749extension.js:243:74749
extension.js:243:73137extension.js:243:73137
extension.js:243:72287extension.js:243:72287
i.find extension.js:243:106819
extension.js:243:53526extension.js:243:53526
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by wwlorey** [comment]
Hi @hareshbhai, thanks for filing. As a workaround you could try reloading your window or sign out and then back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
