### ISSUE TITLE
Automatically register Microsoft.Storage provider if it isn't already

### ISSUE THREAD

**Issue by iyashjayesh** [microsoft/vscode-azurestorage#845]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Storage'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.10.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:74264
extension.bundle.js:31:763360extension.bundle.js:31:763360
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Are you able to create a storage account via the Azure Portal?  I think if you do it through the portal once, it should register your subscription to use Microsoft.Storage.

That being said, we should probably automatically try to register the provider if it is not already.

**Comment by nturinski** [comment]
Implement this step in the wizard https://github.com/microsoft/vscode-azuretools/blob/main/ui/src/wizard/VerifyProvidersStep.ts
