### ISSUE TITLE
Display two extra invalid folders after uploading the "dist" folder to a Local Emulator blob container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#847]
**OS:** All
**Build Version:** 20201011.1

**Repro Steps:**

1. Expand the Local Emulator -> Blob Containers -> Right click the blob container -> Select "Upload Folder..." -> Select the "dist" folder to upload.
2. Check the result.

**Expect:**
There is no extra invalid folder.

**Actual:**
There are multiple "Load More..." -> Click the "Load More..." -> Display two extra invalid folders.
![image](https://user-images.githubusercontent.com/62053665/95723482-c8a10680-0ca7-11eb-9b7e-257d8fb6cb2f.png)

**More Info:**
This issue doesn't reproduces after uploading the "dist" folder to a storage account blob container.

**Comment by nturinski** [comment]
Which version of Azurite did you encounter this with?

**Comment by v-mengwe** [comment]
Storage Extension Version : 20201014.1
Azurite Version : 3.9.0
This issue also reproduces for now.
![image](https://user-images.githubusercontent.com/62053665/96068212-0aab9180-0ece-11eb-9efe-94be583ceaf3.png)
