### ISSUE TITLE
Use common error parsing code to get better error messages

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurestorage#85]
e.g.
  async uploadFile(node: IAzureNode<BlobNode>, filePath: string): Promise<void> {
...
azureStorage.BlobService.BlobResult, _response: azureStorage.ServiceResponse) => {
                if (!!error) {
                    let errorAny = <any>error;
                    if (!!errorAny.code) {
                        let humanReadableMessage = `Unable to save '${node.treeItem.blob.name}', blob service returned error code "${errorAny.code}"`;
                        switch (errorAny.code) {
                            case "ENOTFOUND":
humanReadableMessage += " - Please check connection.";

**Comment by StephenWeatherford** [comment]
And this:

            let details: string;

            if (!!error.message) {
                details = error.message;
            } else {
                details = JSON.stringify(error);
            }

**Comment by wwlorey** [comment]
We've already switched to the common error parsing code.
