### ISSUE TITLE
Saving file

### ISSUE THREAD

**Issue by FreVsAlpha** [microsoft/vscode-azurestorage#865]
Does this occur consistently? Yes
Repro steps:
1. Edit (csv) file on storage account.
2. Then try to save it.

Action: writeFile
Error type: 409
Error Message: The blob type is invalid for this operation.
RequestId:183c22c4-c01e-0070-544e-a9f8a0000000
Time:2020-10-23T15:10:56.4195602Z

Version: 0.10.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:143520
extension.bundle.js:67:19841extension.bundle.js:67:19841
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by wwlorey** [comment]
@FreVsAlpha That blob's type may be something other than a block blob which is the only type we support at this time. Was that csv file uploaded to your storage account from the VS Code extension?

**Comment by FreVsAlpha** [comment]
Hi, no, it was uploaded via the storage explorer. But it's indeed of type `Append Blob` (it's a CSV that receives new lines from a Python script). I just wanted to remove some old lines directly via VS Code. Thanks for the feedback.

**Comment by wwlorey** [comment]
Thanks for filing. Please let us know if you run into any more problems
