### ISSUE TITLE
Azure storage extension does not work from a remote vm?

### ISSUE THREAD

**Issue by phfsantos** [microsoft/vscode-azurestorage#868]
Does this occur consistently? yes
Repro steps:

1. ssh into a remote vm
2. try uploading anything to azure storage using the extension.
Expected it to upload or deploy to azure storage
Result: AzCopy Transfer: "Failed"

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: AzCopy Transfer: "Failed".

Version: 0.10.1
OS: linux
OS Release: 5.4.0-1026-azure
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:37:14113
fulfilled extension.bundle.js:37:11751
```

</details>

**Comment by wwlorey** [comment]
Related: https://github.com/microsoft/vscode/issues/110264

**Comment by wwlorey** [comment]
This was fixed in https://github.com/microsoft/vscode/issues/110264. Selecting "show local" was broken in VS Code and that option is no longer shown when uploading files.
