### ISSUE TITLE
Need to know how frequently users hit not supported features (e.g. opening large blobs)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurestorage#87]
If you try to open a large file in storage explorer,  it will give an error saying that's not supported, and give you an option to open it in Storage Explorer. I'd like to add telemetry:

1) How often users hit this type of limitation and why (too large, what size, not block blob, etc)
This should be recorded in the telemetry as an error for the specific action taking place
2) Whether the user chooses to open in Storage Explorer or not
Lower priority, probably needs to be a separate telemetry action, or maybe an additional attribute of the attempted action.
3) Size of blobs users are successfully dealing with

**Comment by wwlorey** [comment]
TODO: Check is the second item is supported
