### ISSUE TITLE
The results are inconsistent when deploying from Explorer and Azure View

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#872]
**OS:** All
**Build Version:** 20201026.9

**Repro Steps:**

1. Create a storage account -> Deploy the "dist" folder to the storage account.
2. Drill down the storage account -> Blob Containers -> $web -> Click "Open in File Explorer..." -> Select "Open in new window".
3. Right click the $web folder in the explorer(in the new opened window) -> Select "Deploy to Static Website via Azure Storage…".
4. Check the result.
5. Right click a storage account in the new opened window -> Select "Deploy to Static Website via Azure Storage…" -> Select "$web" folder.
6. Check the result.

**Expect:**
The results are consistent between step 4 and step 6.

**Actual:**
The results are inconsistent between step 4 and step 6, there are two different errors.
1. Step 4
  ![Screen Shot 2020-10-30 at 3 32 33 PM](https://user-images.githubusercontent.com/62053665/97673800-5746bd80-1ac7-11eb-9ae3-0c3d25c5b351.png)
2. Step 6
  ![Screen Shot 2020-10-30 at 3 23 47 PM](https://user-images.githubusercontent.com/62053665/97673831-6463ac80-1ac7-11eb-9732-87b967373d9c.png)

**Comment by wwlorey** [comment]
> 1. Step 4
> ![](https://user-images.githubusercontent.com/62053665/97673800-5746bd80-1ac7-11eb-9ae3-0c3d25c5b351.png)

We would ideally want to see this error in both cases but right now we don't know if the source folder is an Azure resource when it's selected for upload.

@v-mengwe Would you be able to share the AzCopy log file from step 6? I'm curious to see why its failing
