### ISSUE TITLE
[Codespace] The blob saves automatically after typing some contents

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#875]
**OS:** Win10
**Build Version:** Latest Release

**Repro Steps:**
1. Create a new Storage Account -> Create a blob container -> Create a empty blob.
2. Type some contents in the blob.
3. Check the result.

**Expect:**
The blob doesn't save automatically.

**Actual:**
The blob saves automatically.

**Comment by wwlorey** [comment]
This reproduces when editing "local" files in Codespaces as well. It appears that this was a design choice they made.

@microsoft/vscodeazuretoolsdev @fiveisprime Do y'all think it's worth filing an issue on Codespaces to prevent this behavior? When you're editing a blob this notification pops up every few seconds:
<img width="464" alt="Screen Shot 2020-11-09 at 2 11 25 PM" src="https://user-images.githubusercontent.com/22795803/98602717-caa1b980-2295-11eb-8e2a-4ca5de976227.png">

**Comment by wwlorey** [comment]
There's an autosave setting in VS Code (shoutout to @nturinski for pointing this out) and this is enabled by default in Codespaces.

|VS Code running locally|Codespaces|
|-|-|
|![image](https://user-images.githubusercontent.com/22795803/101837606-28732c80-3af4-11eb-9122-4d5a634e3ef6.png)|![image](https://user-images.githubusercontent.com/22795803/101837624-2f01a400-3af4-11eb-9386-a6be541c4f77.png)|

So users can turn off autosaving if desired.
