### ISSUE TITLE
Deploy to static website with no down time

### ISSUE THREAD

**Issue by JerryYangKai** [microsoft/vscode-azurestorage#880]
Hi, 

I have some concern about static website deployment. I found from code that it will remove all the blobs in $web container and then uploading the local files. The deployment will stop if one blob delete or one file upload return error. My website will broken when the delete process stop and my new files have not upload yet since the deployment has already stop, the only way I can do is deploy it again. Even if there is no error, if you delete it before uploading, there will be a short down time for the website.

My question is, do you have something for me to prevent such downtime or will you decide to optimize the deployment process?

Thanks,
Kai

**Comment by nturinski** [comment]
Would not deleting the blobs automatically on deployment help resolve your issue?

There is a new setting `azureStorage.deleteBeforeDeploy` that you can set to false in your user settings that will not delete your $web container prior to deployment.  However, you will have to manually delete anything that should have been deleted after deployment (such as stale files you aren't using anymore).

**Comment by wwlorey** [comment]
@JerryYangKai We're also tracking smart upload in https://github.com/microsoft/vscode-azurestorage/issues/361 if that would help resolve your issue

**Comment by JerryYangKai** [comment]
Thanks to @nturinski  and  @wwlorey , that is really helpful to me.

I have another question and hope you can help me, I found that the existing batch operations like delete blobs are all serial process. Have you considered becoming a parallel operation?

**Comment by wwlorey** [comment]
@JerryYangKai Thanks for the suggestion. We use AzCopy for more performant uploads/downloads and we should use that for deleting as well. Tracking that issue here: https://github.com/microsoft/vscode-azurestorage/issues/883

Please let us know if you run into any more problems.
