### ISSUE TITLE
Deploying static site fails with :Expecting a valid port number in the range of [0, 65535] in proxy settings

### ISSUE THREAD

**Issue by kenchon** [microsoft/vscode-azurestorage#884]
Does this occur consistently? - **Yes**
Repro steps:

1. Right click build artifact dir and select `Deploy to Static Web Site via Azure Storage ...`
2. Select target resource group and I get following error:

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Expecting a valid port number in the range of [0, 65535] in proxy settings.

Version: 0.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
createProxyAgent extension.bundle.js:515:471164
NodeFetchHttpClient.getOrCreateAgent extension.bundle.js:515:471469
NodeFetchHttpClient.<anonymous> extension.bundle.js:515:472471
step extension.bundle.js:16:2767
Object.next extension.bundle.js:16:2872
fulfilled extension.bundle.js:16:1536
processTicksAndRejections task_queues.js:94:5
```

</details>

My proxy config of VSCode is something like this:
`http://{my_name}%40example.com:{my_password}@my.example.proxy.com:8080`

**Comment by kenchon** [comment]
As a workaround, I tried downgrading Azure Storage extension `v0.11.0` to `v0.9.0` as referred at #871 and it successfully deployed build artifact to blob container. Hope this helps.

**Comment by wwlorey** [comment]
It looks like AzCopy transfers aren't playing nice with proxies since downgrading to 0.9.0 fixed the issue.

**Comment by wwlorey** [comment]
@kenchon can you verify that executing the "Azure Storage: Upload Files..." command in version 0.11.0 produces the same error for you?
