### ISSUE TITLE
Working on deployment

### ISSUE THREAD

**Issue by kazakov-yury** [microsoft/vscode-azurestorage#888]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Could not find $web blob container for storage account "devkeychainissuerapp"

Version: 0.11.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:515:401725extension.bundle.js:515:401725
fulfilled extension.bundle.js:515:399888
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by wwlorey** [comment]
@kazakov-yury did you create that storage account in the VS Code extension? It may be an unsupported type of storage account if it was created elsewhere (only GPv2 accounts are supported for static websites)

**Comment by kazakov-yury** [comment]
Yes, I am trying to implement a pipeline from Git to Azure storage.
Visual Studio Code looks more or less but Azure pipelines...
Many problems but I am going step by step.

**Comment by wwlorey** [comment]
@kazakov-yury can you try creating a new storage account for this using the VS Code extension? This can be done by clicking the "+" button in the extension:

<img width="248" alt="Screen Shot 2020-12-02 at 11 13 41 AM" src="https://user-images.githubusercontent.com/22795803/100907075-bf9a0d80-347e-11eb-9fae-eb81e6496b90.png">
