### ISSUE TITLE
There is no "load more" after uploading 100 files for a blob container of Local Emulator

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#890]
**OS:** Win10
**Build Version:** 20201129.1

**Repro Steps:**

1. Expand "Local Emulator" node.
2. Right click the Blob Containers --> Create a new blob container --> Upload 100 files to it --> Refresh.
3. Check whether display the "Load more".

**Expect:**
Display the "load more" after uploading 100 files.
![image](https://user-images.githubusercontent.com/57662131/100584964-c4987900-3327-11eb-9a80-75c11170bccb.png)

**Actual:**
There is no "load more" after uploading 100 files.

**More Info:**
This issue doesn't reproduce for the attached storage accounts or common storage accounts.

**Comment by nturinski** [comment]
Tracking this issue here: https://github.com/microsoft/vscode-azurestorage/issues/659

Azurite handles the load blobs response differently from Azure which is what's causing this bug.
