### ISSUE TITLE
Can't select subscriptions

### ISSUE THREAD

**Issue by sofiaaaaaa** [microsoft/vscode-azurestorage#891]
Issue Type: <b>Bug</b>

Can't select subscriptions.

No subscriptions were found. Set up your account at https://azure.microsoft.com/en-us/free/.

Extension version: 0.11.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 5|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nturinski** [comment]
Hi @sofiaaaaaa Are there any special configurations/permissions with it?  Is it a corporate subscription that are you given access to?

**Comment by sofiaaaaaa** [comment]
I signed in with my azure free account at first on my vscode on my macOS, at first it works. but I tried to signed in with my company aaccount  on azure website, and than the "Key" icon has disappeared on the vscode. After that I can't connect with 
any of azure accounts. Even I tried remove vscode program and reinstall again, it doesn't works. Also I removed my cache folder for vscode but it no use.

**Comment by nturinski** [comment]
The key icon has disappeared, but is there anything in the tree view?  Does it look anything like this?

![image](https://user-images.githubusercontent.com/5290572/101069839-5fbf6780-354f-11eb-8e5f-dbd6d694ad0e.png)

**Comment by sofiaaaaaa** [comment]
![image](https://user-images.githubusercontent.com/36926568/101105131-2438a200-3610-11eb-96a8-844262786519.png)
Yes, it same as me in my Vscode.

**Comment by nturinski** [comment]
If you click on Select Subscriptions... does a window like this pop up at the top of your screen?

![image](https://user-images.githubusercontent.com/5290572/101111295-b9478680-358f-11eb-9b4a-01e220f0f994.png)

**Comment by sofiaaaaaa** [comment]
No... not at all.. In my case, it open a popup on right-bottom side. 
It shows me the below message.. 

"No subscriptions were found. Set up your account at https://azure.microsoft.com/en-us/free/."


![image](https://user-images.githubusercontent.com/36926568/101111666-fdce3300-361e-11eb-8bf7-b58c41552fb5.png)

**Comment by nturinski** [comment]
This is a company subscription?  Can you confirm that you're able to access the subscription in the Azure Portal?

Is the email provided in the screenshot what you normally use to access your company subscription?   

If that's not correct, you'll need to sign out of your current account.  If you press F1 > Type 'sign out', you should see the following:

![image](https://user-images.githubusercontent.com/5290572/101114646-c7e56c00-3596-11eb-9412-800dcb03247b.png)

**Comment by sofiaaaaaa** [comment]
Thank you. That was simple....
