### ISSUE TITLE
[Codespace] Downloading append blob or page blob triggers to launch or install Storage Explorer - can't in Codespace

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/vscode-azurestorage#896]
There are places in our code where we ask users to use or install Storage Explorer. We need to disable or remove the UI when the extension is run on Codespace.  

Repro Steps:
1.  Preparation: In Storage Explorer upload an append blob. You can create these by uploading in Storage Explorer and choose to upload as an append blog.
2. Once the blob is uploaded, go to the Codespace Storage extension treeview, refresh the UI so you can see the blob that was just uploaded
3. Right click on the blob to bring up the context menu for download
4. In the command palette select the location where you want to download the blob, then select OK
5. You will get an info window pop up at the lower right corner:
![image](https://user-images.githubusercontent.com/10081483/101111535-3d017300-3590-11eb-9857-df0c808fb9c6.png)
6. Click on the "Open Resources in Storage Explorer button"
7. You will be prompted again:
![image](https://user-images.githubusercontent.com/10081483/101111635-70440200-3590-11eb-9575-2bbfb07fb204.png)
8. Click on the "Download" button, nothing will happen

Since VS Code manages to install the extension from within the VS Code UI, I am not sure if they provided any API's for us to install Storage Explorer from clicking the "Download" button in step 8.  If no, we probably should stop at Step 5, but still need a way to tell the user to use Storage Explorer somewhere else.  

We could also consider supporting page blob and append blob at some point.

**Comment by wwlorey** [comment]
Tracking page and append blob support in https://github.com/microsoft/vscode-azurestorage/issues/897 and https://github.com/microsoft/vscode-azurestorage/issues/867
