### ISSUE TITLE
Fail to open a File Explorer with an error "Invalid uri" after opening an invalid workspace

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#899]
**OS:** Win10/Mac
**Build Version:** 20201206.1

**Repro Steps:**

1. Expand a blob --> Click "Open in File Explorer..." --> Open in current window.
2. Navigate to File Explorer --> File --> Click "Save Workspace As..." --> Save the workspace locally.
3. Open the workspace and edit it --> Save the edited --> Open the workspace in VS Code --> displays a warning "<workspacename> Unable to resolve workspace folder" in File Explorer . 
4. F1 --> Click "Upload Folder...".
5. Check whether open a File Explorer to choose the folder.

**Expect:**
Open a File Explorer to choose the folder like below.
![image](https://user-images.githubusercontent.com/57662131/101335035-9bda2b80-38b3-11eb-9ca4-a0f5458e441a.png)

**Actual:**
Fail to open a File Explorer with an error.
![uploadfolder](https://user-images.githubusercontent.com/57662131/101335425-26228f80-38b4-11eb-8ea6-4130c9989684.gif)

**More Info:**
This issue doesn't reproduce when uploading files.

**Comment by nturinski** [comment]
Are you running this in WSL or Codespaces by chance?

**Comment by v-xinda** [comment]
@nturinski  Run the regular tests normally in VS Code, rather than in WSL or Codespaces.

**Comment by nturinski** [comment]
We should ensure that the folder exists before we attempt to open it through VS Code.

**Comment by v-mengwe** [comment]
**OS:** Win10
**Build Version:** 20210316.1

**Repro Steps:**

1. Expand a blob -> Click "Open in File Explorer..." -> Open in new window.
2. Right click a storage account in the new window -> Click "Deploy to Static..." -> Click "Browse...".
3. Check whether open a File Explorer to choose the folder.

**Actual:**
File Explorer does not open.

**More Info:**
There is an error after changing the path.
![str](https://user-images.githubusercontent.com/62053665/111445876-c9eac980-8746-11eb-8c6e-5330091ff465.gif)
