### ISSUE TITLE
Diagnostics tables and $logs blob containers are not displayed

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurestorage#9]
I have these displayed in Storage explorer:
![screen shot 2017-12-06 at 1 56 47 pm](https://user-images.githubusercontent.com/11282622/33687579-6d3a3252-da8d-11e7-979d-6b960291afe4.png)

But only this displayed in VS Code:
![screen shot 2017-12-06 at 1 56 41 pm](https://user-images.githubusercontent.com/11282622/33687565-631fd344-da8d-11e7-8ab4-9a3525dca317.png)

**Comment by StephenWeatherford** [comment]
Likewise blob $logs containers are not displayed:

![image](https://user-images.githubusercontent.com/6913354/33747794-df70c010-db79-11e7-9542-cdf247962dbf.png)
![image](https://user-images.githubusercontent.com/6913354/33747801-e75e9fcc-db79-11e7-9786-f28a0bb08e9d.png)

**Comment by devtrends** [comment]
Many users will see this omission as a positive thing. If you are not interested in them, then they merely serve as clutter, particularly as they are the first thing in the list. I would prefer one of the following options:

* Put then in all in a folder ($metrics or similar) so they only take up one 'space' in the list by default
* Add a setting to allow them to be hidden
* Put them at the end of the list

**Comment by StephenWeatherford** [comment]
Given the comment from @devtrends, as well as the intended scope for this extension (#75), I'm closing this issue as something we won't do.  Thanks.
