### ISSUE TITLE
Visual Studio Deployemnt failure

### ISSUE THREAD

**Issue by clr-bb** [microsoft/vscode-azurestorage#906]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: AzCopy Transfer: "Failed".

Version: 0.11.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:37:15387
extension.bundle.js:37:13040
n extension.bundle.js:37:12726
handleJob extension.bundle.js:37:14031
Object.<anonymous> extension.bundle.js:37:15435
fulfilled extension.bundle.js:37:12794
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
