### ISSUE TITLE
AzCopy Transfer: "Failed".

### ISSUE THREAD

**Issue by DII-dsward** [microsoft/vscode-azurestorage#909]
Does this occur consistently? 
Repro steps:

1. Add storage account extention
2. Sign in with onmicrosoft account
3. Add file to container
4. Deploy to static website on container

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: AzCopy Transfer: "Failed".

Version: 0.11.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:37:15387extension.bundle.js:37:15387
extension.bundle.js:37:13040extension.bundle.js:37:13040
n extension.bundle.js:37:12726
handleJob extension.bundle.js:37:14031
Object.<anonymous> extension.bundle.js:37:15435
fulfilled extension.bundle.js:37:12794
runNextTicks task_queues.js:59:5
listOnTimeout timers.js:501:9
processTimers timers.js:475:7
```

</details>

**Comment by wwlorey** [comment]
@DII-dsward were you able to successfully upload a file to your blob container? 

I'm wondering if this is a problem with AzCopy which handles file transfers or with the type or format of the files you were attempting to upload.

**Comment by DII-dsward** [comment]
I had to create a blank file in the storage account, then refresh my connections in vscode so it would see the file in the storage account. From there I could make changes.

**Comment by wwlorey** [comment]
Thanks for the info. Are you able to successfully upload a file to your blob container using the "Upload Files..." command? 

<img width="411" alt="Screen Shot 2020-12-30 at 1 52 23 PM" src="https://user-images.githubusercontent.com/22795803/103377918-8fea1f80-4a95-11eb-932a-00efe17d4db2.png">

**Comment by DII-dsward** [comment]
Is that standard practice to need to upload the file even though I’m saving it to the blob container? To be honest I had not tried that.

**Comment by wwlorey** [comment]
In order to get a blob onto a blob container you have to upload it (at least that's the method we have in the extension.)

If you are able to successfully upload an arbitrary file to your blob container we can rule out some reasons why this issue is coming up.
