### ISSUE TITLE
Nodes should be renamed to tree items

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurestorage#91]
BlobNode/etc are actually tree items and should be named that way to avoid confusion.

**Comment by EricJizbaMSFT** [comment]
Mostly fixed in https://github.com/Microsoft/vscode-azurestorage/pull/230, but I guess still need to rename the files themselves

**Comment by wwlorey** [comment]
Fixed in https://github.com/microsoft/vscode-azurestorage/pull/532
