### ISSUE TITLE
uploading issue

### ISSUE THREAD

**Issue by uaahacker** [microsoft/vscode-azurestorage#912]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error deleting blob "assets/css/underconsribbon.css" : request to https://oakressstatic.blob.core.windows.net/%24web/assets%2Fcss%2Funderconsribbon.css failed, reason: getaddrinfo EAI_AGAIN oakressstatic.blob.core.windows.net

Version: 0.11.0
OS: linux
OS Release: 5.8.0-33-generic
Product: Visual Studio Code - Insiders
Product Version: 1.53.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
BlobContainerTreeItem.<anonymous> extension.bundle.js:31:141901
rejected extension.bundle.js:31:135142
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
