### ISSUE TITLE
Unspecified error downloading csv blob

### ISSUE THREAD

**Issue by alanflanders-teck** [microsoft/vscode-azurestorage#915]
Does this occur consistently? Yes
Repro steps:
1. From the Azure storage extension, right click on a csv file in a blob container and select download
2. Select a valid path using "Browse"

Shows it is downloading and then get error:
"AzCopy Transfer: Failed. Source: Azure Storage (Extension)

Note that I'm am using SSH to remote develop on a deployed Azure ML VM.

Action: azureStorage.download
Error type: Error
Error Message: AzCopy Transfer: "Failed".

Version: 0.11.0
OS: linux
OS Release: 4.15.0-1100-azure
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:37:15387
extension.bundle.js:37:13040
n extension.bundle.js:37:12726
handleJob extension.bundle.js:37:14031
Object.<anonymous> extension.bundle.js:37:15435
fulfilled extension.bundle.js:37:12794
```

</details>

**Comment by wwlorey** [comment]
@alanflanders-teck Are you browsing to a download path on your local machine or on the remote VM?

**Comment by alanflanders-teck** [comment]
The remote VM; Linux path running VS Code on Windows.

**Comment by wwlorey** [comment]
@alanflanders-teck I'm not able to reproduce this on a Data Science VM (Ubuntu 18.04) connected via remote SSH in Windows.

Does this problem persist for any file you attempt to download or is it just that CSV file?

**Comment by wwlorey** [comment]
Also is it possible the extension doesn't have write permissions for the directory you selected?
