### ISSUE TITLE
Detect if libsecret-1-dev is installed prior to running AzCopy commands

### ISSUE THREAD

**Issue by robidas** [microsoft/vscode-azurestorage#917]
Does this occur consistently?  Yes
Repro steps:

1. Follow the steps documented at https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/7-exercise-host-a-static-website-using-a-storage-account
2.Do all steps up to and including "Deploy the web application to Azure Storage". This is the point where the failure occurs.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: AzCopy Transfer: "Failed".

Version: 0.11.0
OS: linux
OS Release: 4.4.0-19041-Microsoft
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:37:15387
extension.bundle.js:37:13040
n extension.bundle.js:37:12726
handleJob extension.bundle.js:37:14031
Object.<anonymous> extension.bundle.js:37:15435
fulfilled extension.bundle.js:37:12794
```

</details>

**Comment by wwlorey** [comment]
@robidas are you using WSL or Remote SSH? Or is linux your host OS?

**Comment by robidas** [comment]
WSL

Ubuntu 20.04.1 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)
running on a Win10 pro guest vm, which in-turn is running on a win 10 pro hyper-v host

________________________________

**Comment by wwlorey** [comment]
@robidas You can fix this by installing `libsecret-1-dev` in WSL:

```bash
sudo apt update
sudo apt install libsecret-1-dev
```

It looks like the packages installed by default in Ubuntu 20.04 on Windows are pretty minimal. This package appears to be included in standard Ubuntu.
