### ISSUE TITLE
[Suggestion] It would be better to change the button from "Install Azurite" to "View in Marketplace" when prompting to install Azurite extension

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#928]
**OS:** Win10
**Build Version:** 20210206.4

**Repro Steps:**

1. Make sure there is no Azurite extension installed.
2. Expand Local Emulator -> Blob Containers -> Click "Start Blob Emulator".
3. Click "Install Azurite" button in the dialog.

**Actual:**
It navigates to Azurite extension page in marketplace, not install the extension directly.
![image](https://user-images.githubusercontent.com/62053665/107140431-ca7c8d00-695c-11eb-96f4-03323c34ff26.png)

**Suggestion:**
It would be better to change the button from "Install Azurite" to "View in Marketplace" when prompting to install Azurite extension.

**Comment by nturinski** [comment]
Will be fixed by https://github.com/microsoft/vscode-azurestorage/issues/929
