### ISSUE TITLE
[Suggestion] It would be better to add hyperlink to warning for using Azurite extension

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#929]
**OS:** Win10
**Build Version:** 20210206.4

**Repro Steps:**

1. Make sure there is no Azurite extension installed.
2. Expand Local Emulator -> Right click the "Blob Containers" node -> Select "Create Blob Container...".
3. Check the result.

**Actual:**
There is an error "...reason: connect ECONNREFUSED 127.0.0.1:10000".
![image](https://user-images.githubusercontent.com/62053665/107140831-e2a1db80-695f-11eb-88d1-e6dc9a87f5b7.png)

**Suggestion:**
It would be better to add hyperlink to warning for using Azurite extension, such as:
![image](https://user-images.githubusercontent.com/62053665/107141539-4201ea80-6964-11eb-92d6-9dbfb23db246.png)

**More Info:**
This issue also reproduces for the "Queue" node of Local Emulator.
![image](https://user-images.githubusercontent.com/62053665/107140892-4c21ea00-6960-11eb-954e-cf470f4963c3.png)

**Comment by wwlorey** [comment]
If you expand "Blob Containers" and click "Start Blob Emulator" (without Azurite installed) a notification to install Azurite is shown.

![image](https://user-images.githubusercontent.com/22795803/107264405-cb163180-69f7-11eb-87c0-de5708755c70.png)

![image](https://user-images.githubusercontent.com/22795803/107264428-ce112200-69f7-11eb-81e7-f73fca6d64b0.png)

But I think it's useful to throw a more helpful error if you try to create a blob container without starting the emulator.
