### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by jeevitha-jr** [microsoft/vscode-azurestorage#935]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error deleting blob "assets/web/images/moneyIcon.svg" : request to https://admindashboardflutter.blob.core.windows.net/%24web/assets%2Fweb%2Fimages%2FmoneyIcon.svg failed, reason: getaddrinfo EAI_AGAIN admindashboardflutter.blob.core.windows.net

Version: 0.11.0
OS: linux
OS Release: 4.15.0-133-generic
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
BlobContainerTreeItem.<anonymous> extension.bundle.js:31:141901
rejected extension.bundle.js:31:135142
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
