### ISSUE TITLE
Get Select Subscription while I am already have azure account

### ISSUE THREAD

**Issue by mca-pradeep** [microsoft/vscode-azurestorage#940]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.attachStorageAccount
Error type: Error
Error Message: Storage Account "staticwebcofee" is already attached.

Version: 0.11.0
OS: linux
OS Release: 5.4.0-65-generic
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
AttachedStorageAccountsTreeItem.<anonymous> extension.bundle.js:310:104593
fulfilled extension.bundle.js:310:101996
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by wwlorey** [comment]
@mca-pradeep is your storage account "staticwebcofee" not showing up as attached? The extension appears to detect that it is already attached.
