### ISSUE TITLE
Open in File Explorer opens in VS Code

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-azurestorage#941]
The "Open in File Explorer" option on a container opens a new VS Code window instead of the (Windows) File Explorer.

Azure Storage extension: 0.11.0
VS Code: 1.53.2

**Comment by wwlorey** [comment]
Hi @Sti2nd, the "File Explorer" in that command refers to VS Code's file explorer. You can download blobs if you wish to open them in the Windows file explorer.

![image](https://user-images.githubusercontent.com/22795803/108744016-4db9e900-74ee-11eb-811d-ef97f4bcd5bd.png)

**Comment by Sti2nd** [comment]
Ok, thanks for clarifying ✌️

**Comment by Sti2nd** [comment]
I can report that VS Code does not use the name "File Explorer", but "Explorer" for the name of its explorer. [Link to VS Code docs](https://code.visualstudio.com/docs/getstarted/userinterface#_explorer). Could be worth changing to the correct name to avoid confusion.

**Comment by wwlorey** [comment]
@Sti2nd thanks for that suggestion. Tracking here: https://github.com/microsoft/vscode-azurestorage/issues/954
