### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Dmarch28** [microsoft/vscode-azurestorage#944]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.uploadToAzureStorage
Error type: AuthorizationFailed
Error Message: The client 'OdentheGray@AtomicMass3B9.com' with object id 'ba0f5140-5f04-4da9-aa19-e814f6c9eac3' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/81837647-dd76-460a-9400-714d988f655b/resourcegroups/atomicmass3b9' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.11.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:74401
extension.bundle.js:31:764389extension.bundle.js:31:764389
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
