### ISSUE TITLE
vscode az-file system upload 

### ISSUE THREAD

**Issue by RaspiRepo** [microsoft/vscode-azurestorage#945]
Does this occur consistently? Yes
Repro steps:

1. installed vscode azure file system extension
2. create new share files system from vscode

Action: azureStorage.uploadToAzureStorage
Error type: Error
Error Message: Cannot upload to Azure from an Azure resource.

Version: 0.11.0
OS: darwin
OS Release: 20.2.0
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:515:405950
fulfilled extension.bundle.js:515:405221
processTicksAndRejections task_queues.js:97:5
```

Successfully created storage account "skuchainbackups".
Error: Cannot upload to Azure from an Azure resource.

**Comment by nturinski** [comment]
Hi @RaspiRepo 
Thanks for using the Azure Storage extension.  It looks like you're trying to upload an Azure resource from an Azure resource. 

If you want to transfer a resource between Azure storage accounts, you'll need to download the resource locally first, and then upload the local file to the other Azure resource.

Please let me know if that resolves your issue!

**Comment by RaspiRepo** [comment]
Got it Thanks for update
