### ISSUE TITLE
Deleting all selected blobs

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-azurestorage#951]
It would be time-saving if one could delete all selected blobs in one go! Right now it is possible to select several blobs, but right clicking and choosing "Delete" only deletes one.

This is a feature request.

**Comment by Sti2nd** [comment]
I don't know how VS Code extensions works internally, but if this Azure Storage extension is reusing the same Tree view as the built in Explorer in VS Code, maybe you can get this functionality working just by looking at how it is done in the Explorer 😇

**Comment by alexweininger** [comment]
Hi @Sti2nd, this feature has been released in the latest version of the extension https://github.com/microsoft/vscode-azurestorage/releases/tag/v0.15.0 🎉
