### ISSUE TITLE
There is an error after clicking the blob container name in the editor

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#952]
**OS:** Win10
**Build Version:** 20210316.1

**Repro Steps:**
 
1. Create a storage account -> Create a blob container -> Create an empty blob -> Open the blob in VS Code.
2. Click the blob container name in the editor -> Check whether pop up an error.

**Expect:**
There is no error.

**Actual:**
There is an error.
![st](https://user-images.githubusercontent.com/57662131/111587090-b306ae80-87fc-11eb-8a04-4ff35018387e.gif)

**Comment by wwlorey** [comment]
We should see if we can intercept that ugly error and throw something else
