### ISSUE TITLE
Rename "Open in File Explorer" command to "Open in Explorer"

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestorage#954]
From https://github.com/microsoft/vscode-azurestorage/issues/941#issuecomment-802753574

It looks like VS Code renamed the file explorer to just "explorer": https://code.visualstudio.com/docs/getstarted/userinterface#_explorer

**Comment by nturinski** [comment]
I didn't want this to close since it's a simple string fix and makes sense to do.
