### ISSUE TITLE
There is no verification prompt when entering a file share value with 0.99999999999999999

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#960]
**OS:** Windows
**Build Version:** 20210329.1

**Repro Steps:**

1. Expand a storage account -> Create a file share with value 0.99999999999999999.
2. Check whether pop up a verification prompt.

**Expect:**
A verification prompt "Value must be between 1 and 5120"  pops up.
![image](https://user-images.githubusercontent.com/62053665/112953890-7332b600-9170-11eb-87ae-8463f8e8c0c1.png)

**Actual:**
There is no verification prompt and succeed to create a file share with value 0.99999999999999999.
![image](https://user-images.githubusercontent.com/62053665/112954020-965d6580-9170-11eb-9ebb-d30f35061020.png)

**Comment by wwlorey** [comment]
Thanks for the issue, I don't think this is something most users run into
