### ISSUE TITLE
Delete container

### ISSUE THREAD

**Issue by MiguelQueiroz** [microsoft/vscode-azurestorage#964]
Hello, I was using this Azure VS code extension to try it. And then I wanted to remove it from the explorer.
So I clicked Delete container, I though it meant "delete the reference" not the container... now All the container is GONE!

This is very dangerous, it should have a clearer message, that it is referring to the real azure storage data not "local" data
:(

How do I unlink the Azure subscription? It is not Delete for sure! Now I know, but how you do it!?
Is this the option? Or will this also remove all my other containers!? 

![image](https://user-images.githubusercontent.com/2479868/114200516-31162b00-994d-11eb-9801-2eae01cfa19e.png)

**Comment by wwlorey** [comment]
You can "unlink" your subscription using the "Azure: Sign Out" command via the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)

![Screen Shot 2021-04-14 at 3 32 43 PM](https://user-images.githubusercontent.com/22795803/114788627-a9f2f980-9d36-11eb-8674-b62729482177.png)
