### ISSUE TITLE
The input textbox of the name pops up again when creating a blob with the name "/a/b/c/test.txt"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#970]
**OS:** Windows
**Build Version:** 20210426.1

**Repro Steps:**
1. Create a new storage account -> Create a new blob container for it.
2. Right Click the blob container -> Create Empty Blob -> Type blob name `/a/b/c/test.txt` -> Enter.
3. Check Whether the input textbox of the name pops up again.

**Expect:**
The input textbox of the name doesn't pop up again.

**Actual:**
The input textbox of the name pops up again after typing the name `/a/b/c/test.txt`.

**More Info:**
1. Pop up an error "c.createChild is not a function" after creating the blob.
2. Only display the `test.txt` file under the "blob container" node after creating the blob, the folder displays after refreshing.
3. The `test.txt` file can't be opened. 
![abc](https://user-images.githubusercontent.com/57662131/116210544-8d62b280-a775-11eb-90f1-4cc014196f40.gif)
4. This issue doesn't reproduce when typing a name that start with a number or letter.

**Comment by wwlorey** [comment]
This probably has to do with the leading slash

**Comment by alexweininger** [comment]
Do we want to just automatically strip the leading slash from the input here?

**Comment by alexweininger** [comment]
We should try to mirror what the service does and not try to create tree items on our own. We may be able to easily accomplish this by refreshing the Blob Container after creating a blob.
