### ISSUE TITLE
Files copied onto storage are empty

### ISSUE THREAD

**Issue by wdwit** [microsoft/vscode-azurestorage#975]
Hi all,

The problem I am running into is that when I copy a file onto a blob container, it creates an empty file. The name is correct, but the content is not copied over.
This happens when I am connected to a compute instance and use the Azure Storage extension to add the blob container folder to my workspace.
![Screenshot 2021-05-21 at 12 27 07](https://user-images.githubusercontent.com/6901507/119123887-58721480-ba30-11eb-8fc2-ef1d933dd9ce.png)
![Screenshot 2021-05-21 at 12 30 54](https://user-images.githubusercontent.com/6901507/119123939-6889f400-ba30-11eb-8010-6df25c2a9f68.png)

I then copy a file from the compute instance to the blob container folder (drag and drop or ctrl+c ctrl+v). VSCode shows that is it copying the file.
![Screenshot 2021-05-21 at 12 25 55](https://user-images.githubusercontent.com/6901507/119124171-aab33580-ba30-11eb-8cac-5981224c3f95.png)

There are no errors that pop up while doing this, but after it is finished copying, the file in the blob container is empty. At this moment I can copy the contents of the original file on my clipboard and paste it into the file on the blob container, but this does not work for big files.

I discussed this with @shsuman who suggested to open a issue here. Let me know if more details are needed.

**Comment by wdwit** [comment]
If I try to download the file from storage to the compute instance, or if I try to upload directly using the storage extension, I get an unexpectedQuit.
![Screenshot 2021-05-21 at 12 40 36](https://user-images.githubusercontent.com/6901507/119125298-e8fd2480-ba31-11eb-8840-50d2d36323fd.png)
![Screenshot 2021-05-21 at 12 41 35](https://user-images.githubusercontent.com/6901507/119125307-e995bb00-ba31-11eb-885e-f41d4c175e1f.png)

**Comment by SiddhanthUnnithan** [comment]
Can we validate whether these operations work in a Remote-SSH window?

**Comment by wwlorey** [comment]
@wdwit, regarding the "UnexpectedQuit" error: the extension relies on the `libsecret-1-0` package in linux to make resource transfers. Unfortunately it looks like that package is not installed by default in compute instances and it needs to be installed manually. Here's more info on how to do that from our wiki: https://github.com/microsoft/vscode-azurestorage/wiki/Known-Issues#azcopy-on-linux

@SiddhanthUnnithan the upload/download operations work as expected using a standard VM connected via remote-ssh as well as in a compute instance with `libsecret-1-0` installed.

**Comment by wwlorey** [comment]
The original issue (empty blobs being created if you drag/drop a file into the file explorer) reproduces for me

**Comment by shsuman** [comment]
@SiddhanthUnnithan @AbeOmor Will it be feasible to add the libsecret-1-0 package to the compute instance base image ?

**Comment by wdwit** [comment]
@wwlorey installing libsecret-1-0 did indeed solve the upload/download problem! It would be very helpful if libscret-1-0 will be added to the base image.
The empty blob issue is obviously less of an issue now, but the behavior is still strange. To me, it is fine if the drag+drop and copy+paste operations are not supported as long as it is clear it is not supported (error code or no response).
