### ISSUE TITLE
[Suggestion] It would be better to keep the error messages consistently under the "Blob Containers/File Shares/Queues/Tables" nodes of the attached storage account after deleting it from Subscription

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#980]
**OS:** Win10
**Build Version:** 20210604.34

**Repro Steps:**

1. Create a storage account -> Copy the connection string to it -> Attach the storage account.
2. Delete the storage account -> Expand the attached storage account -> Expand all nodes.
3. Check the error messages under the nodes.

**Actual:**
There are different error messages under the "Blob Containers/File Share/Queue/Tables" nodes.
![image](https://user-images.githubusercontent.com/62053665/121144098-484f9700-c870-11eb-8e47-c61f5dfdfb70.png)

**Suggestion:**
It would be better to keep the error messages consistently under the "Blob Containers/File Share/Queue/Tables" nodes.

**Comment by nturinski** [comment]
The error is being thrown by the API call in the cases of Blobs and Tables.  I think that the error is clear enough-- that the storage account couldn't be found.  I don't think it's worth the effort to make these error messages identical.
