### ISSUE TITLE
The newly created blob isn't highlighted in Azure view after it's created

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#981]
**OS:** All
**Build Version:** 20210604.34

**Repro Steps:**
1. Right click one blob container -> Create Empty blob... -> Enter a name for it to create a blob.
2. Check whether the cursor focus on this new created blob in Azure view.

**Expect:**
The cursor focus on this new created blob in Azure view.
![image](https://user-images.githubusercontent.com/45614674/121150369-0e818f00-c876-11eb-83c7-0ec2a16009f4.png)

**Actual:**
The cursor doesn't focus on this new created blob in Azure view.
![image](https://user-images.githubusercontent.com/45614674/121150194-e42fd180-c875-11eb-826b-efd32a751a11.png)

**More Info:**
This issue also reproduces for new created file/blob container/file shares.

**Comment by nturinski** [comment]
Hi @v-ruizh

Both @wwlorey and I couldn't reproduce this.  Are there any other steps that we should be aware of to make this behavior happen?

**Comment by v-ruizh** [comment]
@nturinski There is no other steps for this issue. 
Create an empty blob, the blob file will be opened and the cursor focus on it. The new created blob should be selected in **Azure View**. That means the new opened blob should be selected(highlighted).

The actual result is that the new blob is opened but it isn't selected(highlighted) in Azure view.
