### ISSUE TITLE
The folder is not completely deleted when refreshing the blob container during deleting a folder

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#982]
**OS:** Win10
**Build Version:** 20210604.34

**Repro Steps:**

1. Expand the Storage account -> Blob Containers -> Right click a blob container -> Select "Upload Folder..." -> Select a folder to upload.
2. Right click the uploaded folder -> Delete -> Refresh the blob container during deleting the folder.
3. Refresh the blob container after deleting the folder completely. 
4. Check whether delete the folder completely.

**Expect:**
Succeed to delete the folder completely.

**Actual:**
The folder is not completely deleted.
![11](https://user-images.githubusercontent.com/62053665/121164186-fe6fac80-c881-11eb-8425-f35293bd14bf.gif)

**More Info:**
This issue doesn't reproduce for file share.

**Comment by nturinski** [comment]
Do the files delete eventually after the refresh?

**Comment by motm32** [comment]
Fixed by #1111
