### ISSUE TITLE
Accessing a file from Azure Blob Storage using VSC

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-azurestorage#998]
As a student, I want to be able to download a file from Azure Blob Storage using VSC extensions. 

**Observation:** This is not currently possible without an Azure account/if you're not downloading a file that someone else is hosting in Blob Storage. Current experience for students in classroom is:
1.	A professor provides a link to a data file hosted in Blob Storage
2.	Students paste the link to a browser, then download it to their machine
3.	Students move the data file into their local repo location and opens VSC

**Suggestion:** New feature where you can paste and download a file from a URL, and it will open in VS Code. AKA remove step 2 in the process, where students would be able to download the data from Azure Blob by pasting the link directly on VSC (via the Azure Storage extension) without going to the browser.

**Benefit:** Can access files that others share with you via URL from storage right from VS Code, without going to browser. Provide a smooth experience for sharing datasets.

**Comment by nturinski** [comment]
As part of this feature, I'm planning to add the following:

- [ ] Generate a SAS token and URL for Blob Containers and File Shares and their children
- [ ] Downloading a container or file share by right click
- [ ] Downloading a container, file share, directory, or file by passing in a SAS url
- [ ] Uploading a container, file share, directory, or file by passing in a SAS url
